### ISSUE TITLE
Integrate TravisCI to loklak_webclient

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#1]
It's a good thing to have the TravisCI integrated right from the start to enable test driven development.

**Comment by sudheesh001** [comment]
Dependant on fixes in #4 - P1 fixes needed.

**Comment by sudheesh001** [comment]
It looks the whole setup installs flawlessly without throwing errors during installation of the isparta module. Errors during installation on Mac OS X machines needs to be investigated.

The log is [here](https://gist.github.com/sudheesh001/60fcda375add80001a3f)

**Comment by sudheesh001** [comment]
Build information: https://travis-ci.org/sudheesh001/loklak_webclient/builds/61964763

the test file checks if the build/** folder is complete but since `gulp dev` runs infinitely instead of just building it, the travis build information at the end displays Failed but the first pass where Travis doesn't really complain.

Do we merge this ? @Orbiter  @mariobehling

**Comment by Orbiter** [comment]
automatic testing is good. Does this add additional work on you, when commiting code? Or does it simply create an alarm if something goes wrong?

**Comment by sudheesh001** [comment]
As of now its designed to just create an alarm if something goes wrong. No additional work during commits as of now.

**Comment by Orbiter** [comment]
ok fine! lets close this to tidy up things. Please reopen if testing must be enhanced
