### ISSUE TITLE
Dashboard view for twitter wall users

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#103]
Once a user has logged in and created customized twitter walls, they should be able to view, start and edit them.
* Show a dashboard view with user created twitter walls
* Options to edit a created twitter wall

**Comment by mariobehling** [comment]
@aneeshd16 This is an issue for a long time already. What is the status?

**Comment by mariobehling** [comment]
Related issue: https://github.com/loklak/loklak_webclient/issues/102

**Comment by aneeshd16** [comment]
#102, #103, and #74 are to be implemented together.Can we move this to M2.5?

**Comment by mariobehling** [comment]
Yes, please do. Maybe unify some of the issues if possible.

**Comment by mariobehling** [comment]
Could you provide a mockup about your ideas, please? Is the wall main page and a dashboard the same?

**Comment by aneeshd16** [comment]
Yes, the main wall page and dashboard should be the same.

Anon user:
![image](https://cloud.githubusercontent.com/assets/5436027/8507177/8ee75c84-2254-11e5-8cc6-091a62d4db1e.png)

Logged in user:
![image](https://cloud.githubusercontent.com/assets/5436027/8507179/97e211a8-2254-11e5-982b-b2ebf5ce68a1.png)

**Comment by mariobehling** [comment]
What about analytics?

**Comment by mariobehling** [comment]
Ok, this looks like a good start, that people can use I guess.

**Comment by mariobehling** [comment]
Please do not use a scrollbar, instead make a grid system with css that adapts to the width and moves walls to the next row. 

![screenshot from 2015-07-07 19 59 06](https://cloud.githubusercontent.com/assets/1583873/8553313/d94d9a82-24e2-11e5-9eb4-e83bf22e1799.png)

**Comment by aneeshd16** [comment]
That's funny, i already did exactly that in https://github.com/loklak/loklak_webclient/pull/316!

**Comment by mariobehling** [comment]
Awesome!

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/8566088/2aca0c24-2579-11e5-8391-7668c19195bf.png)

**Comment by mariobehling** [comment]
Does work if I have three walls next to each other. If width is limited it is expected that all the walls display below each other.

![screenshot from 2015-07-08 11 49 27](https://cloud.githubusercontent.com/assets/1583873/8567669/9625ea18-2567-11e5-9b64-2adbd592bb6f.png)

![screenshot from 2015-07-08 11 49 54](https://cloud.githubusercontent.com/assets/1583873/8567673/9966dc32-2567-11e5-9189-c286ba7493a5.png)

**Comment by aneeshd16** [comment]
This is solved now. test.loklak.net/wall

**Comment by mariobehling** [comment]
Fantastic! What do you need to implement Popular Walls now?

**Comment by aneeshd16** [comment]
@mariobehling , comments here #273

**Comment by aneeshd16** [comment]
This has been implemented. Further enhancements and modifications are in other issues.
