### ISSUE TITLE
How to deliver results with OR operation of parameters

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#106]
Currently, when a search query is sent to `api/search.json`, it returns only results which contain ALL the query parameters. 
For eg, if if my query is `q=@aneeshd16 #loklak``, it would return tweets containing BOTH the @aneeshd16 mention and the #loklak hashtag. This also corresponds to twitter's own search where an AND operation is used.

However, the desired functionality is an OR operation. Results should contain ANY of the query parameters. How could this be implemented? My thoughts so far:
1. For each query parameter, a separate request is made, and then the results are collected in a single place and sorted by `created_at`. This could be a viable approach, if the requests are made in parallel (provided loklak_server can handle them)
2. Have support for OR operations in the loklak_server. @Orbiter

**Comment by Orbiter** [comment]
OR support has to be exactly the same as implemented in twitter. This is not yet supported in loklak_server. While this looks simple in the first place, it's not if you consider that the solution must be a complete implementation of any logical term parsing and normal form generation out of that to create an appropriate elasticsearch query.
The implementation has already startet; tracked with issue in loklak_server in https://github.com/loklak/loklak_server/issues/41

**Comment by aneeshd16** [comment]
I am not familiar with elasticsearch, so I can't comprehend the complexity, but great to know that this will be implemented!

**Comment by Orbiter** [comment]
issue can be closed here because there is no action on the side of loklak_webclient required. The coding on server side is tracked in https://github.com/loklak/loklak_server/issues/41
