### ISSUE TITLE
Post on behalf of an organization for allowed members

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#109]
I was speaking to a few members of the Mozilla community about loklak and how for the upcoming events we could use this as a tweet wall and a stat analyzer, They came up with a requirement which they believed would be important for most other open source organizations who want to use this platform.

Say for example, Mozilla India signs up with our service, they have the option of setting a few of its administrators for that account similar to how Facebook pages can have multiple `roles` to different members and each member can post on behalf of the page, Many times there are multiple people using the organization account, it'd be a good idea if the same system could be implemented and if validated, the post be sent by a user in his own account via the organization account.

So if we have to implement this, we'd need the users to also be signed up with loklak while at the same time the organization too, then the organization can set the rights to a specific user handles who could be authorized to post, when they make a post on behalf of the organization we post the tweet and append the short code of the person who posted at the end of the tweet, for eg. I post on behalf of mozilla india, from my account, Once it authenticates me as a user and as a valid member with the rights to post on behalf of the organization, it append `-SS` to the end of the post, similarly `-MB` if Mario does it on behalf of Fossasia etc..,

Would we be able to support such a functionality ?

**Comment by mariobehling** [comment]
@sudheesh001 Let's build a MVP (minimum viable product first). This can come later.

**Comment by sudheesh001** [comment]
Needs support from https://github.com/loklak/loklak_webclient/issues/74 @aneeshd16 Lets discuss on what we need to do to move towards this.

**Comment by mariobehling** [comment]
Before that is M2.5 Before we need this feature, there are lots of issues to solve.

**Comment by mariobehling** [comment]
Postponing this. Let's reopen this feature request when needed.
