### ISSUE TITLE
Create a statistic table widget

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#11]
The context of this feature is described in https://groups.google.com/d/msg/loklak/7azwyuslmTU/JXh0vrgXhSAJ

The framework page for this feature is created with https://github.com/loklak/loklak_webclient/issues/9
There should be a widget which shows the three top-windows in the following example: 
![message_evaluation_sketch](https://cloud.githubusercontent.com/assets/238730/7424468/b3fea152-efa1-11e4-8c6d-8bc85c093178.png)

Data is delivered by the loklak_server backend using calls like http://loklak.org/api/search.json?q=spacex%20since:2015-04-01_17:10%20until:2015-04-23_18:20&source=cache&count=0&fields=created_at,screen_name,mentions,hashtags&limit=6&timezoneOffset=-120

The widget must be given a field name and possible a coulouring setting so it would be possile to change it's style a bit.

**Comment by Orbiter** [comment]
who is working on this?

**Comment by sudheesh001** [comment]
I am working on this.

**Comment by Orbiter** [comment]
I just learned that it is not called 'tweeters' but 'twitterers' .. please change that word :)

**Comment by Orbiter** [comment]
what happened with this feature, it was read? Please integrate with the statistic histogram, we need this tomorrow... :)

**Comment by fuksi** [comment]
Just started continuing on this, I hope I can integrate before midnight (10pm here GMT +3). Trying the new master, ```npm install``` really take time though ;)

**Comment by Orbiter** [comment]
Thank you Phuc, its looking great! What I wonder is, if this looks better if we replace the percentage with the actual number of tweets. Or can we have both? like "456 = 7%"

**Comment by Orbiter** [comment]
Good work, lets close this feature to move forward to even more epic things :)
