### ISSUE TITLE
Implement a realtime display of tweets on a map

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#110]
The user select a region on the map and loklak_server delivers coordinates with a geoJSON to be displayed. The map shall then draw markers on the map and pop up small text speech bubbles containing the tweet text. Your part is it, to identify new tweets and animate them (not all at once) if more than one is new. This is repeatet again after a give time has passed (time is given in the server response).

We will have three kinds of locations: fuzzy, as given by twitter (only city name) and exact one (as tweetet with loklak). Furthermore, very fuzzy, which are translated from location names within the tweet texts without given locations from any frontent. lokal_server will translate into coordinates.

The fuzzy and very fuzzy locations will point to the same coordinates every time. Maybe we can randomize them a bit to make them looking nice when they appear on the map. However, we should have some kind of visual effect which makes them distinguishable, maybe different colour codes. I will provide some information in the geoJSON to identify how exact the coordinates are.

please start right now to develop a framwork for that so we know which tools will be used. Please also define the geoJSON that you would expect and create a static geoJSON for that. I will then create the live API using your geoJSON specification. Furthermore, we should start to define feature-issues for all the details that are necessary to measure the progress.

This feature can either be seen as part of the wall, but should also be usable without an account, like the normal tweet search. 

The idea with integration in the wall is: we must identify something that should only be usable after registration and then the feature can be selected within the wall functions. Lets start without the wall integration and do that later.

On my side I will start to integrate OpenGeoDB to automatically identify location name strings, so we will have a lot of tweets with coordinates in the database and a lot of things going on on the map.
For the API definition: I expect that you submit either left-top coordinates of the map and a width and height OR the center and a distance, so I can select the tweets. Just let me know what you believe is the common/best way to do that.

Maybe we should also plan to have a search input option as well, i.e. if the number of tweets for a location is too high. Maybe we should have that option also from the very beginning.

Maybe instead of geoJSON it could be possible to submit queries simply in the given search interface of loklak_server, when I extend that with coordinates. I don’t know whats necessary for the map from the server side. Maybe you translate what you get into geoJSON anyway?

hat can be done
http://wiki.openstreetmap.org/wiki/API_v0.6#Retrieving_map_data_by_bounding_box:_GET_.2Fapi.2F0.6.2Fmap
http://boundingbox.klokantech.com/ this is a live example using it

ok, then would it possible to simply extend search.json with bbox=left,bottom,right,top; like /api/search.json?timezoneOffset=-120&q=party&bbox=left,bottom,right,top

right now we don’t have coordinates, only place_name text fields. You can trigger results containing that using the „/place“ constraint, like /api/search.json?timezoneOffset=-120&q=party+%2Fplace

so we can do one thing that we can get cordinates from place by using OSM API
I will add lon/lat coordinates for our own, exact-location tweets and fill the same field using a location-name to location-coordinates table.

{
"type":mapdata,
"geo": {
"type": "Point",
"coordinates": [-122.09,37.64 ]
},
"properties": {
"name": "@prasht63",
"tweet": "Maps is here",
}
}
The translation will probably be done without OSM API because of the mass-data aspect (ALL tweets will be tried to be translated!)

the first step is to add coordinates in a way elasticsearch likes them because they are used to select the tweets. A second step would be a translation into geoJSON. However, in the search results from api/search.json would be the data for elasticsearch.

**Comment by prasht63** [comment]
### Idea
The idea is to develop a standalone tool to let the user draw a box on the map using drag action and then display realtime tweets in the bounding area.This will be coupled with a Search feature at a later stage where the user will be able to filter by Country,City,Places.

###Features
* A standalone tool which a user can without any login.
* A user can select a area on map by drawing a rectangle and all the tweets coming from that area will be   plotted on the map.
* On clicking the bubbles user can see the tweet data.
* Different colour code for different Hashtag
* Heat Map Generation to analyse the trends from the area.(To be discussed)
* Search Option to map tweets from a particular city, country or place.

###Tech Stack
OpenStreetMaps API with Leaflet.JS for Map Integration
AngularJS with jQuery on BootStrap 3.0 for front-end development
Gulp as Task runner
Loklak_Server as Backend service

**Comment by mariobehling** [comment]
Looks good to me as a start. Would be great to see mockups. Regarding the "draw function of a rectangle", I am not sure why we need to draw a rectangle. Just show all the tweets available for a hashtag (or several) or other relevant searches in a specific area.

**Comment by prasht63** [comment]
As discussed with Michael we are doing this as a standalone feature initially so should we create a new repo on loklak or should I start with a new branch in loklak_webclient?

**Comment by prasht63** [comment]
The need for a rectangle is to select a area as per users requirement.That feature what you are saying will be present by default.I will soon upload mockups then it will be a lot clearer.

**Comment by sudheesh001** [comment]
I think you should go with a new branch, that'll make it easier to keep all the issues in one place rather than scattering across different areas.

**Comment by Orbiter** [comment]
I shifted this to milestone 2 because the backend, providing the locations for the map does not yet enrich the tweets with geolocations. The backend issue is at https://github.com/loklak/loklak_server/issues/45

**Comment by Orbiter** [comment]
Just right now I have send you a test file containing a loklak search result with geolocation details.
As an example, here is one record:
```
{
    "created_at" : "2015-06-10T09:49:06.116Z",
    "screen_name" : "*geojson*",
    "text" : "Depuis juin 2011, la mairie du 20e arrondissement propose un nouvel espace d’expression aux artistes: le mur du square Karcher situé au 163 rue des Pyrénées. Tous les deux mois environ, des performances sont organisées sur ce mur de 40 mètres de long environ, en lien avec l’association Art Azoï. Ces oeuvres éphémères permettent une variation des styles et des techniques offerts à l’oeil des passants. Cet espace d’expression et de création graphique est un lieu de création, de médiation culturelle, et anime le quartier dans lequel il se situe. En effet, toute les générations profitent de la performance artistique et commentent pendant les semaines suivantes l’œuvre ainsi co-élaborée",
    "link" : "http://www.paris-streetart.com/lieux/square-karsher",
    "id_str" : "475b0c14_65",
    "source_type" : "IMPORT",
    "provider_type" : "GENERIC",
    "provider_hash" : "475b0c14",
    "retweet_count" : 0,
    "favourites_count" : 0,
    "images" : [ "http://www.paris-streetart.com/photos/map/spot/square-karsher-t.jpg" ],
    "images_count" : 1,
    "place_name" : "Square_Karsher",
    "place_id" : "",
    "location_point" : [ 2.401237, 48.859913 ],
    "location_radius" : 0,
    "location_mark" : [ 2.401237, 48.859913 ],
    "location_source" : "REPORT",
    "hosts" : [ ],
    "hosts_count" : 0,
    "links" : [ ],
    "links_count" : 0,
    "mentions" : [ ],
    "mentions_count" : 0,
    "hashtags" : [ ],
    "hashtags_count" : 0,
    "without_l_len" : 690,
    "without_lu_len" : 690,
    "without_luh_len" : 690,
    "user" : {
      "name" : "",
      "screen_name" : "*geojson*",
      "profile_image_url_http" : "",
      "appearance_first" : "2015-06-10T10:04:08.204Z",
      "appearance_latest" : "2015-06-10T10:04:08.204Z"
    }
  }
```

Right now, there is one important attribute for the visualization of markers: ```location_mark```
I attach two locations in the json:
- the center of the location in ```location_point```
- if the location is a point, the value in ```location_radius```is 0. If it is large, there is a number which means meter. An example would be the marker for a city with the radius of the city in this field
- a single location within the radius is in ```location_mark```. This is set randomly within the the radius of the location and shall be used for visualization of the marker. The reason for using such a random field is, that a location within a tweet can be very weak but we want to calculate a location anyway. If we then have thousands of location for i.e. Singapore, we don't want to have them overlapping in a single point, but evenly distributed in a cloud around the center. To prevent that these locations 'jump' every time you re-paint the map, they will be computet once and you get that location in this field.
- the source of the location in ```location_source```. This value will either be REPORT if it was received from an external source or ANNOTATION if we computed this location ourself using annotation techniques (i.e. geo-database matching)

Please use the example file as a static input for testing and change the already implemened map accordingly.

**Comment by Orbiter** [comment]
I added the priority label since this was intended for milesone 1 but was shifted since my input was missing. Now it should be the next thing to implement.

**Comment by Orbiter** [comment]
map extractions for a bounding box are implemented in the backend with feature https://github.com/loklak/loklak_server/issues/47

**Comment by Orbiter** [comment]
a live version can be tested now with https://github.com/loklak/loklak_server/issues/45#issuecomment-110718582

**Comment by Orbiter** [comment]
@prasht63 I don't see a use for a bounding box. I consider that every time the user changes the view on the map, the map submits a search request to loklak_server containing the view as bounding box. See https://github.com/loklak/loklak_server/issues/47 for details.

**Comment by mariobehling** [comment]
I am closing this issue, as we are working on more specific map issues now and the sample implementation was successful.
