### ISSUE TITLE
side Navbar on collapse should show loklak logo instead of word text

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#112]
Will fix this by tonight,

**Comment by Orbiter** [comment]
The navbar on top does not show the loklak logo. Its not visible if the topbar is not collapsed and not if it is collapsed.

**Comment by mariobehling** [comment]
![loklak-home](https://cloud.githubusercontent.com/assets/1583873/8076804/83287cfa-0f50-11e5-9c2a-f9bf8701f80e.png)
I am confused about this issue. Simply follow the screenshot. There is no traditional sidebar but a three column layout.
