### ISSUE TITLE
Render tweets with video

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#115]
+ Show link/thumbnail at first, load video as tweets are in focus
 + If video is tweet video, use iframe with given source in loklak result
 + Else:
  - Show logo, source of video (Youtube, Vimeo, Fp, etc..)
  - Request for embeded url of a html5-video-container

**Comment by fuksi** [comment]
Done with #139

**Comment by Orbiter** [comment]
good work!

**Comment by Orbiter** [comment]
I just added the recognition of vine.co video links, please embed those videos as well.

**Comment by fuksi** [comment]
No need to open this, all results without filters will be rendered automatically, doesn't matter what kind of links they have. Quick test on live: http://test.loklak.net/search?q=%23vine&timezoneOffset=-180
