### ISSUE TITLE
Enable topbar for all users and sidebar+topbar for logged in users

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#117]
All users will have a topbar that will have the main menu items like
* Home
* About
* Search
* Wall

Logged in users will also have a sidebar that will contain account related links.

### Implementation
Will use `ng-if` and `ng-class` directives to selectively hide/show elements based on a variable defined in the root scope.
The var is `root.sidebarEnabled` defined in `js/on_run.js`. The default value is false. If the user is authenticated, simply set the value to true using  `onEnter : function($rootScope){$rootScope.root.sidebarEnabled=true;}` as a parameter to your route in `js/routes.js`.

**Comment by aneeshd16** [comment]
This has been solved. Will be there in the next pull request.

**Comment by aneeshd16** [comment]
Closed by c286aac5589ac772b90973722a09f94b1ace7d01

**Comment by mariobehling** [comment]
Where can I see the deployed version for testing? Did you take into account the that we had decided to not use a sidebar as shown in LTE but rather a twitter like sidebar?

**Comment by aneeshd16** [comment]
@mariobehling I have created a new issue for the twitter-like sidebar. #149
The main objective of this issue was to introduce the topbar and hide the AdminLTE sidebar.
