### ISSUE TITLE
Create a initial view for unauthorized users / to log in

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#119]
Create a new route to login from frontpage
and a modal to login directly from the current view. 

** Updated: details **
When accounts feature is completed from #74 and others:
- Create a global directive to manage authentification status, ran higest priority when load page
- If not loggin: 
   - Show a initial view like e.g. https://github.com/loklak/loklak_webclient/issues/119#issuecomment-121689038
   - Disable/hide features, those do not make sense to users
- If logged in:
   - Redirect to home view
   - Render home view accordingly
   - Enable all features
   - Include some information about available features at the home view

** Update UI and features as the issues progress **

When continue, continue with branch https://github.com/loklak/loklak_webclient/tree/InitHomeView

**Comment by sudheesh001** [comment]
Fixed via #179

**Comment by Orbiter** [comment]
This view is shown without user interaction when loklak.net is opened. This is not wanted. Log-in shall happen if the user clicks on log-in or if the user tries to access a function which needs log-in.

**Comment by mariobehling** [comment]
Please be inspired by twitter. Please follow up on this when accounts are done and we have a way for people to login to loklak without twitter. Moving it to 3.5 as I am not sure, when @aneeshd16 will get accounts implemented.

![screenshot from 2015-07-15 19 36 29](https://cloud.githubusercontent.com/assets/1583873/8705316/21cca518-2b29-11e5-9bb8-0698d23a0ba9.png)

**Comment by mariobehling** [comment]
What do you want to achieve exactly?
