### ISSUE TITLE
Propose Service/Projects to aggregate for loklak as search and tweet engine for the Internet of Things

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#120]
As a first step we are supporting twitter in loklak. Additional data providers can be other web services or machines - The Internet of Things. A core functionality in loklak is the aggregation of machine readable data, the evaluation of the data, and the conversion to human readable structure that are useful. These can be displayed in views such as a) maps with points, lines, colored areas etc., b) diagrams, c) info walls (twitter wall, media wall, activity wall) d) timelines and e) other forms (what are your ideas?). 

As a first step we are looking for services we can aggregate. Which Open Data projects can we start with? Think of sensor networks, wifi communities, health research data, open government data, environmental data and more. Please add projects and services you find here in this issue. Please include info about the format, if possible.

**Comment by mariobehling** [comment]
Let's collect some service where we can get data:

Yet Another Haze Index (Yahi) http://rolandturner.com/yahi/ | http://rolandturner.com/yahi/developers | https://github.com/rolandturner/yahi

Freifunk-Karte http://www.freifunk-karte.de/ | https://github.com/ffansbach/nodelist

Sahana Eden Disaster Management: E.g. http://nepal.sahana.io/eden/req/req

Ebola Data Availability: http://eden.sahanafoundation.org/wiki/Deployments/Ebola#Data

**Comment by sudheesh001** [comment]
Data Govt of India - https://data.gov.in/
Socrata Data sets - http://www.socrata.com/top-open-data-datasets/
Weather data - http://www.wunderground.com/weather/api/
Weatherbase - http://www.weatherbase.com/
World bank - http://search.worldbank.org/api/v2/projects
NASA  - https://data.nasa.gov/developer

**Comment by prasht63** [comment]
Earthquake Data :
http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php

**Comment by mariobehling** [comment]
Something to look at as well: Javascript based viewer for the netjson plugin of olsrd2. It uses XMLHttpRequests to load its data without reloading the webpage and uses the vis.js (http://visjs.org/) API to display the graph data: https://github.com/almende/vis
