### ISSUE TITLE
Create a modal to retweet tweet

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#123]
This can only be a modal, not a view. A separate view would remove the context of the action "retweet".

**Comment by fuksi** [comment]
Breakdowns of step 
- Create a modal, add listen on retweet button
- Embed basic info of the current tweets
![image](https://cloud.githubusercontent.com/assets/6878677/8614729/5696a70e-26f5-11e5-8d85-43942be51719.png)
- Retweet request is not available on hello.js docs, but functionality are still there: https://github.com/MrSwitch/hello.js/blob/master/dist/hello.all.js

**Comment by sudheesh001** [comment]
@fuksi Retweet functionality with hello.js required the ID to be passed, the function is already written, the modal seems like a great idea :+1:
