### ISSUE TITLE
Extra action on tweets

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#124]
Enable user to favorite a tweet
Enable user to also share the link via mutliple social media
Other than share link, user should be able to export current view, e.g. ```/search``` or ```/wall``` or ```/tweet```...

**Comment by fuksi** [comment]
This is partly overlapped. The current implementation of all views already enable user to use a string right away from the address bar.

Consider if needed to add a share gadget to share across social media.

**Comment by mariobehling** [comment]
Ok, so the next step is a sharing and embedding functionality https://github.com/loklak/loklak_webclient/issues/314

I guess we can close that then. Reopen, if there is anything missing. Thanks!
