### ISSUE TITLE
Analyze the composition of twitter search results

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#125]
The default results of twitter search are composed with different parts, which are inserted to the general results. Analyze the logic behind those parts, and create new issues to implement those:

Those part includes:
1. Accounts 
![image](https://cloud.githubusercontent.com/assets/6878677/8019566/526ad594-0c5e-11e5-8699-503d5d5e5b94.png)
2. Most? favorited 
![image](https://cloud.githubusercontent.com/assets/6878677/8019567/735a81a0-0c5e-11e5-9928-503d1bb09bd9.png)
3. Photos
![image](https://cloud.githubusercontent.com/assets/6878677/8019570/8fbc73b2-0c5e-11e5-8434-d313b2ca3f67.png)

**Comment by sudheesh001** [comment]
Wouldn't this be better for the server to keep mining the information it has and serve the information accordingly in its responses ?

**Comment by fuksi** [comment]
Take [this search](https://twitter.com/search?q=%23vow&src=typd&vertical=default) for example
I'm guessing that loklak server is only mining the ```Live``` view, tweet by tweet. The ```Top``` views are organized differently. In fact I don't know how it is evaluated, like, tweet with most reply first, or with most retweet first... It's might be too much/inefficient for the server to mine the ```Top``` view.

Meanwhile I already have some data that I can evaluate from the normal result: ```retweet_count```, ```favorite_count```, top mentions, top twitter..

@Orbiter What do you think about this?

**Comment by Orbiter** [comment]
this is a good idea but maybe it's better to get the top tweets from the loklak_server backend which has full access to the search index. The difference betweet top tweets and live tweets is, that top tweets have a popularity-rank. It's not so easy to detect that but your idea using retweet_count and favourite_count is good. But you cannot see so many tweets as the backend can see.

Lets do it in the following way: loklak_server will provide some search attributes which will either enable you to sort on the fields retweet_count and favourite_count in a given time frame, and you can then select these and compose them into the favourites.

I opened a loklak_server issue for this: https://github.com/loklak/loklak_server/issues/46

**Comment by Orbiter** [comment]
a solution for the sort order in loklak_server is now imlemented with https://github.com/loklak/loklak_server/issues/46

example:
http://localhost:9000/api/search.json?timezoneOffset=-120&q=fossasia&sort=favourites_count&source=cache

**Comment by fuksi** [comment]
@Orbiter the sort parameter doesn't seem to have effect
http://loklak.org/api/search.json?timezoneOffset=-180&q=jaha&sort=favourites_count
