### ISSUE TITLE
Enable user to choose color for their AdminLTE themes

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#126]
AdminLTE can be changed by included a different theme color css file and change class in body.  
- Enable the options  
- Combine all color theme css file to reduce http requests.

**Comment by mariobehling** [comment]
At the moment we don't know if AdminLTE is the future. We probably need a designer to make a new theme. Therefore the theme color for AdminLTE has a lower priority.

**Comment by sudheesh001** [comment]
This can be closed as we're safely moving away from the AdminLTE design. Please feel free to reopen in case its needed.
