### ISSUE TITLE
Top NavBar does not collapse on Screen Resize

### ISSUE THREAD

**Issue by prasht63** [loklak/loklak_webclient#128]
![image](https://cloud.githubusercontent.com/assets/2105062/8020324/4d2310ae-0c92-11e5-908b-677882284774.png)

**Comment by sudheesh001** [comment]
The responsiveness is breaking because of the right side bar i believe.

**Comment by aneeshd16** [comment]
It is because of the right side bar. Works fine when only top nav is present.
![image](https://cloud.githubusercontent.com/assets/5436027/8023023/4a0ac056-0d14-11e5-9ae3-cd406d51a70f.png)
![image](https://cloud.githubusercontent.com/assets/5436027/8023026/510c82f4-0d14-11e5-959e-79e73afd8df4.png)

**Comment by prasht63** [comment]
So do we need side bar? For now I have solved this with side bar.Should I submit a pull request it for review? 
![image](https://cloud.githubusercontent.com/assets/2105062/8028885/60a11ac6-0dd3-11e5-8244-49031c444656.png)

**Comment by sudheesh001** [comment]
@prasht63 Good work.
Tip: An easier way for you to test responsiveness is by using Chrome's inspector instead of resizing the screen :+1: 
Press Ctrl + Shift + I and in the inspector box that pops up, next to the search icon, there'll be a mobile icon, Click on that to toggle responsiveness on/off. Once you click on it, you'll have a black ruler on top and left side and a drop down.
![responsive](https://cloud.githubusercontent.com/assets/4545925/8028944/1e98e7a2-0dd4-11e5-9a90-0519a5dab337.PNG)
Choose the phone model and refresh. It'll make life easier.

**Comment by prasht63** [comment]
Yes I do use it, but the emulator on my browser is not working fine after update.Anyways thanks for the info I will stick to it.
Also whats the status on sidebar? Should I send a pull request?

**Comment by aneeshd16** [comment]
The sidebar has been disabled by default by the latest merge. I am not sure how the sidebar will be used, it's still under discussion. But you can commit the responsive sidebar all the same if it works okay.

**Comment by sudheesh001** [comment]
@prasht63 Yeah sure, PR the sidebar, I'll review it, if its responsive and works, there's no reason not to add it in.

**Comment by prasht63** [comment]
Since this has already been solved with the latest commit.So closing.

**Comment by Orbiter** [comment]
if I resize the search window it does not look nice, there is something broken in the top right corner.
Browser: Firefox

![topnav](https://cloud.githubusercontent.com/assets/238730/8070660/49de4e5e-0f03-11e5-8006-7027ab051839.png)

**Comment by aneeshd16** [comment]
Currently, our site doesn't look very good on small screens.
AdminLTE renders the search bar in the top nav as follows:
![image](https://cloud.githubusercontent.com/assets/5436027/8101078/34ad8480-1031-11e5-9183-a4573c03aaca.png)
I will push this feature in the next commit.

**Comment by prasht63** [comment]
@aneeshd16 you working on this?

**Comment by aneeshd16** [comment]
No, you can do it. Got a lot on my plate already :)

**Comment by prasht63** [comment]
No problem ! Keep up the good work!

**Comment by prasht63** [comment]
Moving it to #161
