### ISSUE TITLE
Angular controllers fail to work on gulp prod

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#131]
The problem is that some parts are minified. And the code that uses those parts is not able to understand the minified form.
This gives a possible solution. Need to check.
http://stackoverflow.com/questions/18950181/javascript-error-unknown-provider-tprovider-t-after-rails-minification-angul

**Comment by aneeshd16** [comment]
Linked to #114

**Comment by fuksi** [comment]
Done with pull https://github.com/loklak/loklak_webclient/pull/132

**Comment by fuksi** [comment]
@loklak/loklak_developers 
This is not solved. I'm opening this again. 
If we can't find a solution, I suggest that we don't minify main.js when deploying for now. 

**P/s i was also advised not to minify angular at all**

**Comment by sudheesh001** [comment]
@fuksi I think its best not to minify the files at all, Let us serve them directly without going through the minifying process, I've been working on this too since morning, its just because of the minifying that all the issues throw up. Can we exclude main.js from being minified.

**Comment by aneeshd16** [comment]
@sudheesh001 , the size difference is too much. Minified files are ~700KB, while i think the unminified are around 4MB.

**Comment by sudheesh001** [comment]
As of now lets prioritze, saving bandwidth isn't really the issue right now, it can be an optimizationm, we need to get the functionality up and running faster. Lets clean up later, the npm install process is also humongous with lots of libraries, it seriously needs a cleanup.

**Comment by prasht63** [comment]
@Sudheesh +1

**Comment by fuksi** [comment]
I'll still try out some approaches today. 4.4mb to 700kb is a big difference. Chrome dev tools literally freezed 10-15s to interpret the whole thing locally, but on live, it was only 1-2s.

**Comment by fuksi** [comment]
Done with #144
