### ISSUE TITLE
Gulp prod errror

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#133]
@loklak/loklak_developers 

At the moment we can't deploy on live because of this error.
If you can at least try to deploy ```gulp prod``` with the latest master to see if the error is environment related. 

@julianfox, this seems to be original gulp related, do you have any info on this?
```bash
[00:20:30] Using gulpfile ~/loklak_webclient/gulpfile.js
[00:20:30] Starting 'clean'...
[00:20:30] 'clean' errored after 8.1 ms
[00:20:30] Error: EACCES, rmdir 'build/css'
````
http://i.imgur.com/Gy2xFf5.png

P/s: It works fine with my remote server, fresh ubuntu14.04, npm 1.3.10, node 0.10.25

**Comment by mariobehling** [comment]
@fuksi what is the link to your remote server?

**Comment by fuksi** [comment]
Here is a static one: http://users.metropolia.fi/~dinht/build/
I'll turn on the another in a moment.

**Comment by mariobehling** [comment]
empty page for me

**Comment by sudheesh001** [comment]
This issue seems to be fixed. `gulp prod` works perfectly and as expected and documented doesn't start the node server but prepares the content for serving. Closing this.

**Comment by Orbiter** [comment]
I did not get this error any more after a fresh installation, however, I got a new one: https://github.com/loklak/loklak_webclient/issues/151
