### ISSUE TITLE
Import open data continuously and script account creation in loklak

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#134]
Let's think of how we can add information from Open Data portals and the Internet of things to loklak. As loklak will get more useful organizations will add data to loklak themselves. For the beginning we need to make the service useful and add data we find automatically.

I see the following steps. How do we automate these?

1. Crawl the web with our search engine and find suitable JSON files for loklak.
2. Categorize name of JSON owner and automatically create a loklak account (Questions: how do we create accounts? what is the naming convention? everyone account needs an email - what is the email? and every account should be re-created in twitter as well - how to script it?)
3. Create loklak tweets with time stamp of events in JSON files - Each time event gets a tweet.
a) How to create tweets? What is the specific content, e.g. xxx releases data about zzz.. What do we tweet exactly?
b) Questions how about "year time events" e.g. growth of gdp in Germany 2015 - what date - length do we assign? What is the tweet date?)
4. Each location (city, country, street) gets a hashtag
5. Each document period gets a png-animated map tweet
6. How do we show links to JSON on the web in the interface (the above should also be possible manually for people who have an account)?

**Comment by Orbiter** [comment]
I suggest to add different types of data step-by-step. I.e. first add geojson data. To do that, we can provide a 'submit' function in loklak where a user can simply paste an url with geojson content. This can then be submitted to the loklak_server backend which takes care of the import process.

Other types of content can be added later. Possible i.e.: geo-rss

The addressed identification of such imported tweets is important: either the tweets are identified with an user account of the user who submitted the source or they are anonymously imported using a technical account.
