### ISSUE TITLE
Change top bar to reflect twitter top bar / delete left sidebar

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#137]
At the moment AdminLET is our basis for development. But: This is just a way to start. We need to develop our own design and should reflect current design standards of twitter. The three column layout should also work for us. The LTE sidebar is not fitting into this design.

1. Please change our top bar to reflect the twitter top bar and include search.
2. Please delete the left sidebar.

**Comment by mariobehling** [comment]
Any update?

**Comment by sudheesh001** [comment]
Was stuck with the deployment problem, Will fix this after the discussion with @aneeshd16

**Comment by mariobehling** [comment]
This works in the version for users, that are not logged in. However as soon as logged in, there is another design at the moment.
