### ISSUE TITLE
Implement user accounts and authentication

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#138]
Please align the implementation of user accounts and authentication with other related tasks. Before we can authenticate with twitter, we need to be clear about how we implement authentication in loklak. What are your suggestions? This is kind of a basic feature that has a high priority.

**Comment by aneeshd16** [comment]
### General Notes
1. Sign in using Twitter has been done. Navigate to `/auth/twitter` and the auth flow begins. 
2. After auth, the `req.user` object contains all the user data including token and token_secret.
3. User data is also sent to loklak_server after login. Keys and user profile data can be retrieved thereafter.
4. For implementing any kind of twitter related actions, I would recommend to use the `twitter` npm module. An example for posting a tweet to twitter has been already completed.

### App Specific Notes (For twitter wall)
Using the apps property ` "apps" : {"wall" : {"type" : "horizontal"}} `, I can store the wallOptions object with the account. (Milestone 2)

**Comment by mariobehling** [comment]
@aneeshd16 What is missing? How can the user sign in at loklak?
> Navigate to /auth/twitter and the auth flow begins. 
Do you mean? - http://loklak.net/auth/twitter

**Comment by sudheesh001** [comment]
@mariobehling Yeah that's how the user logs in.

**Comment by mariobehling** [comment]
@sudheesh001 Did you try that link? Not working atm.

**Comment by sudheesh001** [comment]
Yes it works on local, are the app keys and secrets put correctly on the application config as well as the twitter app ? I documented the details into the readme file.

**Comment by prasht63** [comment]
@Mario I think currently due to #131
<https://github.com/loklak/loklak_webclient/issues/131> and #133
<https://github.com/loklak/loklak_webclient/issues/133>
http://www.loklak.net is not working properly.

**Comment by mariobehling** [comment]
Look, everyone should deploy a test version on an online server, where we all can test. We already had a discussion about local vs. online yesterday. Time is limited and it is not my goals to figure out server setups. I would like to test stuff. Issues should only be closed when they clearly work online on loklak.net as well. Does this make sense to you?

**Comment by mariobehling** [comment]
@prasht63 have you set up the client on a server of yourself yet?

**Comment by mariobehling** [comment]
@prasht63 Could you help to fix this, please?

**Comment by prasht63** [comment]
yes I have set it up <http://prasht63loklak.eu-gb.mybluemix.net/> but its
not working properly. I am looking as soon as I have running one I will
post it on the group.

**Comment by mariobehling** [comment]
@prasht63 Where are the map parts that you made? How can I test and access it?

**Comment by prasht63** [comment]
Hi
currently its not online.I am trying to put it online.If you have
loklak_webclient locally set up, you can go to localhost:3000/map to access
it.For the preview you can see the screen shots I am attaching here.[image:
Inline image 1]

**Comment by mariobehling** [comment]
I can always set it up locally, but my interest is to see loklak running on a server. At the moment, it looks like none of the devs is able to set up a loklak server running without issues on the web. @/all Please keep it up! Hope to see some progress today.

**Comment by sudheesh001** [comment]
This is already implemented and tested on my production server.
loklak.cloudapp.net:3001/auth/twitter/

**Comment by mariobehling** [comment]
@sudheesh001 I think you have a different understanding, what it means, that a feature is implemented. I would like to see a login button on the top right or a login page. After I login I get the features for logged in users. How can I login in the user interface? How is this feature integrated in the UI?

**Comment by sudheesh001** [comment]
@mariobehling I think you're talking about #143 I seperated the UI UX issue of the login from the implementation of user authentication.

**Comment by mariobehling** [comment]
@sudheesh001 Thanks for clarifying. Please feel free to cross-reference such links in future. Cheers!

**Comment by Orbiter** [comment]
I don't have had the experience that I was able to log into twitter from the loklak_webclient interface since there is not even a log-in button. I expect that there is a button which I can click on, then authentify and finally see the loklak webinterface which shows that I am logged in.

**Comment by sudheesh001** [comment]
@Orbiter The login button is present in the top right corner with the latest commit 
![297376fe-0f0c-11e5-9282-1b691704f04f](https://cloud.githubusercontent.com/assets/4545925/8075363/4d79a0fe-0f5d-11e5-86bb-4d6bf100819a.png)

**Comment by Orbiter** [comment]
Right now, no user account data is present in the loklak_server database which means that the /api/account.json servlet was never called. As long as we don't have account data of the user, this issue is not solved!

**Comment by aneeshd16** [comment]
Will be solved after #171

**Comment by sudheesh001** [comment]
#171 merged and checked, this is good to close.
