### ISSUE TITLE
Set up loklak on test.loklak.net

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#146]

**Comment by fuksi** [comment]
Move to #158

**Comment by Orbiter** [comment]
test.loklak.net must be assigned in DNS setting

**Comment by Orbiter** [comment]
http://test.loklak.org/ is now working … but thats not the place where it should be. I just did that to test if port rerouting works. still test.loklak.net must be assigned by @mariobehling

**Comment by mariobehling** [comment]
Working now, so closing it. Cheers.
