### ISSUE TITLE
Implement twitter-like sidebar for logged in users

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#149]
The sidebar should be "Column 1" of the three column layout shown below.
![loklak-home](https://cloud.githubusercontent.com/assets/1583873/8065412/93fe4a9c-0ee1-11e5-9e23-15bffe5412de.png)
Related to #117

**Comment by sudheesh001** [comment]
![screen shot 2015-06-13 at 1 57 46 pm](https://cloud.githubusercontent.com/assets/4545925/8143802/89164c1c-11dc-11e5-9fb4-400aab4e53f7.png)

Current implementation, leaving the right side for the Trends to come up, This just got merged to master after review by @aneeshd16 and @prasht63 , merged by  @prasht63 

Please close this in case this is what we were looking for

**Comment by aneeshd16** [comment]
Closed via #179
