### ISSUE TITLE
horizontal layout of twitterwall does not use full width of screen

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#156]
currently the default wall view does not use the full screen. Please consider that people will view this in full screen only and therefore the wall must use all space it gets.

Example:
![wall1](https://cloud.githubusercontent.com/assets/238730/8101317/20317c66-1016-11e5-91ac-c1bea85458f9.png)
If you use the full width, some more vertical space is available because more text fits into one line. Then, show the images centered below. Example:
![wall0](https://cloud.githubusercontent.com/assets/238730/8101311/0fc7ac4c-1016-11e5-97c0-fafa6b73bf19.png)

**Comment by aneeshd16** [comment]
That space has been left blank so that statistics (top twitterers, top hashtags etc, histogram) can be displayed there. I'll open a issue for that.
Users should have the option to disable statistics. In that case, the entire width will be utilized.
Thanks for pointing this out!

**Comment by Orbiter** [comment]
ok good point with statistics. Thats true, if the statistics are wanted, the space must be left out.
Please add an option for this in the wall settings.

**Comment by aneeshd16** [comment]
Related #73

**Comment by Orbiter** [comment]
this is related to https://github.com/loklak/loklak_webclient/issues/37 -- if the user wants to show the statistics, show it in the empty space. If the user does not want it, extend the tweet to fill up the space.

**Comment by aneeshd16** [comment]
:+1:

**Comment by mariobehling** [comment]
Details in statistics view.
