### ISSUE TITLE
Deploy latest version of main branch

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#158]
Please update test.loklak.net to the latest version of web app. After deployment make a screenshot of a logged in user and assign task to person for next day.

- [x] 11 June	Prashant
- [x] 12 June	Phuc
- [x] 13 June	Sudheesh
- [x] 14 June	Aneesh
- [x] 15 June	Prashant
- [x] 16 June	Phuc
- [x] 17 June	Sudheesh
- [x] 18 June	Aneesh
- [x] 19 June	Prashant
- [x] 20 June	Phuc
- [x] 21 June	Sudheesh
- [x] 22 June	Aneesh
- [x] 23 June	Prashant
- [x] 24 June	Phuc
- [ ] 25 June	Sudheesh
- [ ] 26 June	Aneesh
- [ ] 27 June	Prashant
- [x] 28 June	Phuc
- [x] 29 June	Sudheesh
- [x] 30 June	Aneesh
- [x] 1 July	Prashant
- [x] 2 July	Phuc
- [x] 3 July	Sudheesh
- [x] 4 July	Aneesh
- [x] 5 July	Prashant
- [x] 6 July	Phuc
- [x] 7 July	Sudheesh
- [x] 8 July	Aneesh
- [ ] 9 July	Prashant
- [x] 10 July	Phuc
- [ ] 11 July	Sudheesh
- [ ] 12 July	Aneesh
- [x] 13 July	Prashant
- [x] 14 July	Phuc
- [x] 15 July	Sudheesh
- [x] 16 July	Aneesh
- [ ] 17 July	Prashant
- [x] 18 July	Phuc
- [x] 19 July	Sudheesh
- [x] 20 July	Aneesh
- [x] 21 July	Prashant
- [x] 22 July	Phuc
- [x] 23 July	Sudheesh
- [ ] 24 July	Aneesh
- [x] 25 July	Prashant
- [x] 26 July	Phuc
- [x] 27 July	Sudheesh
- [ ] 28 July	Aneesh
- [x] 29 July	Prashant
- [x] 30 July	Phuc
- [x] 31 July	Sudheesh
- [x] 1 August	Aneesh
- [x] 2 August Prashant
- [x] 3 August Phuc
- [x] 4 August Sudheesh
- [x] 5 August Aneesh
- [x] 6 August Prashant
- [x] 7 August Phuc
- [x] 8 August Sudheesh
- [ ] 9 August Aneesh
- [ ] 10 August	Prashant
- [x] 11 August	Phuc
- [x] 12 August	Sudheesh
- [x] 13 August	Aneesh
- [x] 14 August	Prashant
- [x] 15 August	Phuc
- [ ] 16 August	Sudheesh
- [ ] 17 August	Aneesh
- [ ] 18 August	Prashant
- [x] 19 August	Phuc
- [x] 20 August	Sudheesh
- [ ] 21 August	Aneesh
- [ ] 22 August Prashant
- [x] 23 August Phuc
- [x] 24 August Sudheesh
- [ ] 25 August Aneesh
- [ ] 26 August	Prashant
- [x] 27 August	Phuc
- [x] 28 August	Sudheesh
- [ ] 29 August	Aneesh
- [ ] 30 August	Prashant
- [ ] Week 36	(Sunday, 6 Sep)
- [ ] Week 37	(Sunday, 13 Sep)
- [ ] Week 38	(Sunday, 27 Sep)
- [ ] Week 39	(Sunday, 4 Okt)
- [ ] Week 40	(Sunday)
- [ ] Week 41	(Sunday)
- [ ] Week 42	(Sunday)
- [ ] Week 43	(Sunday)
- [ ] Week 44	(Sunday)
- [ ] Week 45	(Sunday)
- [ ] Week 46	(Sunday)
- [ ] Week 47	(Sunday)
- [ ] Week 48	(Sunday)
- [ ] Week 49	(Sunday)
- [ ] Week 50	(Sunday)
- [ ] Week 51	(Sunday)
- [ ] Week 52	(Sunday)
- [ ] Week 53	(Sunday)

tbc.

**Comment by prasht63** [comment]
+1

**Comment by sudheesh001** [comment]
:+1:

**Comment by aneeshd16** [comment]
+1

**Comment by fuksi** [comment]
+1

**Comment by prasht63** [comment]
@fuksi you are up for today :+1:

**Comment by sudheesh001** [comment]
@mariobehling Integrated these dates into the google loklak calendar so that there's no chance that someone might miss it.

**Comment by mariobehling** [comment]
@fuksi and all, please leave a comment after you deployed the latest version every day. So we know when to test. Cheers!

**Comment by fuksi** [comment]
2 successful deployment. One at midday at commits c4922153aa659d59f2477af8f23efdfc00eb062d, at just now at 01bd909d99353862d1fd003015f466cc26255263  
It helps a lot if the responsible member of that day is informed about straight commits to master. Cheers!

**Comment by sudheesh001** [comment]
Deployed at 4160756776aee794bf5b49251c2eb187b1cf7022
Screens running
- 27424.production
- 27331.iframely

**Comment by aneeshd16** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/6f45107b460e506d3d8a884dfd48144db94ca05a
Screens running

27424.production
27331.iframely

**Comment by sudheesh001** [comment]
Deployed at 19a1885d39fcc38bed6f49ff659ab80a9fe3e60b

New design deployments at
http://loklak.cloudapp.net:3001/

**Comment by mariobehling** [comment]
@sudheesh001 This issue is regarding the deployment on test.loklak.net. The cloudapp installation is still not working here.

**Comment by sudheesh001** [comment]
To keep this stable, only reviewed patches from the `master` branch will move to test.loklak.net Once the twitter branch merges to master, the changes will happen accordingly.

**Comment by aneeshd16** [comment]
Deployed using the new method. Instructions are in readme.setup. Posting them here for convenience:
1. The iframely and oauth-proxy processes should be running forever with pm2. Check if they are running or not by "pm2 list". If they are running or do not need to be updated, skip to step 5.
2. If those processes need to be updated, you need to stop them first by "pm2 stop <pm2-id>". You can get the pm2-id by doing "pm2 list"
3. Start oauth-proxy by "pm2 start oauth-proxy/index.js"
4. Start  iframley by "cd iframely" and "pm2 start server.js". Do remember to go back to the root directory.
5. "git pull"
6. "gulp prod"

**Comment by mariobehling** [comment]
@prasht63 Did you deploy the latest version yesterday?

**Comment by prasht63** [comment]
@mariobehling  The last deployment by me was day before yesterday after introducing the wall-map with auto popup.After that no changes were made to master yesterday.So did not deploy.

**Comment by mariobehling** [comment]
@sudheesh001 Please assign the deployment to Aneesh at the end of today.

**Comment by mariobehling** [comment]
@prasht63 You should then assign to the next person in line. Please keep the deployments going and assign at the end of the day to the next person.

**Comment by sudheesh001** [comment]
Moving to @aneeshd16 Todays' deployment done at 04c054754c2164318ae13100c912690321c4575b

**Comment by mariobehling** [comment]
@sudheesh001 What does it mean?
> Moving to @aneeshd16 Todays' deployment done at 04c054754c2164318ae13100c912690321c4575b

Please include all PRs of today!

**Comment by sudheesh001** [comment]
Update: Deployed at efc692fc726d6a81d9f3adaad690ef194e850366

**Comment by aneeshd16** [comment]
Deployed yesterday night.

**Comment by prasht63** [comment]
Updat Deployed at https://github.com/loklak/loklak_webclient/commit/64c87d4c5767bca0c82c92d8d8aaa2db49e4b107

**Comment by sudheesh001** [comment]
Deployed at 9601dc50c76f1cef6b16ce17c4d8c68bcb10a3d8

**Comment by aneeshd16** [comment]
Deployed at 8a6f34f951700b270a7009b7770676f3f8071a48

**Comment by prasht63** [comment]
depolyed at loklak/loklak_webclient@fbe530a
@fuksi you are up

**Comment by aneeshd16** [comment]
Just FYI, `sh deploy.sh` works unless an `npm install` is required. Can we automate this quickly without spending too much time on it?

**Comment by sudheesh001** [comment]
Deployed at d1795260852d67a81cf2825f6b5d8f534205629c

**Comment by aneeshd16** [comment]
Deploy 1 at 521e03bdd161461074bab04f17dbe550ff8a339c
To be updated.

**Comment by prasht63** [comment]
Deployed

**Comment by prasht63** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/fe296c950548c9533b55ed390eb0f28f59068a46

**Comment by fuksi** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/702cddbecaf6e5dfe2ee6370b06c2b8df9e059f1

**Comment by sudheesh001** [comment]
No changes since 702cddbecaf6e5dfe2ee6370b06c2b8df9e059f1 , Branch stable. Pending PRs reviewed and feedback given before merge and deployment https://github.com/loklak/loklak_webclient/pull/361

**Comment by aneeshd16** [comment]
Deployed at 702cddbecaf6e5dfe2ee6370b06c2b8df9e059f1

**Comment by sudheesh001** [comment]
Deployed at e914c3d8d0fea4e0414cdb55483fb268f54c47d5

**Comment by aneeshd16** [comment]
Deployed

**Comment by prasht63** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/e914c3d8d0fea4e0414cdb55483fb268f54c47d5

**Comment by fuksi** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/1f3f9d3bc0b68f399105fe107f3bb795e1786bb0

**Comment by sudheesh001** [comment]
Deployed at e050507f5d79f46117e527dc40e43e335517bbe7

**Comment by fuksi** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/18f88e0860c8536051a1e51ef5611b469ede64e9

**Comment by sudheesh001** [comment]
Deployed at 3d0555820d8c2fbc45f3b27ab6deb3fd5b920add

**Comment by prasht63** [comment]
Deployed at 3d05558

**Comment by fuksi** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/d5e64cc360b4c72e33c666d5b94c8eef14be4436

**Comment by sudheesh001** [comment]
No change in deployment status, no updates to deploy

**Comment by aneeshd16** [comment]
Deployed (no change)

**Comment by sudheesh001** [comment]
Deployed at 8f456cacbd6d1e79092f2801825ba608aaa7b08e

**Comment by aneeshd16** [comment]
Already up to date.

**Comment by prasht63** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/98442e54a1689ac5d53090d33ee11a266bc5cfb7

**Comment by fuksi** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/b0b71550363c42f64770c744770efc43371e2e06

**Comment by sudheesh001** [comment]
Deployment remains at b0b71550363c42f64770c744770efc43371e2e06

**Comment by fuksi** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/51cd9bf6bb7a00b8812d3aa06f2eb4fa85ca51f6

**Comment by sudheesh001** [comment]
Deployment 1 : 6e620383f8a0dbd9edc3bb68f1859e38c3d79b9d
Deployment 2 : 26009f87a4b8c04cbd5a0c6b5e29b032194dedd1

**Comment by aneeshd16** [comment]
Deployed at 3db7a7587f887f0d7458bea72c5ca18c6276c373

**Comment by prasht63** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/7b1b9a87054956df7862d2758efae03304fb4d9e

**Comment by fuksi** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/565849f4f5fbfc538757f15ae48a2a14cffb80dd

**Comment by sudheesh001** [comment]
Deployed at 62cc8b4b0302b99d4957df40b60b097ae94bec98

**Comment by fuksi** [comment]
Deployed at https://github.com/loklak/loklak_webclient/commit/14b4bf8aa3a92cb84054958f73989fbe4711055f

**Comment by sudheesh001** [comment]
Deployed at 1c72a4bccdfbe60b24c26a879b76495d362aa519

**Comment by aneeshd16** [comment]
@sudheesh001 Deployed version is ~20 commits behind. Can you please test if we are good for deployment?
