### ISSUE TITLE
link single view tweets with date on tweet

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#160]
The single-view of tweets https://github.com/loklak/loklak_webclient/issues/98 shall be linked on the date of the tweet. Thats exactly the same in twitter.

**Comment by fuksi** [comment]
![image](https://cloud.githubusercontent.com/assets/6878677/8108624/40bc3590-105a-11e5-8920-8eca68af9169.png)

On twitter. First you have to click around the area to show accurate time and date, then it is the word `Details` where clicking would open new tweet in the link. Done with 81425e641be9f5b131688a522bb19c20a2444052

**Comment by fuksi** [comment]
Also live at http://gofullstack.me:3001/

**Comment by Orbiter** [comment]
At this time, all tweets are not only completely broken, also the date cannot be clicked any more!

**Comment by fuksi** [comment]
Not all this time :) Just a merge conflict wasn't resolved, results in breaking the main.css: 
dbda5a00cf8029fb6ef0440cfbe177a2d0973d07
Already fixed.

**Comment by Orbiter** [comment]
This is not working. When I click on the tweet age, the tweet view changes (shows date below message) but that is not the expected behaviour. If the tweet age is clicked, the individual view of the tweet shall be shown directly.

**Comment by mariobehling** [comment]
@Orbiter I think twitter changed that and it looks to me we are mimicking the same as twitter currently.

**Comment by mariobehling** [comment]
It looks to me there is no way to directly open a twitter feed in a single click anymore. It is just possible to copy the URL from a share as a tweet or DM. Any ideas?

![screenshot from 2015-07-04 12 59 43](https://cloud.githubusercontent.com/assets/1583873/8507670/a9e652e0-224c-11e5-8933-05c158716793.png)

**Comment by fuksi** [comment]
Now can open single tweet by:
- The twitter way: Click on status area to show more detail, then click on `Details`
- Other way: click on three dots above, then click on optiops `Open this single tweet`

On coming features:
* [ ] Enable copy link on click

**Comment by mariobehling** [comment]
Screenshot would be good with those kind of issues. Where can we test this?

**Comment by fuksi** [comment]
The deployment was slow, I just deployed again today. You can test on any search.
![image](https://cloud.githubusercontent.com/assets/6878677/8746656/46486fdc-2c94-11e5-8b85-20d34a131cb6.png)

Clear instructions are also given in the merged PR: https://github.com/loklak/loklak_webclient/pull/368
