### ISSUE TITLE
Top-Bar Design is broken when window is resized

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#161]
The effect is different in case how small you make the window. This is not related to 'responsiveness', it is just badly formatted:

case 1:
![break1](https://cloud.githubusercontent.com/assets/238730/8107221/141e13a8-1048-11e5-9d25-c9335dd48388.png)

case 2:
![break2](https://cloud.githubusercontent.com/assets/238730/8107227/197a2634-1048-11e5-8230-0fdd0c17b26d.png)

**Comment by Orbiter** [comment]
assigned to @prasht63 as your current worklist is much smaller

**Comment by prasht63** [comment]
Option 1:
![image](https://cloud.githubusercontent.com/assets/2105062/8136005/dc1cf890-1158-11e5-8317-121099fc8e73.png)
![image](https://cloud.githubusercontent.com/assets/2105062/8136019/eeefdd3e-1158-11e5-91a5-4396d39a6e38.png)

Option 2 :
![image](https://cloud.githubusercontent.com/assets/2105062/8135956/8433fdea-1158-11e5-8bd8-7276b7810290.png)
![image](https://cloud.githubusercontent.com/assets/2105062/8135971/9ef482ee-1158-11e5-94bb-aecaf2eb8612.png)

**Comment by sudheesh001** [comment]
I am currently changing this to fit with the design changes that are mentioned in #112 .

**Comment by prasht63** [comment]
@sudheesh001  changing what?

**Comment by sudheesh001** [comment]
The top nav bar has been changed in the latest commit, please proceed on the responsiveness accordingly.

**Comment by mariobehling** [comment]
![twitter-topbar](https://cloud.githubusercontent.com/assets/1583873/8143814/9303cfc8-11bf-11e5-83d6-68cbe5341293.png)
Please take some time to take attention to details. Our top bar starts to be clotted for no reason. Compare with twitter, please and change it accordingly.

**Comment by mariobehling** [comment]
Also check how you can take care of the logout, please:

![logout-button](https://cloud.githubusercontent.com/assets/1583873/8143818/eb8e3bba-11bf-11e5-8fd3-57744f9450b0.png)
