### ISSUE TITLE
Add tweet box after clicking on top right tweet button

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#166]
Just compare with twitter and also add icons for additional attachments e.g. maps.
![tweet-now](https://cloud.githubusercontent.com/assets/1583873/8127496/a40191ac-10f7-11e5-9d96-ea288adee9a2.png)

**Comment by sudheesh001** [comment]
https://github.com/loklak/loklak_webclient/issues/118 Describes the technical process
Partially implemented in https://github.com/loklak/loklak_webclient/issues/143 with changes to top nav bar and the tweet button's availability to user in any page when logged in.

I see that this also has the Add photo and Add location as we wanted, @prasht63 can you take on that once the code so far is merged, that'd avoid spinning the wheel all over again

Partially depends on https://github.com/loklak/loklak_webclient/issues/165 https://github.com/loklak/loklak_webclient/issues/119

**Comment by sudheesh001** [comment]
@prasht63 #179 has the required views, if you could review that and if that goes well, then you can continue with the `Add photo` and `Add location` buttons as assigned.

**Comment by sudheesh001** [comment]
@prasht63 Please continue with the changes needed in the tweet box. #179 has been merged.

**Comment by mariobehling** [comment]
@prasht63 This was assigned 7 days ago. What is the progress?

**Comment by prasht63** [comment]
Reassigning to @sudheesh001 since he is handling design issues.

**Comment by prasht63** [comment]
It has already been implemented with https://github.com/loklak/loklak_webclient/pull/179. Closing

**Comment by prasht63** [comment]
@sudheesh001 Add Add Photo and Add Location features to lightbox. Reopening

**Comment by mariobehling** [comment]
Please compare this design first with twitter and check the differences. There is still a lot to do. Please only close issues after you confirmed, that they are 100% finished.

![tweetbox](https://cloud.githubusercontent.com/assets/1583873/8341409/f9064a18-1ac4-11e5-86a0-1caae75f4442.png)
