### ISSUE TITLE
Read user profile images from json

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#168]
This is a question in relation of the issue https://github.com/loklak/loklak_webclient/issues/59 (to be reopened):
- when the loklak_server was able to provide an user image, it will also store the image in a cache for further usage
- that cache will be the user information within the user account
- the image would be a base64-encoded string
- when the front-end receives search entries, it will also contain such base64-encoded images.

The question is: can the front-end read and decode such images and display them without doing any more requests to twitter or the backend?

**Comment by mariobehling** [comment]
This issue is also related to https://github.com/loklak/loklak_webclient/issues/165

**Comment by Orbiter** [comment]
Yes it is related to https://github.com/loklak/loklak_webclient/issues/165 !!

The backend-service has been implemented now in https://github.com/loklak/loklak_webclient/issues/59 but with this issue it would not even be necessary to access the backen-proxy or twitter itself, because the image could be embeded into the user data. If this is possible with the proposed base64 encoding, it will be done!

**Comment by aneeshd16** [comment]
Base64 would work, no problems. This can be easily done.

**Comment by Orbiter** [comment]
Ok, thank you @aneeshd16 !!
Then I have one further question, which is connected: if the loklak_webclient has successfully read an user image (without usage of the proxy), can the loklak_webclient submit this to loklak_server for storage in a base64 encoded string with a POST request?

**Comment by Orbiter** [comment]
if this is possible, the new process described in https://github.com/loklak/loklak_webclient/issues/59#issuecomment-111522188 will slightly be changed.

**Comment by aneeshd16** [comment]
@Orbiter, it is certainly possible but i wouldn't go with it. A search gave me the following way to convert an image to base64:
* create a html canvas element
* draw the image on the canvas
* get the base64 string from the canvas.

So if there are 100 results in a search, this process will have to be repeated 100 times, not to mention making 100 requests to the server.
Sure, it can be done, but I am not sure it how it would affect the performance.
@fuksi @sudheesh001

**Comment by Orbiter** [comment]
hm, ok it's strange that the other way around (base64->image easy, image->base64 complex) is so different. However, there is also a security issue about user images if we would do that. Therefore forget about the latest idea, but we still then draw images from base64 of the backend.
Further steps are described in https://github.com/loklak/loklak_webclient/issues/59#issuecomment-111522188 ..thank you!

**Comment by aneeshd16** [comment]
:+1:
