### ISSUE TITLE
Merge Wall and Map and offer map as an option in the final choice of design.

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#169]

**Comment by mariobehling** [comment]
I have discussed this again with Michael as well. The Item in the navigation bar should stay with the name "Wall", but in the final design tab of the wall, we could change the name to "design & views" or just "views". @aneeshd16 Or do you have better suggestions?

**Comment by aneeshd16** [comment]
The third tab page contains these options:
* Choice of layouts
* Choice of header colour
* Choice of header position

"Design & views" sounds good, but maybe the text is too big? It would look like this:
![image](https://cloud.githubusercontent.com/assets/5436027/8267272/205d1ed0-1777-11e5-92b6-a9904cda4322.png)

How about "Preview"?
![image](https://cloud.githubusercontent.com/assets/5436027/8267277/8ad1173a-1777-11e5-9462-3d6fd75efd3b.png)

**Comment by mariobehling** [comment]
Yeah! Preview is probably much better. Thank you!

**Comment by mariobehling** [comment]
For the output view of the tweets on the map, something like the following would be nice, where we can actually see a photo and the tweets of people: https://www.campaignmonitor.com/worldview/demo/

**Comment by mariobehling** [comment]
Collecting links, that might be relevant (even if they are for Google Maps)
http://www.sitepoint.com/embellishing-your-google-map-with-css3-and-jquery/

**Comment by mariobehling** [comment]
Note: This issue is taking with anything that deals with markers, popups animations and whatever the user sees on the map.

**Comment by mariobehling** [comment]
Here is a link to a worldmap from a send out of FOSSASIA. There are a number of JS that might be relevant for us. Please compare: https://fossasia.createsend.com/reports/wv/t/F48F8442ED58EDD3
