### ISSUE TITLE
Add map as display option for tweets

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#170]
Insert a map search here.

![search-options](https://cloud.githubusercontent.com/assets/1583873/8129233/615875f4-1107-11e5-84aa-40e2176c3e4e.png)

**Comment by fuksi** [comment]
@mariobehling, can you elaborate the map search features? Then I would understand the requirement, and compare it with the capability of loklak server, in order to design the feature. Of course I can elaborate on this myself, but I also want to know your opinion and expectation

For example:
- Is the result a list of statuses or a map? (I can't yet imagine how to implement a map here)
- Is the search criteria going be like this img below, or is it going to be like: `100 miles from here` 
![image](https://cloud.githubusercontent.com/assets/6878677/8170355/c3a6e0d4-13b8-11e5-90d9-db718d45fb72.png)

The picture was taken from advanced search on twitter.

**Comment by mariobehling** [comment]
We are considering different options for this feature. For the beginning just show a map here and show all tweets with location information on the map.

**Comment by mariobehling** [comment]
Regarding the search criteria. A location can be a search criteria, but it does not have to be. If I search e.g. for loklak, just show all tweets - wherever they were posted - on the map.

**Comment by fuksi** [comment]
@Orbiter, I see in the API there a way to request with the arg `near`, in what format should the parameter is? E.g. `near=Helsinki`?

In the result, I can't find a property that can be used to determine the coordinate of a status? Is the loklak server supporting any other properties soon?

**Comment by Orbiter** [comment]
It's really easy:
- display always a map (with or without any results), by default with world-view, filling the complete window width below the search result type selection tab
- add the ```/location``` constraint to the search request (like you add ```/image```for images)
- the search result will contain only items with ```location_point```attributes
- draw markers on the map where the ```location_point```attribute points to

**Comment by Orbiter** [comment]
- if the user changes the view on the map (i.e. zoom), add the ```bbox```constraint to the search query according to https://github.com/loklak/loklak_server/issues/47

**Comment by Orbiter** [comment]
To get test data, follow instructions in https://github.com/loklak/loklak_server/issues/45

**Comment by Orbiter** [comment]
MUCH MORE test data now in the search index because automatic detection is now implemented

**Comment by Orbiter** [comment]
@fuksi https://github.com/loklak/loklak_webclient/issues/170#issuecomment-112382684 the location is now in the field location_mark. There are two location fields: location_point (thats where the center of the position is) and location_mark (thats where the marker on the map shall be painted).
Both fields have  [longitude, latitude] assigned.

**Comment by fuksi** [comment]
Own note: Add new mark up from #202

**Comment by fuksi** [comment]
A map is available at the moment, but content is not as rich as other search filter.
http://test.loklak.net/search?q=%23loklak%2B%2Fmap&timezoneOffset=-180

This feature is on hold until other solution like #202 is provided from @prasht63 
If 2 days until the end milestone 2 no other solution is provided. I'll create a new one.

**Comment by Orbiter** [comment]
please add https://github.com/loklak/loklak_webclient/issues/211 (zoom into search region using an extension of `/location` constraint)
