### ISSUE TITLE
Send Twitter oauth_token and oauth_token_secret to loklak_server after authentication

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#171]
Utilize this: https://github.com/MrSwitch/node-oauth-shim#capture-access-tokens
in `oauth-proxy` to intercept the tokens and send it to loklak_sever.
Issue on loklak_server: https://github.com/loklak/loklak_server/issues/26

**Comment by aneeshd16** [comment]
Fixed in 55b22641d6bb11548f6ad7fc559f5c3bd315871d

**Comment by Orbiter** [comment]
I don't have any account data in the database of loklak_server, so this cannot be solved!

**Comment by aneeshd16** [comment]
@Orbiter , my locally running loklak_server has data. Is there any way to clear/delete the existing data so that i can test if new data is being added?

**Comment by Orbiter** [comment]
If there is any account data stored, that would show up in the file data/accounts/account*.txt - but currently that file is empty - on test.loklak.net

**Comment by Orbiter** [comment]
retested this with latest deploy on test.loklak.net - works! great!
