### ISSUE TITLE
use settings from the loklak_server

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#172]
settings in loklak_webclient shall be overwritten with those as delivered by the server using the feature https://github.com/loklak/loklak_server/issues/48

**Comment by aneeshd16** [comment]
Currently, `js/constants.js` reads constants from the local file `custom_configFile.json`. It needs to be modified to read the json from `<loklak_server_url>/api/settings.json`. Properties will be added/overwritten as appropriate.

**Comment by Orbiter** [comment]
The settings servlet is implemented. To test it, just call http://localhost:9000/api/settings.json

To write settings within the server, edit the file data/settings/customized_config.properties
and add settings in the following way:
- if you want a setting
```
"newproperty"="newvalue"
```
add the following line to ```customized_config.properties```:
```
client.newproperty=newvalue
```

**Comment by aneeshd16** [comment]
@Orbiter , will this file get committed every time?
for eg, we had,
* configFile.json : Default settings to act as an example (in repo)
* custom_configFile.json: Custom settings, (not in repo)

What is the equivalent in loklak_sever?

**Comment by sudheesh001** [comment]
@Orbiter I am not really sure if publishing the twitter consumer secret is a good idea, anyone can query that API on the server and get the twitter key and secret.

**Comment by mariobehling** [comment]
What is a better solution?

**Comment by sudheesh001** [comment]
I think its best to keep this dependency with the webclient as we are doing now, in a custom file or as environment variables which can be accessed by `process.env.` but I tested that before and then @aneeshd16 and I reverted it to a custom file.

These values are constants and depend on if someone is deploying all of them individually. Giving them a custom config file means that we are giving them full flexibility to use the client as a stand alone client rather than them going through the process of setting up the server and querying keys from there, also they can set up their own apps while keeping the app token information secret.

I don't really find any reason why we should move this over to an API rather than have it as a setting to allow more projects to be built out of ours. Its just my opinion.

**Comment by mariobehling** [comment]
Twitter is only one service we will support and we do not want to depend on twitter, if they shut us out at some point, like they have done with other services. Login with twitter is just the start, so users can login. After that we need our own system with user accounts. What do you suggest to achieve this?

**Comment by sudheesh001** [comment]
I think the safest way around this problem over a long term along with login with twitter would be to also have a regular signup feature so that the users can signup with their information as follows
```
Name:
Email:
password:
```
Additional information could be something like `integrations`
```
Would you like to integrate any of the following ?
- Twitter
- Facebook
etc..,
```

**Comment by mariobehling** [comment]
@sudheesh001 Can you check out the way it works for Pinterest, please? I mentioned this a few times already. I wonder, when you will check it out.

At Pinterest a user logs in first login with e.g. FB and then you get an email to confirm your account. What do we have to do to implement this. Can you please try this out at Pinterest once?

**Comment by Orbiter** [comment]
@sudheesh001 https://github.com/loklak/loklak_webclient/issues/172#issuecomment-111724203 yes the keys should not be available in the public. Therefore I made them accessible from localhost only. That means that these informations can only be read from the oauth_proxy and not from the client's browser. Is that an issue? That means that the settings are overwritten for the oauth_proxy only, which is ok.

**Comment by Orbiter** [comment]
@mariobehling if the loklak_server gets the user account details from the webclient, it can retrieve the other user details as well. But at this time we don't have this because loklak_webclient still does not access the /api/account.json servlet!

**Comment by sudheesh001** [comment]
Implemented with the merge after @prasht63 review.
@loklak/loklak_developers please make sure you make the change of the settings to the server so that there are no issues and the application doesn't break.

**Comment by Orbiter** [comment]
please read my comment at https://github.com/loklak/loklak_webclient/commit/92e614caa65a22e31440cdc9c6f49778c7c2fcb9#commitcomment-11745965 and reopen if this can be done. I think there was a misunderstanding.

**Comment by Orbiter** [comment]
Don't trash the `custom_configFile.json` when overloading them with settings from loklak_server. The data received from the `/api/settings.json` shall just overload the values that the servlet provides, not all settings. You can i.e. do this by writing to `custom_configFile_server.json` instead `custom_configFile.json` and also load this during start-up.

**Comment by Orbiter** [comment]
I changed the auth settings in loklak_server. Since then, the log-in with twitter does not work. I guess this feature is not working. Please check.

**Comment by Orbiter** [comment]
To check if this working, open a command shell on loklak.org and run:
```curl http://localhost:9000/api/settings.json```
Please DO NOT PASTE ANY TEST DATA HERE FROM THE SERVER; SINCE THIS IS A SECRET!

Then, debug your loklak_webclient application and check if these values are correctly used.

**Comment by Orbiter** [comment]
@fuksi solved the problem
> Ok now it's fixed. User can login again on test.loklak.net. About the solution: TL&DR version: if credentials are changed, OauthProxy must be restarted  This applies only for production. (In dev, oauth is always restarted when gulp dev is ran)
> Problem explanation:
> I want to recall the role of our OauthProxy service. Oauth 2 API can support auth with just consumerKey, however twitter Oauth version is 1, so it still need both. Our application is a front end application so we can't just expose both keys, hence the OauthProxy instance, or "Oauth Shim". It "shim" our keys by keep a running server process holding pairs of keys and other credentials. The web client then just requests the Oauth Shim with the public key, Oauth Shim will recognize the public key, pair up with the secret and other cred such as callbackUrl, and then forward the request to twitter Oauth.
> When we change the keys in production, because the OauthProxy is also taking fields from custom_configFile.json, if the OauthProxy process is not restarted, it won't recognize the new public because it's still holding the old pair. Hence the error: "Credentials were not recognised". It was the error informed by the OauthProxy service, not the Twitter API. I can't believe I missed that....
