### ISSUE TITLE
Implement a redirecting page during the auth flow

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#174]
Currently after logging in, we are not using any redirecting page. So after logging in, a page like this is shown:
![image](https://cloud.githubusercontent.com/assets/5436027/8143803/8af4a650-11dc-11e5-8d44-0918c331466c.png)

Need to implement a new redirect page.

**Comment by sudheesh001** [comment]
Fixed in 55b22641d6bb11548f6ad7fc559f5c3bd315871d
