### ISSUE TITLE
Regression - Modals and lightboxes broken after wall changes

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#178]
@aneeshd16 The changes made in 2da28c39fc35e416da030eee2bf5b5bdb3db1679

https://github.com/loklak/loklak_webclient/commit/2da28c39fc35e416da030eee2bf5b5bdb3db1679#diff-7ab7e672fb1c96b2cd0c3795ae50e1bdR1692

Have broken the default modals, so now the modals don't appear as they have to be
Ideally should appear like
![screen shot 2015-06-14 at 8 33 27 am](https://cloud.githubusercontent.com/assets/4545925/8146895/65f895a2-1270-11e5-8828-cc24bde7bbef.png)
but rather after those CSS changes to default functionality appear as
![screen shot 2015-06-14 at 8 33 53 am](https://cloud.githubusercontent.com/assets/4545925/8146897/75f7c928-1270-11e5-9843-17374c77aefc.png)

**Comment by sudheesh001** [comment]
@aneeshd16 merging #179 will break the wall, breaking the default CSS isn't really a good idea as it may affect a lot of things in the application. Maybe you could use the same classes but extend it with an extra `.wall` ? Would that be good ?

**Comment by prasht63** [comment]
So I am merging Pull #179 . @aneeshd16 @sudheesh001 please discuss about the wall. That issue can be solved as @sudheesh001 suggested.
