### ISSUE TITLE
get attributes in URL for search result page

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#18]
I would like to see the query attributes (including time zone offset) in the get- attribute values of the url. That means a search result page path should look like 
```
/search?q=untersuchungsausschuss&timezoneOffset=-120
```
The reaso for such a feature is, that it must be possible to bookmark a loklak-Address or send it around with other media (like email etc) With the current search page, this is not possible.

Please make the servlet name exactly as given above, it should be names 'search'.

related feature: https://github.com/loklak/loklak_webclient/issues/7 because the welcome page should have a different url path than the search result page.

**Comment by fuksi** [comment]
@Orbiter , I believe this was also solved in merge #48  for feature #8. You can test this with the master HEAD.
