### ISSUE TITLE
Clean up code; remove unnecessary libraries

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#180]
This is a general requirement during development with low priority if you are not finished (code which is not needed at that time may be needed later) but it is a needed with high priority for the final version that only such libraries are inside the app which are necesary.

This is therefore a milestone 4 feature for all parts of the application

**Comment by Orbiter** [comment]
As the 'ongoing' and 'with high priority' means: you cannot close this issue until the end of development as it applies for the final version.

**Comment by mariobehling** [comment]
Closing it now as this should be understood as a continuous task.
