### ISSUE TITLE
Implement locally debugging service.

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#183]
I've been using a service on my host to debug link. Now is time to implement it locally. Service is just a simple node app with express. More about it here: https://iframely.com/

Example use service: 
http://gofullstack.me:8061/oembed?url=https://www.youtube.com/watch?v=LuBOjdwqOtc

Service is currently used to debug link in `search` view, however, it is also expected to be used in other views including `home` & `wall`.

After implementation, document the service, and explain here how to use it with the related angular components.

**Comment by fuksi** [comment]
Iframely is an embeded API, just like the famous embed.ly, except it's open source and support just as many domains. Repo here: https://github.com/itteco/iframely

We have been using iframely for a while with a service running in my host and is hardcoded into our repo. [Example link](http://gofullstack.me:8061/oembed?url=https://www.youtube.com/watch?v=LuBOjdwqOtc). Now it is implemented on branch [dev-debug-service](https://github.com/loklak/loklak_webclient/tree/dev-debug-service). 

The version of iframely is customized in the new branch to separate iframely config and add it into our custom_configFile.json. Step to test the new service
- `git remote update; git checkout dev-debug-service`
- npm install in `./loklak_webclient` iframely
  - Should you have problem with npm install in thie repo on debian based, install `build-essential`
  - I can't solve the problem with node-gyp on Windows > 8.1 yet
- Use a new screen or a new ssh session to run iframely: `node server`. **Important**, currently [you have to be in the `iframely` folder to run the command](http://i.imgur.com/zWGh7Le.png) Otherwise it won't work. I'm working on this.
- Use a different or a ssh session to run gulp dev.

If it works, rich result (videos, article) should render properly, like this. 

http://46.101.145.49:3001/search?q=%23vine&timezoneOffset=-180

Cheers!

**Comment by aneeshd16** [comment]
Good find, it will be awesome to embed all kinds of things.
`I can't solve the problem with node-gyp on Windows > 8.1 yet`
If you have visual studio 2013, just add `--msvs_version=2013` at the end of your `npm install` command.
` you have to be in the iframely folder to run the command`
try `node iframely/server`

Overall it looks good!

**Comment by sudheesh001** [comment]
Looks good. :+1:

**Comment by fuksi** [comment]
@aneeshd16, thank you for the msvs fix. It works! Will add it to docs soon.

**Comment by fuksi** [comment]
About why running inside iframely folder. If we run server.js outside the folder. None of the plugin would be included. And of course the server will run, but the result won't be what we wanted

![image](https://cloud.githubusercontent.com/assets/6878677/8204699/20bf55ae-14f3-11e5-842a-d05c902bf11e.png)

The log should be like this for the service to work properly.

![image](https://cloud.githubusercontent.com/assets/6878677/8204747/75701de0-14f3-11e5-8aa0-6bf02c0bc53c.png)

**Comment by fuksi** [comment]
Done with the merge above
