### ISSUE TITLE
Live Tweet Text Validation (character count)

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#189]
When the user enters a new tweet, every key-down must cause that a javascript function is triggered to evaluate if the tweet is valid. A tweet must comply with twitters character counting rules as defined in https://dev.twitter.com/overview/api/counting-characters

According to https://dev.twitter.com/overview/t.co every link is 20 characters long.

The validation process must:
- identify all links within a text
- count all characters in a text without link texts
- compute the characters without links plus number of links times 20

After the computation of user characters, the input modal displays in green font the remaining number of available characters or in red colour the number of characters that exceed 140 - with preceded minus sign.

**Comment by aneeshd16** [comment]
This is a nice package that could help us for this:
https://www.npmjs.com/package/twitter-text
