### ISSUE TITLE
links in tweets of search results cannot be clicked

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#194]
links in tweets must be detected and rendered as clickable links in tweets. The link colour must be identical to the links for hashtags and the link text must be underlined.
When a link is clicked, the corresponding page shall open in a new tab (not replace the same page; i.e. with target="_blank")

**Comment by sudheesh001** [comment]
I think this can be safely closed. Finished with the latest pull request #208

**Comment by Orbiter** [comment]
the link is correclty coloured and clickable, however clicking on the link replaces the current view and does not open a new window tab as requested. Please add a `target="_blank"` to the link which will create the required functionality.

**Comment by sudheesh001** [comment]
@Orbiter This is not reproducible, all the links in the search open up in a new tab. https://github.com/loklak/loklak_webclient/blob/master/app/js/filters/tweetTextLink.js#L21

**Comment by Orbiter** [comment]
is this deployed?

**Comment by sudheesh001** [comment]
Yes, just tested on Loklak Test

**Comment by Orbiter** [comment]
it's working!
