### ISSUE TITLE
Compare and Research the Twitter js and css stack with the loklak stack

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#199]
Look at a normal page of twitter and have a look at the frontend stack. They are using:
analytics.js
boot.js
init.js
profile.js
timeline.js
twitter_core.css
twitter_more1.css
twitter_more2.css

What are the pros and cons of using some of them for loklak?

**Comment by aneeshd16** [comment]
analytics.js is google analytics. All the other js files are minified and cannot be used by us.

We cannot directly use those css files as they are too huge to inspect manually. However, we can see which UI elements on twitter use which classes, and then use those specific classes in our app.

**Comment by sudheesh001** [comment]
There'd be a small problem with the JS files because of two reasons
1. Its minified
2. It'll definitely have more twitter related stuff in it which we need to see and remove.

I am sure we can easily go with the CSS files, that's the on going work in #181

**Comment by mariobehling** [comment]
Ok, just take the parts that are needed, but try to stay with the same naming conventions and let us know, if you make other decisions. And: I am not saying we should copy the complete code. That would not make sense, but we can follow tech decisions e.g. should we use init.js or timeline.js for anything? We have some similar features to twitter and if twitter uses some technologies it means they will be supported continuously. So, it is well worth following this!

@aneeshd16 I saw you were thinking about angularchart.js Please compare with twitter analytics, what they are using there. Cheers!

**Comment by mariobehling** [comment]
@sudheesh001 I see 14 css files when i look at the wall creation page. Can you also look into cosolidating things? e.g. unite wall styles in loklak_wall.css or something?
![loklakcss](https://cloud.githubusercontent.com/assets/1583873/8257218/5068fcdc-16ac-11e5-8d9f-a938ed26ecfd.png)
