### ISSUE TITLE
ERR! thrown in npm install, protocol errors and png-crush binary

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#2]
I am working behind a corporate firewall that blocks SSH and GIT:// protocol, but I can work with https:// 
As I was setting up this project I've noticed the following errors,
https://github.com/loklak/loklak_webclient/blob/master/package.json#L48&L54
```sh
npm ERR! git clone git://github.com/douglasduteil/isparta Cloning into bare repository '/Users/sudheeshsinganamalla/.npm/_git-remotes/git-github-com-douglasduteil-isparta-60a3da0a'...
npm ERR! git clone git://github.com/douglasduteil/isparta fatal: Unable to look up github.com (port 9418) (nodename nor servname provided, or not known)
npm ERR! git clone git://github.com/douglasduteil/karma-coverage Cloning into bare repository '/Users/sudheeshsinganamalla/.npm/_git-remotes/git-github-com-douglasduteil-karma-coverage-abcb3516'...
npm ERR! git clone git://github.com/douglasduteil/karma-coverage fatal: Unable to look up github.com (port 9418) (nodename nor servname provided, or not known)
npm ERR! Error: Command failed: Cloning into bare repository '/Users/sudheeshsinganamalla/.npm/_git-remotes/git-github-com-douglasduteil-isparta-60a3da0a'...
npm ERR! fatal: Unable to look up github.com (port 9418) (nodename nor servname provided, or not known)
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/sudheeshsinganamalla/Documents/loklak/loklak_webclient
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code 128
```
Many universities with a proxy system block the SSH protocol for safety, the best would be to go with `git+https://`. The above errors can be removed by simply moving to this. Moving to this fixed most of the problems but at the same time, it still results in an ERR for
```sh
npm ERR! pngcrush-bin@0.1.18 postinstall: `node lib/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the pngcrush-bin@0.1.18 postinstall script.
npm ERR! This is most likely a problem with the pngcrush-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pngcrush-bin
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/sudheeshsinganamalla/Documents/loklak_GSoC/loklak_webclient
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
```

Leaving this aside, running `gulp dev` results in server running at 3001 and looks as follows
![screen shot 2015-04-30 at 5 59 06 pm](https://cloud.githubusercontent.com/assets/4545925/7412651/903e2358-ef62-11e4-8eb5-ad52982b65e7.png)

Has this setup correctly or is there something that's missing ?

**Comment by aneeshd16** [comment]
Change the apiUrl in app/js/constants.js from "localhost:9001" to "loklak.org" and hopefully you should be able to run a search without having the server to run locally.

**Comment by sudheesh001** [comment]
@aneeshd16 I already have the local instance of the `loklak_server` running locally, looks like this is someother problem, I just sent a small fix at #3 which slightly relates to a part of the problem I experienced.

**Comment by sudheesh001** [comment]
Tested the setup which runs clean on
1. Ubuntu 
2. Fedora

Only breaks on Mac OS X with the following error
```
npm ERR! notarget No compatible version found: nomnom@'douglasduteil/nomnom#next'
npm ERR! notarget Valid install targets:
```

**Comment by fuksi** [comment]
I was able to reproduce the error on a fresh OSX and this is how I fixed it:

- [Just in case] I updated NPM just in case brew 
```bash
brew update; brew upgrade npm
```
- Main fix, System Darwin error would relate to the CLI environment of OSX, the could mean ```node-gyp``` failed to rebuild the CLI. Xcode CLI might not be enough, so I chose the lesser chosen option: install Xcode.

Then it just work.

**Comment by Orbiter** [comment]
as this is Mac OS only related: I am working on Mac OS too, but I never had a problem. Maybe because Xcode was already installed previously.

**Comment by sudheesh001** [comment]
Thanks, `brew update` seems to have fixed the problem, upgrade `npm` threw an error `Error: No such file or directory - /usr/local/Cellar/node` I then realized that I had this placed somewhere else, linked them up and everything works perfectly.

Closing this issue. Thank you @fuksi and @Orbiter
