### ISSUE TITLE
Implement Data Handling for Plotting Tweets on the map

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#207]
Other areas dealing with markers, popups animations anything you see on the map, is in this issue: https://github.com/loklak/loklak_webclient/issues/169

**Comment by mariobehling** [comment]
@aneeshd16 Please close this issue, if it is finished.

**Comment by aneeshd16** [comment]
Solved by https://github.com/loklak/loklak_webclient/pull/214
