### ISSUE TITLE
Search view and responsiveness

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#210]
Some of the subview in search view is not working properly in smaller screensize. Make major layout style changes before end of milestone2. Focus on **usability**, not trivial stuffs.   
Update here changes here as they come, as future peer review can be handy.

**Comment by mariobehling** [comment]
@fuksi What is the update here? What is the specific issue? Screenshots are always good to understand what is going on. Some of the subview? Which ones?

**Comment by mariobehling** [comment]
![screenshot from 2015-06-30 14 14 28](https://cloud.githubusercontent.com/assets/1583873/8430491/737aba1a-1f32-11e5-8ec0-19afae57c674.png)
* [ ] Please also try to keep all search filters in one row
