### ISSUE TITLE
send current map display range as search attribute to loklak_server

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#211]
if the user can see a map from https://github.com/loklak/loklak_webclient/issues/170 then the user probably wants to zoom into the map. Each time the user zooms into the map or changes the view, then another search must be send to loklak_server with the latest boundaries of the visible map area.

The feature https://github.com/loklak/loklak_server/issues/47 now supports this. Instead of sending only a `/location` constraint as addition to the search query, also the boundaries must be submitted using the following schema: `/location=lon-west,lat-south,lon-east,lat-north`

**Comment by mariobehling** [comment]
In howfar is this related to #207 ? Are you using the same method?

**Comment by fuksi** [comment]
This is not related to #207. 
The init map search will load 300 results, but in most case, there are more. It is of course possible to load, said 1000 results in the beginning, but I witness how long it took the render the results, so more than 300 can create some bad UX, hence comes this issue/approach: zoom to load more.

Short version for the PR above:
   - Listen to `zoom` event
   - Get new geo boundaries
   - Get new data with new boundaries
   - Add new points to map

**Comment by Orbiter** [comment]
The webclient send integer values to the back-end, which makes result bad and invisible once the zoom level is high. The bug is obviously caused by `parseInt`, see https://github.com/loklak/loklak_webclient/commit/131d25cd955f99fb620f89639385c9b513e08c82 at line 330-333. These values must be double.

**Comment by Orbiter** [comment]
Has been fixed!
