### ISSUE TITLE
Integrate sensor data from weather stations, wind temperature and other sensors on the loklak map

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#212]
A starting point to do this could be Pocket Science Lab. Right now pocket science lab is able to generate data (Temperature, Relative Humidity and wind speed) and fetch it periodically and save it as .dat file.  The data is of the form | |x1,y1,z1|, |x2,y2,z2|, ....| where x , y and z are vectors, for example time,temperature and humidity. What are the steps to integrate this data into loklak?

**Comment by mariobehling** [comment]
@prasht63 Please talk with @wavicles about the integration. @wavicles can you actually implement GeoJson in Pocket Science?

**Comment by mariobehling** [comment]
@wavicles What is your update?

**Comment by wavicles** [comment]
Hello Mario
Please find the attached .dat file generated using weather station.
I did logging for past few hours and fetched data every 30 minutes.

   - First column is time in minutes
   - Second column is temperature in Degree Celsius (used LM35 sensor)
   - Third column is wind speed in km/h (using home-made anemometer)
   - Fourth column is relative humidity in %  (using DHT11 sensor)

I am now working on calibration for better accuracy.

Best Regards

Praveen

**Comment by mariobehling** [comment]
@wavicles This is an issue on github. I think you replied by email and attachments get stripped. Please upload the file somewhere and link it for us. Please sign in to github and verify your messages. Thanks!

**Comment by wavicles** [comment]
Hello Mario
The original file is here 
https://drive.google.com/file/d/0B61l01VLhQ1MVnRxbkN0bVBkcWc/view?usp=sharing

**Comment by wavicles** [comment]
I am working on the program to get both temperature and relative humidity from a single sensor DHT 11. The time will be taken directly from the system instead of elapsed time.

**Comment by prasht63** [comment]
@wavicles Can you describe the data a bit.I see this 
```
0.00  24.0  13.1  91  
30.00  24.0  13.6  92  
60.00  23.5  12.0  93
90.00  23.0  10.0  93
120.00  23.0  11.0  94
150.00  23.0  11.3  94
180.00  22.5  10.7  93
210.00  22.0  11.6  94
240.00  21.0  9.5  93
270.00  21.0  11.6  93
300.00  21.0  12.4  94
330.00  21.0  11.4  93
360.00  21.0  11.7  94

```
Can you add column names and a bit of description.Also it possible to live stream this data?

**Comment by wavicles** [comment]
Hi Prashant
>
> @wavicles Can you describe the data a bit.I see this
>
> 0.00  24.0  13.1  91
> 30.00  24.0  13.6  92
> 60.00  23.5  12.0  93
> 90.00  23.0  10.0  93
> 120.00  23.0  11.0  94
> 150.00  23.0  11.3  94
> 180.00  22.5  10.7  93
> 210.00  22.0  11.6  94
> 240.00  21.0  9.5  93
> 270.00  21.0  11.6  93
> 300.00  21.0  12.4  94
> 330.00  21.0  11.4  93
> 360.00  21.0  11.7  94
>

First column is Time elapsed in minutes.
Second column is temperature in degree Celsius.
Third column is wind speed in kmph.
Fourth column is relative humidity in %.

Regards
Praveen

**Comment by mariobehling** [comment]
We need to define a data structure for this in loklak server and then follow up here. Closing this for now therefore.
