### ISSUE TITLE
Integrate Marine Traffic in Loklak

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#215]
More information is here: http://www.marinetraffic.com/en/ais-api-services

**Comment by mariobehling** [comment]
How should we do this? Idea:
* Create an account "MarineTraffic"
* Add connect API to loklak
* Every ship gets an IoT-ID and tweets every time position or other data is updated.
* People can then follow ships (just like twitter accounts)

**Comment by prasht63** [comment]
Isn't this a paid service? http://www.marinetraffic.com/en/ais-api-services/detail/api-service:25

**Comment by mariobehling** [comment]
Yes, if we can implement this, we will learn and support a standard to show ships on the map. I do not find specific info about the API cost - http://www.marinetraffic.com/en/p/plans

We should also look out for more open data and see what are the strategies to keep the cost in balance. Also, it would be great, if we could see how we define a JSON format for ships, e.g. if people want to add their own small ships to the list.
