### ISSUE TITLE
debian installation problem

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#22]
on debian 7.8 I get:
```
gulp dev

Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/loklak/loklak_webclient/node_modules/gulp-util/node_modules/through2/through2.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
thats on the root server for loklak.net

**Comment by fuksi** [comment]
It's probably because of ```npm install``` process. Try this if you haven't and ```npm install```again. It solved my problem on ubuntu.
```
sudo apt-get install nodejs-legacy
```
(Source) [http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu]

**Comment by Orbiter** [comment]
```
apt-get install nodejs-legacy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'nodejs' instead of 'nodejs-legacy'
nodejs is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
was already installed!

**Comment by smokingwheels** [comment]
just try this to reinstall it.
apt-get remove nodejs
apt-get purge nodejs

Purge is identical to remove except that packages are removed and purged. Purge meaning that any configuration files are deleted too.

**Comment by sudheesh001** [comment]
@smokingwheels is right, purging and reinstalling should work or link the `which nodejs` path to `/usr/bin/node`

**Comment by Orbiter** [comment]
thank you all, the webclient is finally running on loklak.net (temporary, will move away the port 3001 later)
http://loklak.net:3001/statistics?q=rp15&since=2015-05-01_00:00&until=2015-05-07_23:00
