### ISSUE TITLE
Track Emojis on Twitter and show them on a map

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#220]
Let's get inspired by the Emoji tracker: https://github.com/mroth/emojitracker

Can we show emojis used on twitter on a map and generate statistics for regions to track the mood of people around the world?

**Comment by prasht63** [comment]
Awesome idea! Maybe we can add a heatmap layer to qualitatively show the mood across the world map.The big picture is going to be so cool!

**Comment by mariobehling** [comment]
I see you get the idea! Great.

**Comment by mariobehling** [comment]
This can be a separate app and a mini-project: https://github.com/fossasia/labs.fossasia.org/issues/136
