### ISSUE TITLE
Wikipedia - What data is relevant for loklak and maps?

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#221]
Wikipedia is an awesome Open Data resource. Which parts are relevant for loklak? What should we implement?

**Comment by prasht63** [comment]
@mariobehling I found out this API provided by wikipedia which allows you to see articles near a area.https://www.mediawiki.org/wiki/Extension:GeoData#API . Please have a look

**Comment by mariobehling** [comment]
Yes, nice. What other ideas do you have? How about birth/death dates of people and the location? What other interesting location data do we have? What is the most interesting?

**Comment by prasht63** [comment]
That is one interesting thing! We can have something like this,you click at
a location and you see a pop up of famous people who lived or died nearby
.People will want to click at random points on the world map to see which
famous personality is related to that.But for this I will have to look up
more in the API

**Comment by mariobehling** [comment]
Depends on server implementation. Closing it for now.
