### ISSUE TITLE
Fix Start page design and features

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#227]
As referenced in previous issues e.g. https://github.com/loklak/loklak_webclient/issues/92 and partly implemented before, please fix start page after login similar to twitter.
![loklak-home](https://cloud.githubusercontent.com/assets/1583873/8107965/b4e56f98-104d-11e5-8291-97fc4a547d52.png)

Currently I get this one
![startpage](https://cloud.githubusercontent.com/assets/1583873/8341779/84b1f3f8-1ac7-11e5-8f02-f678f458163f.png)

**Comment by mariobehling** [comment]
Also, there was a settings option with links and possibility to logout already. Now disappeard.

![settings-loklak](https://cloud.githubusercontent.com/assets/1583873/8341847/1c32d698-1ac8-11e5-9299-36969071398b.png)

Compare to:

![settings-twitter](https://cloud.githubusercontent.com/assets/1583873/8341850/22304e5e-1ac8-11e5-99c6-ae424db79546.png)

**Comment by mariobehling** [comment]
Moving to M2.5 and assigning to @fuksi

**Comment by mariobehling** [comment]
@fuksi Center following stream is missing at the moment. Please add it back.

**Comment by mariobehling** [comment]
On settings area "view profile" should direct to loklak user page not to twitter.

**Comment by fuksi** [comment]
Done straight on master. Now will direct to home view, which is the current loklak user page.

**Comment by mariobehling** [comment]
@fuksi Please check the different between home page and user page on twitter and implement it in the same way. The user page is not the same.

**Comment by mariobehling** [comment]
I am closing this issue as settings and profile pages a quite a big feature and can be discussed separately. https://github.com/loklak/loklak_webclient/issues/283
