### ISSUE TITLE
Add scroll to show feature to search result

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#234]
Please also comment here what plugin will be used.

**Comment by mariobehling** [comment]
What options do we have?

**Comment by fuksi** [comment]
Options that I have found. I'm likely to go with the first one.

- Vanilla javascript plugin: https://github.com/imakewebthings/waypoints
- jQuery plugin: http://www.infinite-scroll.com/
- Vanilla javascript

What making it slow is not getting the result from the server, but it is the process of loading rich contents (embed pictures from insta, imgur, video from youtube, twitter, facebook ..v..)
So the expected flow is 
- Get 100 or more results from the server and put it in the background.
- Show ~ 20 results from the beginning
- When (user) scrolled down to/close to bottom
  + If still have > 20 results left, append 20 new results
  + Else request more new results from server update the results buffer, and then append 20 new

I'm making this high priority since it'll have a clear effect on live.

**Comment by fuksi** [comment]
The first version of this is here: http://gofullstack.me:3001/search?q=%23london (just try to scroll down)
and there is an obstacle that I haven't been able to show yet.

The approach of all plugins above is to:
- Take a look of the last element, in this case, a status
- Get its offset top position
- Assign a listen to scroll/move down event
- If browser window top positio meets the offset top position mentioned below, trigger an event
- The event in this case is to load more status, and then assign a new listenter, like from the begining.

The problem is: the last status, or any status's size changes through time (as we are loading embeded tags). Then the offset position is not anymore accurate and effective. Sometimes it's in the middle of the page, sometimes it's out of the page height area.

@aneeshd16, @sudheesh001, @prasht63. Most of us I believe have done scroll to show before, however in most cases, the element's size are stable, this case it's a bit different. The only approach I tried is to create an interval, which watches all the statuses for change of height,  
and then assign a new listener. It's not stable and also not very performance-wise. I wonder if you guys have got this problem before. Any suggestion are welcome.

**Comment by mariobehling** [comment]
Scroll bar does not show up in Firefox browser current version. Though, I can go down with page down buttons.

![screenshot from 2015-07-06 10 31 57](https://cloud.githubusercontent.com/assets/1583873/8518440/5ba818e6-23ca-11e5-8d51-7a488db278b1.png)

**Comment by aneeshd16** [comment]
Maybe this would be useful?
http://binarymuse.github.io/ngInfiniteScroll/demo_basic.html

**Comment by zyzo** [comment]
I used this for a project http://manos.malihu.gr/jquery-custom-content-scroller/. 

It has a callback named `onTotalScroll` – triggers when content has scrolled all the way to bottom or right, which from my experience worked well.

The code : https://github.com/fossasia/timeline.api.fossasia.net/blob/master/timeline.js#L106

**Comment by mariobehling** [comment]
Syntax error in query generates wrong results in scroll down features.

![screenshot from 2015-07-09 00 31 04](https://cloud.githubusercontent.com/assets/1583873/8583941/ed72d19a-25d1-11e5-96d8-c059dc3c07c8.png)

**Comment by Orbiter** [comment]
Details to the syntax error:
- when the search result is scrolled, the loklak_webclient submits request like this:
```
http://loklak.org/api/search.json?callback=angular.callbacks._l&q={%22q%22:%22from:mariobehling%2Buntil:2014-10-20_15:27%22,%22timezoneOffset%22:-120}
```

- the right query would be
```
http://loklak.org/api/search.json?callback=angular.callbacks._l&q=from:mariobehling+until:2014-10-20_15:27&timezoneOffset=-120
```
