### ISSUE TITLE
Remove transition effect in all views

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#241]
List here where transitions have been removed.

**Comment by sudheesh001** [comment]
I've seen all the views that are there actually very few transitions,
1. The top nav bar has the transitions of the items on hover.
2. In the search view, the filter options have a transition on hover.
3. Sign in and Tweet buttons have transitions of the modal boxes / lightboxes.
4. Wall has a large modal box that's present with a transitions between the 3 sub windows.

I am not really sure what's expected here, do we have to remove all the transition delays on these and make them appear immediately on clicks ?

**Comment by mariobehling** [comment]
> I am not really sure what's expected here, do we have to remove all the transition delays on these and make them appear immediately on clicks ?

Make the transition time 0.

**Comment by mariobehling** [comment]
> Sign in and Tweet buttons have transitions of the modal boxes / lightboxes.

Tweet button still has a transition, that is too slow.
