### ISSUE TITLE
Allow favorite and retweet to work via the hello API

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#247]
http://adodson.com/hello.js/#helloapi

POST /me/like
POST /me/share

Parameters required, tweet "id"

Currently the tweets shown have an ID thats available with each one, we have the favorite and the retweet buttons available too, the above two APIs can implement the functionality of these buttons.

**Comment by mariobehling** [comment]
Just to ensure, I understand everything correctly: The tweets are saved with their complete dataset (e.g. including IP and Geolocation info) in loklak and crosstweeted to Twitter, correct?

**Comment by mariobehling** [comment]
Also the favs are served in the loklak DB or not?

**Comment by sudheesh001** [comment]
This is just the retweet / favorite action being performed on the existing tweets which are present from the server, the tweet ID information is being taken from the content served by the loklak server, the retweet action using this ID from the server is taken and then sent over to Twitter, After this the scraper does its job, All the content that's initially been present with the tweet is also there.

**Comment by mariobehling** [comment]
> After this the scraper does its job

@Orbiter Is this the preferred way?
