### ISSUE TITLE
Fix design of twitter wall

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#252]
There a lot of things that need improvements. Look for example the screenshots below
* [x] scroll bar shows up - it shouldn't!
* [x] number of tweets should adapt to size of available screen (compare tweetwall!)
* [x] number of tweet should not cover logo or face too much in the sidebar: The face is the important thing! People want to see who is number one
* [x] map view still have lots of issues
* [x] open wall in new tab
* [ ] a lot more. Please test!
* [x] instagram images do not render
* [x] test if images are rendered correctly in all 3 layouts.

![screenshot from 2015-06-30 14 57 18](https://cloud.githubusercontent.com/assets/1583873/8431235/62d15b14-1f38-11e5-9f42-d7770370ae75.png)
![screenshot from 2015-06-30 14 52 46](https://cloud.githubusercontent.com/assets/1583873/8431236/6318472c-1f38-11e5-9a96-72a440e4c0a4.png)
![screenshot from 2015-06-30 14 51 36](https://cloud.githubusercontent.com/assets/1583873/8431238/63448490-1f38-11e5-96c3-2dfe643de47f.png)
![screenshot from 2015-06-30 14 49 47](https://cloud.githubusercontent.com/assets/1583873/8431237/63375702-1f38-11e5-90a1-1ccba60bf0a8.png)

**Comment by aneeshd16** [comment]
These are known bugs, thanks for creating the issue. I am working on them.

**Comment by mariobehling** [comment]
Ok, good! Related to the display length of tweets is https://github.com/loklak/loklak_webclient/issues/253

**Comment by mariobehling** [comment]
Are you testing the wall on different layouts? Are you implementing a refreshment of new tweets? The oldest tweet should be substituted by the newest tweet. It looks like a lot of tweets are loaded but are not shown on the wall. You seem to solve this by deactivating the scroll bar. However tweets are still loaded, but why? See below for example.

![screenshot from 2015-07-08 17 43 48](https://cloud.githubusercontent.com/assets/1583873/8574884/4d07f4de-2599-11e5-8dd3-1f933cee09ae.png)

![screenshot from 2015-07-08 17 41 37](https://cloud.githubusercontent.com/assets/1583873/8574885/4d148ec4-2599-11e5-926d-884960bae46b.png)

**Comment by aneeshd16** [comment]
For the linear layout, 10 tweets are loaded at a time. This is to allow for various screen sizes. On a 1366x768 screen, about 3 tweets are shown. On a 1920x1080 screen, around 5 and a half tweets are shown. This is to give an effect that as your screen height increases, more tweets should be shown. This is exactly the same behavior as that of tweetwall. Only difference is that tweetwall loads 15 tweets, we load 10.
>Are you testing the wall on different layouts? Are you implementing a refreshment of new tweets? The oldest tweet should be substituted by the newest tweet.

Yes, I am. It takes approximately 20-30 seconds on average for a tweet to show up on the wall after the tweet is made.
* Linear layout: Newest tweet shown at top, tweets shown in descending order of creation time.
* Card: Newest tweet at top left
* Centre of attraction: Only the latest tweet is shown.

**Comment by mariobehling** [comment]
This task is ongoing. So, we continue that one in M3. Good job!

**Comment by aneeshd16** [comment]
Tasks mentioned originally have been completed.
