### ISSUE TITLE
Fix characters and shorten URL views

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#253]
![screenshot from 2015-06-30 15 02 32](https://cloud.githubusercontent.com/assets/1583873/8431354/299fdde2-1f39-11e5-9b6c-fcacee602f52.png)
* [x] fix wrong characters that still show up for old tweets (if possible)
* [x] take out "http" or "https" from links
* [x] autoconvert long links to show only the link beginning and "..."

**Comment by Orbiter** [comment]
The wrong characters cannot be fixed for old tweets :(
The issue with character parsing is fixed, but for already parsed tweets the fix is too late.

**Comment by mariobehling** [comment]
Just to be sure: This issue applies to all views including walls, home screen, search etc.

**Comment by aneeshd16** [comment]
Absolutely. I am modifying the `tweetTextLink` filter, which would automatically affect any view that's using the filter.

**Comment by aneeshd16** [comment]
Before:
![image](https://cloud.githubusercontent.com/assets/5436027/8499063/4347971a-21ac-11e5-867a-4a0bac4a5a57.png)
After:
![image](https://cloud.githubusercontent.com/assets/5436027/8499051/21e92336-21ac-11e5-807f-0eda09a2f05c.png)

The link length is kept to 22 characters, same as Twitter.

**Comment by mariobehling** [comment]
@Orbiter @sudheesh001 I don't understand why the "we've" is again rendered as "we9ve".

**Comment by sudheesh001** [comment]
@mariobehling I think @Orbiter  has made the patch to fix the appearance of 9 inplace of apostrophe to the server and it works but the only problem being that the tweet might have been scraped in the past when this patch wasn't there so its already late to correct them, we'll look forward to solutions where we can try replacing existing contents. Lets discuss that

**Comment by aneeshd16** [comment]
Closed via 216e8428825fb3b347d24d42cedfc6766fef6432
