### ISSUE TITLE
Show some visible output on favorite / retweet action being triggerred

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#257]
This is a follow up to #247 which successfully implements the functionalities but offer no visual feedback to the user, the main problem is that
- Even if the visual feedback of changing the star color etc.., is given, it'll disappear on refresh of the page
- The loklak server doesn't give the list of who liked it so its hard for the sessions of the logged in user to ensure that he has favorited or retweeted something.

How do we deal with this problem ?

**Comment by mariobehling** [comment]
As this is related to the server, please also discuss this with @Orbiter.

**Comment by mariobehling** [comment]
I am moving it to M3. Please also give some suggestions about your ideas and ping @Orbiter on chat.

**Comment by mariobehling** [comment]
@sudheesh001 There has not been input from you as requested. Is there a related issue on the loklak server repo? I am assigning this to you. This is actually part of your project and we would expect you to follow up.
