### ISSUE TITLE
Home list of tweets unordered in loklak

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#260]
The list of home tweets is usually ordered according to last tweets on top. The list on loklak is unordered.

![screenshot from 2015-07-01 21 53 27](https://cloud.githubusercontent.com/assets/1583873/8463574/c7886832-203b-11e5-9439-9b5fdd7bfa06.png)

**Comment by sudheesh001** [comment]
The sorting function was implemented here which was removed because it kept resulting into a timeout, this needs to be put in correctly so that we avoid the delays.
https://github.com/loklak/loklak_webclient/commit/26ef0f69fa91acd1e2f879fc678e4e27f8290bff#diff-4c242643d0a18b0152c046e9ed637055L46

**Comment by mariobehling** [comment]
@sudheesh001 If you take out basic functionality, please create an issue and assign to the responsible. We cannot just get rid of features that are implemented once. Thanks for solving the issue, but it is not completely solved until the functionality is there. Hence: Create an Issue in future!

**Comment by fuksi** [comment]
I'll solve this today.

**Comment by fuksi** [comment]
@sudheesh001, why is it resulting in a timeout?
I just looked back and the sort function is accurate and place at the right place to not interrupt anything.
Sorting ~ 30 statuses is very fast - 0.064s - You can't notice that.

Please compare the live version on PR #260 and http://test.loklak.net/

**Comment by mariobehling** [comment]
It is working now. Thank you!
