### ISSUE TITLE
Tweet location erroreous despite seemingly clear location information

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#261]
Checking the tweet map, I see that lots of locations are wrong e.g. Reuters reports "Washington...", but the tweet shows up in Africa. Or someone makes a tweet #cuba, but it shows up in Asia. 

@Orbiter What can be done to improve the tweet map locations?

![screenshot from 2015-07-02 09 41 17](https://cloud.githubusercontent.com/assets/1583873/8472119/c6c43b5c-209e-11e5-96e5-c9ef1b78cb2b.png)

**Comment by fuksi** [comment]
The example user was indeed a traveler:

**Comment by mariobehling** [comment]
As I understand the geolocation information to show tweets come from the hashtags currently. Or what is the relevant information to show a tweet in a certain location? How can we make this transparent?

**Comment by Orbiter** [comment]
The location can also come from the place name submitted by twitter. If such a place name is attached to the tweet, it is currently invisible. To make it visible, I already opened https://github.com/loklak/loklak_webclient/issues/287 - it should show the place name if a place name exist and was submitted by twitter.

**Comment by fuksi** [comment]
I put this on hold until progress on this mentioned issue.

**Comment by fuksi** [comment]
This was solve from #287, in https://github.com/loklak/loklak_webclient/commit/702cddbecaf6e5dfe2ee6370b06c2b8df9e059f1, with the rule
>when showing a tweet on a map:
- if (and only if) the field location_source contains the exact string REPORT then write below the tweet text:
- left-aligned a "place mark" (that thing like a upside-down drop)
- right to the mark the text from the field place_name

The result are can't be easily seen as geojson import is not yet available for the user https://github.com/loklak/loklak_webclient/issues/287#issuecomment-121206702

Please open this again, when IoT feature has substantial progress and there is issue need to be fixed.

**Comment by fuksi** [comment]
Done with this PR https://github.com/loklak/loklak_webclient/pull/409
Example:
![image](https://cloud.githubusercontent.com/assets/6878677/9222138/f94af7d6-40f7-11e5-8826-5f3e0a4c23b1.png)
