### ISSUE TITLE
Create a Trend Section in the Sidebar on Search

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#262]
The current section "trends" is a place holder. Implement a real trends are in the sidebar.

**Comment by mariobehling** [comment]
Please provide a screenshot for new features. Where can we test it? Where is it running on your web server?

**Comment by sudheesh001** [comment]
The trends should appear like this, I have deployed the changes to test.loklak but the trends list isn't appearing on it for some reason but when I investigate from the console the request is being made and the response is being returned. 

Keeping this open until furthur seen

<img width="1440" alt="screen shot 2015-07-20 at 9 38 53 am" src="https://cloud.githubusercontent.com/assets/4545925/8769866/5b51cd38-2ec4-11e5-9305-9d9a315bd383.png">

**Comment by sudheesh001** [comment]
Now present on test.loklak.net

**Comment by mariobehling** [comment]
Please add this trend section to the left sidebar at the search site as well, e.g. http://test.loklak.net/search?q=loklak here on the left.
