### ISSUE TITLE
Render Map page without scrollbars in most usual resolutions

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#266]
Similar to other map sites like Google maps or our own map search page, please render test.loklak.net without scrollbars.

![screenshot from 2015-07-02 21 06 14](https://cloud.githubusercontent.com/assets/1583873/8485496/4901e4d4-20fe-11e5-98f5-d41689dc54eb.png)

**Comment by mariobehling** [comment]
Scroll bar still there.

![screenshot from 2015-07-25 08 39 45](https://cloud.githubusercontent.com/assets/1583873/8888305/c18d621e-32a8-11e5-89cf-f9bb921d2ba9.png)

**Comment by prasht63** [comment]
I think the changes have not reflected on test.loklak.net. I will redeploy
