### ISSUE TITLE
show individual tweet when clicking on date on tweet-pop-up on map

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#267]
If you click on a marker on the map, you see the tweet for that location. At the bottom, there is the date of the tweet. Consistently, the date should be clickable and if clicked on the tweet the individual tweet view shall be shown. Currently there is no link behind the date. Just add a link behind the date and link to the individual tweet view inside loklak.

**Comment by fuksi** [comment]
Done in the PR above
