### ISSUE TITLE
don't show search constraints in the search box for map/accounts/video/photos

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#268]
when a search was done and one of the map/accounts/video/photos options are clicked, the corresponding constrained is shown in the search box as well. This is confusing and nothing the user should see. The information that the view is currently on map/accounts/video/photos must be kept somwhere else in the view status, but not in the search box.

While the constraint should not be visible in the search box, it stil must be part of the url so it is possible to bookmark or share the link to the corresponding view.

Therefore, when you remove the constraint string from the search box, don't remove it from the URL.

**Comment by mariobehling** [comment]
Not sure, if I understand that right, cause the idea is, that the user can also enter the search constraint him/herself and then it would show up. Also with additional constraints the user could create specific views like in advanced search. So, I am not clear why these constraint are confusing or are we thinking about different things?

**Comment by sudheesh001** [comment]
@mariobehling I think I understand it this way.
>While the constraint should not be visible in the search box, it stil must be part of the url so it is possible to bookmark or share the link to the corresponding view.

Remove the show of constraints in the blue search bar, so instead of showing `FOSSASIA+/photos` etc.., we'll apply the photo filter and change the URL but the content should remain `FOSSASIA` so that it doesn't look like there's a long complex string present in there.

**Comment by mariobehling** [comment]
Has been implemented before.
