### ISSUE TITLE
keep the current view if a new search is submittet. Applies to all map/accounts/video/photos

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#269]
Consider that a search was made and a different view than 'life' was selected. If a user then submits a new search term, then the current view of map/accounts/video/photos shall be selected, not 'live' by default.

This actually applies also to the current view selection of the map. If the user has zoomed into a specific part of the map and a new search term is submitted, then the next view with search results to the new search shall show the same part of the map as before.

**Comment by fuksi** [comment]
Done with #315
