### ISSUE TITLE
Show Thumbnails of Walls on Main Wall Page

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#274]
Walls should be shown as thumbnails on the main wall page.

**Comment by aneeshd16** [comment]
Closing this as this has been implemented.

**Comment by mariobehling** [comment]
Where is the thumbnail? Where can we test it?

**Comment by mariobehling** [comment]
Anyways, there is more important stuff. So, I am adding this issue to a later milestone.

**Comment by mariobehling** [comment]
The idea is that a thumbnail is like a screenshot of the actual wall. I think this feature is not a top priority. We can reopen it in the future, when other more important things are done.
