### ISSUE TITLE
use location_mark instead of location_point for marker locations on the map

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#278]
The `location_mark` is the position where the markers on a map shall be painted, not on `location_point`, which is the 'real' position. The marker is the location plus applied fuzziness to see several markers instead of one if there are severals in search results.

I see location_point at
https://github.com/loklak/loklak_webclient/blob/ebb233e3e57ee888d76c1648aa78097619563769/app/js/directives/mapLayout.js
https://github.com/loklak/loklak_webclient/blob/e299a3ea47a43f5cd81a5ec2d65f9071daedd53d/app/js/controllers/advanced-search.js
https://github.com/loklak/loklak_webclient/blob/21f679796d16bb71784e76e1a57317218a70e048/app/js/controllers/search.js

.. please change this to location_mark!

**Comment by mariobehling** [comment]
This is related to https://github.com/loklak/loklak_webclient/issues/232

**Comment by mariobehling** [comment]
@fuksi This is also related to the map search.

**Comment by prasht63** [comment]
Fixed with #279

**Comment by mariobehling** [comment]
Assiging this to fuksi. Please check in howfar this is relevant to the map search.

**Comment by prasht63** [comment]
@mariobehling I have changed it everywhere.At all places we are plotting maps as suggested by @Orbiter .So this is good to close.

**Comment by mariobehling** [comment]
Awesome!

**Comment by Orbiter** [comment]
I just tested this on the live map and it looks interesting! Did you try out the effect? However, it's working, great!
