### ISSUE TITLE
Sharing a link from Facebook puts %3A in the : in the time value

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_webclient#28]
A post from Facebook when url is copied 
http://loklak.net:3001/statistics?q=smokingwheels&since=2015-04-01_06%3A00&until=2015-05-12_13%3A00
Fails to return any results.

Linkedin has a shorten link and the client fails to have any results 
link https://lnkd.in/bBqyR3y 
Seems to be only working from the home page now after I tried the links.

Facebook seems to attach an ID to a link as well see pic
![just url id from fb](https://cloud.githubusercontent.com/assets/11748913/7465160/6333ca76-f2fe-11e4-919c-e81a3804f865.PNG)

**Comment by aneeshd16** [comment]
@smokingwheels to solve this issue, i am urlencoding all the parameters when generating the share link, and then decoding them again when the link is used.
Good find! I should've used urlencoding from the start.

**Comment by fuksi** [comment]
@smokingwheels, is this issue solved? Let's close it :+1:
