### ISSUE TITLE
clicking on the 'Map' option removes the blue headline showing the current search term

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#281]
if a search was done and the tweet list is visible, click on the 'Map' option. The blue headline disappears. This behaviour is different from the other search options, where the blue top-bar stays in place. Please keep the blue headline when clicking on the map option.

**Comment by mariobehling** [comment]
I would also like to discuss this. One one hand it is good to have the additional info on the blue line. On the other hand the line takes valuable space in the interface, e.g. if we add it to the map search page, the map on my 15 inch screen will be even smaller.

**Comment by sudheesh001** [comment]
I am giving my personal view here about this, I think when we deal with maps and things like that we need to give the user more space on the screen for enhancing the user experience and keeping the excitement of clicking on the screen, zooming and exploring different regions.

The blue bar would take up a lot of valuable screen size and the interaction space if its added to the map and I believe its best to not have it here on this page.
