### ISSUE TITLE
Show followers and following on different Layers on the map.

### ISSUE THREAD

**Issue by prasht63** [loklak/loklak_webclient#284]

**Comment by mariobehling** [comment]
@prasht63 As you are working on the UI as well: Please check if you can also implement that the scrollbars do not show up for the views as described here https://github.com/loklak/loklak_webclient/issues/266

**Comment by mariobehling** [comment]
Where can we test this?

**Comment by Orbiter** [comment]
This feature shall be supported by the loklak_server, the corresponding feature is https://github.com/loklak/loklak_server/issues/64

If https://github.com/loklak/loklak_server/issues/64 is implemented, the loklak_webclient must use the api provided by https://github.com/loklak/loklak_server/issues/64 to fetch followers and following and remove the currently implemented fetch method.

**Comment by Orbiter** [comment]
The retrieval of followers from the twitter client inside loklak_webclient should be replaced by a retrieval of those data from loklak_server. Therefore I re-open this issue: please retrieve the follower list from loklak_server, documentation is online at http://loklak.org/api.html#account .. please scroll down to "Retrieval of Twitter User Account Data" for details.

**Comment by prasht63** [comment]
closing this as already implemented on /map
