### ISSUE TITLE
selection of hashtag-link sometimes fails

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#286]
hashtags shall be marked as link. That moslty works, but in some cases not:

<img width="646" alt="hashtagfail" src="https://cloud.githubusercontent.com/assets/238730/8507736/dc594a5e-224f-11e5-96a6-304ecb38553f.png">

This may be a problem with umlaute, but strangely it works with the word "Köln" but not with "München".

**Comment by sudheesh001** [comment]
The hastag regex has 
```js
var hashtagReg = /#([\wäöå]+)/gi;
```
so the ü character is missing and has to be converted into 
```js
var hashtagReg = /#([\wäöåü]+)/gi;
```
But this would just solve it for this case, what are the other possible cases in which this could fail ?

**Comment by mariobehling** [comment]
Please try out all kinds of special local characters and other languages as well. @sudheesh001 Please do some tests as well.
