### ISSUE TITLE
Show place name in individual tweet pop-up in case that the place was submitted by twitter

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#287]
When investigating if the place mapping was done correctly, some tweets can be seen which obviously do not have a place name within their tweet text. Therefore it is not transparent why that tweet appears on that specific location on the map. Therefore place names submitted by twitter is an important context information which should be shown together with the tweet text.

In contrast to the visibility of the place if that was submitted by twitter, the place computed by the loklak_server shall not be shown because this information would already be in the tweet text. Please do:

- when showing a tweet on a map:
 - if (and only if) the field `location_source` contains the exact string `REPORT` then write below the tweet text: 
  - left-aligned a "place mark" (that thing like a upside-down drop)
  - right to the mark the text from the field `place_name`

**Comment by fuksi** [comment]
Please link/refer to #261 when this is done.

**Comment by mariobehling** [comment]
@prasht63 Yesterday, we read you are working on this issue, but there is no update here. Please keep us more in the loop. So we can give input if any.

**Comment by prasht63** [comment]
@mariobehling I will be working today, was finishing up #313 with adding a few designs.

**Comment by prasht63** [comment]
@Orbiter I have added the location to show along with the tweet.Only the tweets which have location_source as "REPORT" will show tweet location as name.However I could not get any tweet with location_source as REPORT.All of them were ANNOTATION based location sources.Can you suggest some test cases?

**Comment by Orbiter** [comment]
We only have REPORT if the message was imported by a geojson import (@zyzo: please provide an import example here so @prasht63  can reproduce this for his tests) or if the message was created by loklak using a rich tweet with location attachment (which we don't have by now, as far as I know)

**Comment by zyzo** [comment]
@prasht63 : You could add fossasia geojson messages to your local loklak, using this command : 
```sh
curl -i -F callback=p \
        -F url=http://cmap-fossasia-api.herokuapp.com/ffGeoJsonp.php \
        -F map_type=shortname:screen_name,shortname:user.screen_name,name:user.name,name:text,url:link \
        -F source_type=FOSSASIA_API \
        http://localhost:9000/api/push/geojson.json
```

**Comment by mariobehling** [comment]
Please provide screenshots. I do not see, that this issue has been solved.

![screenshot from 2015-07-28 11 54 47](https://cloud.githubusercontent.com/assets/1583873/8928563/89c39884-351f-11e5-810f-c01fd66b41a3.png)

**Comment by prasht63** [comment]
@mariobehling The place name will only show up
when showing a tweet on a map:
if (and only if) the field location_source contains the exact string REPORT then write below the tweet text:
left-aligned a "place mark" (that thing like a upside-down drop)
right to the mark the text from the field place_name

Since the normal Tweets don't have REPORT as location_source so the location won't come in those cases.Loke you have posted. Closing this issue as it has been solved.

**Comment by Orbiter** [comment]
@prasht63 closed this correctly according the requirements I made. However, the result does not turns out to be satisfying. The architecture to identify different cases for the usage of place names was lacking the case which we are looking for with @mariobehling comment. Therefore I added another location_source type in https://github.com/loklak/loklak_server/commit/f06053436ae9f679ffd811b02ba2b26b9d62e0a2 with name `PLACE`. I will set this value in all cases where the location coordinates was created by annotation of the place name given by twitter.

I therefore reopen this issue. @prasht63 please replace the condition
> if (and only if) the field `location_source` contains the exact string `REPORT`

with the following condition:

 if (and only if) the field `location_source` contains either the exact string `REPORT` or the exact string `PLACE`.
