### ISSUE TITLE
links from tweet view on map shall go to loklak, not twitter

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#288]
all links which refer to users on the map view of tweets are currently pointing to twitter. They must point to loklak instead. Two simple rules:
- links *about* a `<user>` shall create a link to a loklak search for `from:<user>`
- links *mentioning* a `@<user>` shall create a link to a loklak search for `@<user>`

see example:
<img width="344" alt="tweetm" src="https://cloud.githubusercontent.com/assets/238730/8507768/d3bb107e-2251-11e5-9d61-a49ad15ddb72.png">
- clicking on "Michael Shep" shall cause to open `/search?q=from:MichelSchep`
- clicking on "@johncoffeymusic" shall cause to open `/search?q=@MichelSchep`

same with hashtags please!

**Comment by fuksi** [comment]
Done with #315

**Comment by Orbiter** [comment]
If I click on the user name (the big title line) then the link still goes to twitter!

also: this also applies to individual tweet view and the list view of the tweet. There none of the links are fixed. Please change *ALL* links to twitter with links to loklak. Just make a search in the code for 'twitter.com' and replace all where applicable

**Comment by fuksi** [comment]
Done with https://github.com/loklak/loklak_webclient/commit/1c8987aa6a1eccaac1d1de618f7cfc1d1d0a8657
