### ISSUE TITLE
Dates along the bottom of the histogram are not showing.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_webclient#29]
On Firefox 37.0.2 on win 2003 the dates selection (axis/scale) at the bottom is cutoff the histogram.
In Win 7 same version of Firefox it displays correctly.
A minor problem.

![histo ff 2003 date cut off](https://cloud.githubusercontent.com/assets/11748913/7468665/d53cec44-f33d-11e4-89a8-91dde8976587.PNG)

**Comment by Orbiter** [comment]
I see the same effect but I can constantly reproduce how to make them to appear:
- copy the share link and paste it into the url line
- the same graphics appears but with the dates below
Thats somehow a strange effect

**Comment by smokingwheels** [comment]
When searching and pasting the link it works now on both.
http://loklak.net:3001/statistics?q=youtube&since=2015-05-01_06%3A00&until=2015-05-06_10%3A00
A few times the results page just had the search, start and end date and nothing below but it is all working now.

Should the Browser sync disconnect banner and then sync reconnect banner comes again when asking for results?

**Comment by Orbiter** [comment]
I believe this is solved, my latest test was successful. If anybody sees the effect again, please report the browser type you used.
