### ISSUE TITLE
Implement "show followers/following around the world in percentagewise distribution"

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#296]
This kind of feature can be viewed at different services e.g. https://tweepsmap.com/Map

![screenshot from 2015-07-06 12 39 13](https://cloud.githubusercontent.com/assets/1583873/8520618/33294bb2-23dc-11e5-9f23-ee5d193db9b2.png)

**Comment by prasht63** [comment]
@Orbiter Is there a way loklak_server can relate a place name to a Country. For ex Berlin-->Germany , Delhi-->India

**Comment by Orbiter** [comment]
right now I have the ISO-3166 2-letter country code available in my data set. I am currently looking for a  ISO-3166 -to- geolocation table so that I could send you a coordinate where you can plot the accumulated info to.

To access this information efficiently, you would need to make an aggregation search on the (to-be-implemented)  ISO-3166 field in the search index which I would enrich with location coordinates in the aggregation result. Would that be a solution for you?

**Comment by prasht63** [comment]
I am looking for something like https://github.com/loklak/loklak_server/issues/62 where along with the location name you add the name of the country to the response 
```
{"locations":{"Singapore":{"place":["Singapore"],"population":3547809,"location":[103.85006699890363,1.2896698812440377],"mark":[103.85006699890363,1.2896698812440377]},"New York":{"place":["New York City"],"country":"USA",population":8175133,"location":[-74.00596630480419,40.71427148800075],"mark":[-74.00596630480419,40.71427148800075]}}
```

**Comment by Orbiter** [comment]
ok, I already added the field `place_country` and `place_country_center` to search results. The country can also be retrieved with aggregations, like:
```
http://loklak.org/api/search.json?q=/location&source=cache&fields=place_country&limit=6&count=0
```
This gives you aggregations for the countries but not the country name and not the country center location. I try to find a solution for that in the fashion you suggested above.

**Comment by prasht63** [comment]
Thanks

**Comment by Orbiter** [comment]
please retrieve the follower list from loklak_server, documentation is online at http://loklak.org/api.html#account .. please scroll down to "Retrieval of Twitter User Account Data" for details

**Comment by mariobehling** [comment]
This issue was closed automatically through your commit, but I do not see it solved on live.

**Comment by prasht63** [comment]
@mariobehling #311 is similar issue.So I have moved it there.
