### ISSUE TITLE
Show images which are embedded in search result timeline

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#30]
The timeline currently does not show images when they are embedded in the tweet. The json result includes the image path. Please deeply embed these in the results. They maybe need to be resized.

**Comment by julianfox** [comment]
Hey, i will try to manage it.

**Comment by Orbiter** [comment]
:thumbsup:

this is feature in the context of the milestone-plan at https://groups.google.com/forum/#!msg/loklak/7azwyuslmTU/q9ueCSgwjZUJ

**Comment by Orbiter** [comment]
I just tested your code and it looks good. Still: image display needs some enhancements, like:
- if there are more than one image, its not optimal to write them all in a column below each other. Maybe they fit side-by-side in a row, but maybe their format is not good for that. Because we don't know the actual size, we cannot know the orientation and size of these images in advance. Is there a library which can handle such situations?

**Comment by Orbiter** [comment]
I found two solutions to display images in a proper way:
- to properly fit the images side-by-side in each row, as thumbnails, you can use https://github.com/desandro/masonry
- to enlage these images and show (several) in a slide show, you can use https://github.com/dimsemenov/PhotoSwipe

If you like, use alternatives to these libraries but those looked right when I looked around what we can use to make the display of images awesome!

Please add these two features as well!

**Comment by aneeshd16** [comment]
Is anyone working on this? I am unable to add photoswipe, any help would be nice. :)

**Comment by fuksi** [comment]
I can work on this over the weekend *assigned to myself*

**Comment by fuksi** [comment]
@aneeshd16
Only 1 part of photoswipe can be installed with ```npm install photoswipe```. We'll need to copy and place ```photoswipe-ui-default.js``` in the components to be included as well ( and the rest of css stuffs).

Please pull and check the new branch ```feat_photoswipe```. You'll need to ```npm install```again. It's not finished yet. The ```createPhotoSwipe``` in ```controllers/wall.js``` is now called on every new tweet with images. It should be triggered on click of the masonry container. I wasn't able to pass e.g. ```ng-click= "wall.createPhotoSwipe(masonryId);``` to the directive's template ```status.html```.

However, things will change soon with the [new wall] (https://github.com/loklak/loklak_webclient/issues/52), so if it's not necessary anymore, please close the issue!

**Comment by sudheesh001** [comment]
Closed by #55
