### ISSUE TITLE
no line breaks within words in tweets on the wall

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#300]
The tweet view in the wall does not recognize words or word endings. Words *must not* be divided within the word. Never. A line break may only occur where a whitespace is. 

See example:
<img width="729" alt="grexit" src="https://cloud.githubusercontent.com/assets/238730/8530094/2d409a5a-241f-11e5-833f-5e0886e22b80.png">
I don't understand why you have not seen this before, this should not be something where a bug report is necessary.

If you fix this, then please don't include the next problem that I believe would come: a new line must not begin with a whitespace character.

**Comment by aneeshd16** [comment]
Before:
![image](https://cloud.githubusercontent.com/assets/5436027/8531247/9b2234e2-2443-11e5-9380-4f9778b37f48.png)
After:
![image](https://cloud.githubusercontent.com/assets/5436027/8531266/b2c53018-2443-11e5-994c-c3925f8d8107.png)

The CSS `word-break` property was mistakenly set to `break-all` everywhere. Changed it to `keep-all`.

**Comment by aneeshd16** [comment]
Good to close?
http://test.loklak.net/wall/display?data=%7B%22headerColour%22:%22%233c8dbc%22,%22headerPosition%22:%22Top%22,%22layoutStyle%22:%222%22,%22headerForeColour%22:%22%23FFFFFF%22,%22images%22:%5B%22both%22%5D,%22videos%22:%5B%22both%22%5D,%22audio%22:%5B%22both%22%5D,%22allWords%22:%5B%5D,%22anyWords%22:%5B%5D,%22noWords%22:%5B%5D,%22allHashtags%22:%5B%5D,%22from%22:%5B%5D,%22to%22:%5B%5D,%22mentioning%22:%5B%5D,%22eventName%22:%22ve%22,%22mainHashtagText%22:%22loklak%22,%22mainHashtag%22:%22%23loklak%22,%22showStatistics%22:true%7D
