### ISSUE TITLE
Too much wasted space in tweets on wall

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#304]
See example:
<img width="1003" alt="toomuchspace" src="https://cloud.githubusercontent.com/assets/238730/8544880/65f709da-24a9-11e5-9811-a753f30acf66.png">
Why is there so much space wasted? Is this a placeholder for something else (i.e. other media)?

@mariobehling How can we handle this? Please write your opinion and then lets turn this into a bug/feature

**Comment by mariobehling** [comment]
@Orbiter Aneesh is still working on the design and has difficulties with the card design. He is progressing steadily. So, I hope this will be solve in the upcoming days.

**Comment by mariobehling** [comment]
Please give us an update in this issue before starting to work on M3 and close if this has been solved.

**Comment by aneeshd16** [comment]
This is directly related to #319. I have added Michael's comments there. We can close this so that all discussion can be held there.
