### ISSUE TITLE
wrong query for wall content design values

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#305]
See example, this is what I have set up:
<img width="842" alt="ots15" src="https://cloud.githubusercontent.com/assets/238730/8544998/9963e88c-24aa-11e5-84c1-f48a14a97fe8.png">

now navigate to `/home/loklak/loklak/data` and call `tail -f loklak.log | grep ots`
What you get is:
```
2015-07-07 13:14:47.741:INFO::qtp1904436988-8930: /api/search.json?callback=angular.callbacks._0&count=10&q=%23ots15+ots15+ots2015 -> 1 records returned, 0 new
```
That means, the wall makes the following query: `#ots15 ots15 ots2015` which essentially means `#ots15 AND ots15 AND ots2015` which is wrong. Furthermore, the `#ots15` is given nowhere as request.

The right query would be: `ots15 OR ots2015`.

I will give you here the complete rule set for values in the input fields:
By now, the back-end is not able to mix AND and OR within one query. The front-end must check that this does not happen. Therefore we have several different cases:

Field | Values
----- | -----
All of these words | A B C
None of these words | D E F
Any of these words | *not allowed, disable this field if 'All of these words' or 'None of these words' are given*
These Hashtags | *not allowed, disable this field if 'All of these words' or 'None of these words' are given*

Query: `A B C -D -E -F`

Field | Values
----- | -----
All of these words | *not allowed, disable this field if 'Any of these words' or 'These Hashtags' are given*
None of these words | *not allowed, disable this field if 'Any of these words' or 'These Hashtags' are given*
Any of these words | A B C
These Hashtags | D E F

Query: `A OR B OR C OR #D OR #E OR #F`

**Comment by Orbiter** [comment]
add-on for people:

Field | Values
----- | -----
All of these words | *not allowed, disable this field if 'Any of these words' or 'These Hashtags' are given*
None of these words | *not allowed, disable this field if 'Any of these words' or 'These Hashtags' are given*
Any of these words | A
These Hashtags | B
From these accounts | C
Mentioning these accounts | D
To these accounts | E


Query: `A OR #B OR from:C OR @D OR @E`

**Comment by aneeshd16** [comment]
Thank you! This helps a lot! This will be done by EOD.

**Comment by aneeshd16** [comment]
> That means, the wall makes the following query: #ots15 ots15 ots2015 which essentially means #ots15 AND ots15 AND ots2015 which is wrong. Furthermore, the #ots15 is given nowhere as request.

Maybe you entered `#ots15` in step 1?

So if someone enters in "All words" or "No words", I also need to disable the people section.

This is solved in PR #308. :)

**Comment by aneeshd16** [comment]
@Orbiter, this is live, kindly test :)

**Comment by Orbiter** [comment]
This looks good with one exception: the wallOptions.mainHashtag is still included in the query. Thats the main hashtag from step one. This shall not be included in the query. Thats in wallDisplay.js in line 44+45.

I admit that actually the main hashtag should always appear in the wall query, but it is confusing if that is included from the first page. A better solution would be to copy the main hashtag from page 1 into the field "These Hashtags" so when the user selects page 2 the main hashtag is there already. So please do:

- remove the lines 44+45 in wallDisplay.js
- add the main hashtag from page 1 as default value into the field "These Hashtags", but only if not yet any content for that field was defined (to protect overwriting if the page 2 is selected again in the same wall definition)

**Comment by aneeshd16** [comment]
if the user fills in the mainhashtag on step 1, there are two cases:
1. The "these hashtags" field is empty. In this case, just make it the default value.
2. The "these hashtags" field has been filled. In this case the `mainhashtag` will be added as an value to that field.
This approach should do it. I'll update it by tonight and then we can test.

**Comment by Orbiter** [comment]
no. Following these rules, it would be completely intransparent for the user how the search is composed. Please make it s I suggested.

**Comment by mariobehling** [comment]
This issue is related to design choice in M3 as well, which are currently not clear in the existing design: https://github.com/loklak/loklak_webclient/issues/330

**Comment by Orbiter** [comment]
I will add a 'checked' mark without testing the implementation because the feature has changed so much that a test against the description does not makes sense.
