### ISSUE TITLE
Deletion of a particular tweet should be allowed, purge of tweets

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#306]
- [ ] Tweets that are scraped and deleted from twitter 
- [ ] Tweets that the user wants to delete from the loklak webclient
- [ ] Tweets from the application to purge on the loklak_server

How are we planning to tackle this on the server ?

**Comment by Orbiter** [comment]
As far as my experiences with the deletion option in twitter are: there are some misterious rule if and when I am allowed to delete a tweet. Sometimes this works, sometimes not. We must define our own rules.

Then, a deletion in loklak_server is difficult. As soon as a tweet is received, it is stored in the dump file and dump files are always shared. That looks like a deletion does not make sense any more. To actually purge a tweet, we would need to write a kind of 'delete' message which would command the import process next time to delete the recently imported message again. Should be possible somewhow.

**Comment by Orbiter** [comment]
fix is up!
