### ISSUE TITLE
tweetLink filter href has no value and target is missing when rendered.

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#307]

**Comment by fuksi** [comment]
Just `pic.twitter...` link. The rest works fine!

**Comment by sudheesh001** [comment]
<img width="1440" alt="screen shot 2015-07-08 at 9 11 43 am" src="https://cloud.githubusercontent.com/assets/4545925/8562651/f892e6b2-2551-11e5-8cb8-c0c827e5d28e.png">

Somehow the code seems to be working fine when the URL Regex is passing so this means its not the filter, Need to look into why this is causing a problem when executing it.

**Comment by aneeshd16** [comment]
Maybe the filters after this are causing it? Try removing all filters after this one and check if it happens?

**Comment by sudheesh001** [comment]
Will be fixed with the next merge.
