### ISSUE TITLE
Implement Regional Origin List View of Followers/Following

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#312]
An example here is Tweepsmap

![screenshot from 2015-07-07 16 45 05](https://cloud.githubusercontent.com/assets/1583873/8548856/ad0bdc42-24c7-11e5-8894-29d7e82ae9c5.png)

**Comment by Orbiter** [comment]
please retrieve the follower list from loklak_server, documentation is online at http://loklak.org/api.html#account .. please scroll down to "Retrieval of Twitter User Account Data" for details

**Comment by prasht63** [comment]
Plan of action: 
A modal overlay will show all the stats regarding the followers.Something like this
![image](https://cloud.githubusercontent.com/assets/2105062/8935760/05c4d384-356c-11e5-9c79-72f307df9a73.png)

**Comment by mariobehling** [comment]
What do you plan to show in this statistics? We need to be able to distinguish between followers/followings/other data. A modal overlay might not be the best option. 

We need a way to show
* [ ] statistics for followers using loklak data (not the twitter API!)
* [ ] statistics for following accounts using loklak data (not the twitter API!)
* [ ] statistics for other data e.g. IoT

A basic idea below. Please expand on this idea.

![screenshot from 2015-07-28 20 05 32](https://cloud.githubusercontent.com/assets/1583873/8939464/dba934f2-3564-11e5-9256-2ae804ea6279.png)

**Comment by prasht63** [comment]
So shall we go with a new route something like /stats?
Currently I am using the data from Loklak only for follower.Once Loklak supports following info we can extend the stats to following too.
Data I have for followers is 
1. Country wise %age distribution
2. City wise %age distribution 

We can also show distribution in terms of follower's following, like how many your followers have following more than 1000 or something.

**Comment by mariobehling** [comment]
Yes, that would be great. Please show us some mockups or design ideas. How do others do this? I have another sample below with a way to possibly select followers/followings/IoT data, but all of this are just drafts based on tweetsmap and I think it would be great to come up with something different/better.

![screenshot from 2015-07-28 20 05 32](https://cloud.githubusercontent.com/assets/1583873/8939955/a3a368ae-3567-11e5-8efc-954a694d7ecd.png)

**Comment by prasht63** [comment]
![image](https://cloud.githubusercontent.com/assets/2105062/8941498/98286094-358d-11e5-9022-f05073825191.png)
@mariobehling  I am thinking something like this.This will retain the design singularity by conforming with the wall design and we can show all the three as tabs

**Comment by prasht63** [comment]
So I have still one doubt, should I implement this screen as modal over the map page or should I create a new /stat route, for that we will have to add a item in top nav just like wall, map etc

**Comment by prasht63** [comment]
As per commit https://github.com/loklak/loklak_webclient/commit/fa4878a44ddfaf6e18a12e68ca02edc0c149b7d4 . Following things are done 
- [ ] List of followers segregated country wise and ready for plotting via pie chart.
- [ ] List of followers location wise segregated and ready for plotting via pie chart.
- [ ] Top 5 most influential followers(based of the number of followers of them) retrieved and ready to be shown.
- [ ] To be done : Segregation of followers based on their number of followers.

I am thinking of segregating in these categories of followers : 
1.Having followers 0-500
2.Having followers 500 -1000
3. Having followers >1000
@mariobehling Your inputs on this please.

**Comment by mariobehling** [comment]
@prasht63 Please show us a page how your current idea looks like. How about adding it to test.loklak.net/analyze for now? Maybe add it on the top bar and let's think if this is the way to go. We need to consider a dashboard. Let's go step by step.

**Comment by mariobehling** [comment]
or maybe we should rather call this "report" like loklak.net/report

**Comment by prasht63** [comment]
I have started with Analyze, will be finishing it in an hour or so. I will change it to report before sending a PR

**Comment by prasht63** [comment]
Developement status : On clicking analyze you are taken to a page where you see this, Through this input box you can see anyone's follower stats.By default it will show the logged in user's
![image](https://cloud.githubusercontent.com/assets/2105062/8971162/bdfd6470-366b-11e5-8294-4448538fdc2d.png)
Till now I have added only two graphs.Rest will add tomorow
![image](https://cloud.githubusercontent.com/assets/2105062/8971185/f7ad32ea-366b-11e5-9d42-681bc928e994.png)

**Comment by prasht63** [comment]
@Added Top Influential Followers ,  city wise distribution . PR coming soon
![image](https://cloud.githubusercontent.com/assets/2105062/8977198/afffcb26-36b4-11e5-95ec-2399b62c0d53.png)

**Comment by mariobehling** [comment]
I do not see which countries and cities are shown in the chart.

Which technology are you using?

**Comment by prasht63** [comment]
@mariobehling  I am using chart.js since it was already been used in Wall statistics so I did not have to include new libraries . Once you hover on each division of pie chart you will see it. You can see the behaviour here http://www.chartjs.org/docs/#doughnut-pie-chart
