### ISSUE TITLE
Implement beautiful design and additional info for followers/following map

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#313]
This issue is related to https://github.com/loklak/loklak_webclient/issues/232

Step 1: Make a list of useful design features
Step 2: Implement features

Some thoughts about useful features:
* [ ] scroll over effect of pictures on map shows larger image, followers/following info and link "more"
* [x] click on photo shows larger image, followers/following info and latest three tweets

**Comment by mariobehling** [comment]
Please mark that each point has been closed before closing this issue. Where can we test this?

**Comment by prasht63** [comment]
http://test.loklak.net/map

**Comment by prasht63** [comment]
If you dont see the changes try in incognito.

**Comment by prasht63** [comment]
I am closing this as it has been implemented and can be tested at test.loklak.net/map
