### ISSUE TITLE
render the first, top message in the "wall" LARGE

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#32]
This feature has the target to reach the milestone at 
https://groups.google.com/forum/#!msg/loklak/7azwyuslmTU/q9ueCSgwjZUJ
it also is based on https://github.com/loklak/loklak_webclient/issues/31

We want to see the first/top message in the timeline VERY LARGE. To show the message in a large form, increase the image size (take the large one, 400x400, link like
https://pbs.twimg.com/profile_images/577515909335511041/AFPxKLw3_400x400.png )
and display the message text in larger letters.

This way to display the message shall encourage people in conferences, who see the wall simultaneously during speeches, to tweet their own message to appear on the wall.

**Comment by Orbiter** [comment]
the given image link path  in the loklak json actually always ends '_bigger'. if you replace 'bigger' with 400x400 or 200x200 you get the picture which is bigger than 'bigger' :)

**Comment by julianfox** [comment]
For the first message, do we display the images ?

**Comment by Orbiter** [comment]
yes, please!

**Comment by Orbiter** [comment]
I tested this and it looks good!

but...when the entries below the large image is updated, the whole list loads again. That should be done more smoothly, like shifting them on the screen below.

**Comment by julianfox** [comment]
Oh, normally there is a transition animation, you have no animation at all ?

**Comment by sudheesh001** [comment]
The first message in the wall is comparatively larger than the rest. I think this can be closed safely, if this needs more discussion, please feel free to reopen.
