### ISSUE TITLE
Map not centered

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#323]
There were already some discussions about requests to center the map. As there is no issue to follow up, I am adding one here. Please ensure a centered logic display of the map.

![screenshot from 2015-07-09 09 50 07](https://cloud.githubusercontent.com/assets/1583873/8590687/254b506e-2623-11e5-931f-ad30022c1816.png)

Compare to a centered map here:

![screenshot from 2015-07-07 16 22 27](https://cloud.githubusercontent.com/assets/1583873/8548331/814fe272-24c4-11e5-874b-d707e4aff1b0.png)

**Comment by mariobehling** [comment]
Showing a map centered to Russia makes a bad showcase and getting this right is a high priority before we start working on M3.

**Comment by prasht63** [comment]
@mariobehling where do you think the center should be? I had centered the map to USA but @aneeshd16 felt that it should be at world center . Please clear my doubt about where the center should be.I will apply at once.

**Comment by mariobehling** [comment]
@prasht63 I do not understand the question. There is a standard display of maps. I already posted an image above. Reposting it below. Check any world map on the net. Almost all will display it as in the following image.

![screenshot from 2015-07-07 16 22 27](https://cloud.githubusercontent.com/assets/1583873/8548331/814fe272-24c4-11e5-874b-d707e4aff1b0.png

**Comment by mariobehling** [comment]
We are just looking to see the most standard map page. It is a surprise that there are questions.

https://en.wikipedia.org/wiki/Web_Mercator

![openstreetmap_homepage](https://cloud.githubusercontent.com/assets/1583873/8636953/94a4e77c-287b-11e5-9300-2821014a61ae.png)

**Comment by mariobehling** [comment]
This is the current view on loklak, which shows that the map is not in the center of the screen: ![screenshot from 2015-07-15 08 05 51](https://cloud.githubusercontent.com/assets/1583873/8691869/8a1feb9a-2ac8-11e5-993d-9f2fb02d491d.png)

This is a view how it should be centered.
![screenshot from 2015-07-15 08 06 27](https://cloud.githubusercontent.com/assets/1583873/8691881/aa645918-2ac8-11e5-85b0-ed11e16ed478.png)
