### ISSUE TITLE
Wall load slow and using lots of resources leads to regularly slow or unresponsive browsers

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#327]
![screenshot from 2015-07-09 16 06 37](https://cloud.githubusercontent.com/assets/1583873/8597321/fcdcd422-2654-11e5-84da-72eade869d6e.png)

**Comment by mariobehling** [comment]
Any idea what is the reason and potential solution? Can this be fixed before we start the next sprint?

**Comment by aneeshd16** [comment]
I will try to fix this today, it looks like an infinite loop or maybe overuse of memory...shouldn't happen normally. This does not happpen with all walls, I have had walls running for hours without any problem. 
Link for reference:
http://test.loklak.net/wall/display?data={%22headerColour%22:%22%232c88c9%22,%22headerPosition%22:%22Top%22,%22layoutStyle%22:%222%22,%22headerForeColour%22:%22%23FFFFFF%22,%22images%22:[%22both%22],%22videos%22:[%22both%22],%22audio%22:[%22both%22],%22allWords%22:[],%22anyWords%22:[],%22noWords%22:[],%22allHashtags%22:[],%22from%22:[],%22to%22:[],%22mentioning%22:[],%22eventName%22:%22MozWeekend%20Berlin%22,%22sinceDate%22:%222015-06-30T23:00:00.000Z%22,%22untilDate%22:%222015-07-22T00:00:00.000Z%22,%22mainHashtagText%22:%22mozweekend%22,%22mainHashtag%22:%22%23mozweekend%22,%22showStatistics%22:true}

**Comment by mariobehling** [comment]
Seems to be fixed, but wall displays irrelevant results now https://github.com/loklak/loklak_webclient/issues/347
