### ISSUE TITLE
Implement logo upload and automatic scaling, reuse implementation of module to upload images to tweet if possible

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#329]
![screenshot from 2015-07-09 16 44 29](https://cloud.githubusercontent.com/assets/1583873/8598201/ca1fe704-2659-11e5-9ca8-1fe64bbabb44.png)

The wall does not offer an image upload yet. Please reuse existing ways in loklak if possible/

**Comment by mariobehling** [comment]
@aneeshd16 What options do we have? I saw this comment from you in the standup:

> Blockers: Will have to decide between doing the image upload, scaling and conversion manually or using yet ANOTHER library.

**Comment by aneeshd16** [comment]
I found a module, https://github.com/adonespitogo/angular-base64-upload that would make this task trivial. However, I need @fuksi and @sudheesh001 views, if we need to go for something more general. IMO, this should be fine.
Demo: http://embed.plnkr.co/MTzfQASN8ZVeocAq7VcM/preview

**Comment by fuksi** [comment]
This implementation looks good for me, it's actually a lot more compact of what we're using here at: 
- https://github.com/loklak/loklak_webclient/blob/master/app/js/services/file.js 
- & 34-39 in https://github.com/loklak/loklak_webclient/blob/master/app/js/controllers/tweet.js  

Please implement this directive and then refer to here your experience with it so we can make the decision to change code in similar places :)

**Comment by aneeshd16** [comment]
Okay, I will go with this, will take me day to implement.

**Comment by sudheesh001** [comment]
@aneeshd16 Looks good with this present but also for hellojs the file has to be uploaded as a file instead of base64. So I believe building the directive to take a file instead would be better and would suit the overall implementation that's needed.

**Comment by aneeshd16** [comment]
@sudheesh001 , we can use the custom parser mentioned here https://github.com/adonespitogo/angular-base64-upload#custom-parser to directly work with the file object.

**Comment by mariobehling** [comment]
This feature does not work fully. Please close when this feature has been fully tested and confirmed to work on test site.

**Comment by mariobehling** [comment]
Please check this: I uploaded an image for a wall. It all works fine. Now I create another wall without an image. When I generate the second wall suddenly the image of the previous wall is there.

**Comment by aneeshd16** [comment]
@mariobehling I could not reproduce this. Can you give me the exact steps please?

**Comment by mariobehling** [comment]
Ok, seems to be solved now. But at the moment tweets are not loading on any wall. 
Also I get an error message from Firefox preventing the new tab for the wall.
![screenshot from 2015-08-03 18 31 48](https://cloud.githubusercontent.com/assets/1583873/9042296/10044126-3a0e-11e5-9739-16107f578a18.png)

**Comment by aneeshd16** [comment]
This is quite strange, as I have not changed that part of the code which opens these tabs. They are simple hyperlinks with `target=_blank`. If this problem was not appearing earlier, there should be no reason it is happening now unless the browser settings have changed.

Also, I just tried it in firefox and could not reproduce this.

**Comment by mariobehling** [comment]
Ok, the walls are back. Seems it was a temporary glitch. Please check the wall on Fx. It might have been related to another code change.
