### ISSUE TITLE
Implement a thought through choice of media items for wall

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#331]
Currently there are options that do not make sense, e.g. the user can choose "only images", but can also choose "show videos". There are choices that exclude each other. Please implement the following functionality and UI.

* [x] add a section below the left hand side area "What do you want to show on the wall?" (as described here https://github.com/loklak/loklak_webclient/issues/330) with the title "Which media do you want to show on the wall"
* [x] add button sliders for the following
 * [x] Show images Yes - No - Only
 * [x] Show video Yes - No - Only
 * [ ] Show audio Yes - No - Only (Is this already an implemented option?)
* [x] If the user chooses at one point "Only", all the other options should change their color to grey and become unavailable

**Comment by aneeshd16** [comment]
1366x768 (Scrollable)
![image](https://cloud.githubusercontent.com/assets/5436027/9026334/96a39490-3949-11e5-8f79-fc2025885901.png)
![image](https://cloud.githubusercontent.com/assets/5436027/9026335/9ad7493a-3949-11e5-84c4-ef8650659181.png)

1920x1080
![image](https://cloud.githubusercontent.com/assets/5436027/9026341/c064b9b2-3949-11e5-85eb-dca89690109f.png)

**Comment by mariobehling** [comment]
Looks nice for me.

The follower threshhold field seems to be out of relation a bit in comparison to the other areas that are changing the size.

**Comment by aneeshd16** [comment]
Cool. Okay, will change that.

**Comment by mariobehling** [comment]
The options are displayed, but it does not show up on the wall as desired. If user chooses "Display Images Only", then only images should show up and a tweet text can be displayed similar to tweetbeam. This was discussed at the beginning of the project e.g. compare: http://www.tweetbeam.com/show?query=loklak

**Comment by aneeshd16** [comment]
Currently I am following tweetwall's implementation. The type of wall displayed by tweetbeam is completely different from what has been done till now, both from a UI and code perspective. tweetbeam's wall does look good, but as you mentioned, it is conflicting with the designs we have of existing layouts. We can have another layout called the "image wall" which would look similar to that. Something like this:
![image](https://cloud.githubusercontent.com/assets/5436027/9235263/48227ce0-415b-11e5-915d-003d16dd54f4.png)
Like the map layout which automatically adds the `/location` parameter, this new layout will automatically add the `/image` parameter. Also, this layout loads a LOT of images at once, so the possible increase in strain on the server will also have to be considered.

We can open a new issue for this, as this discussion is out of the scope of this issue. However, we already have 4 layouts, and there can be many more possible layouts. The code is written in such a way that a layout is a "pluggable component", and no change is required to existing code to add new layouts. Each layout has its own directive. A single controller only sends data to the chosen directive which decides how to show it. The task of adding more layouts to the wall is a continuous one, and we can have a lot more layouts in the future with new and innovative designs.

**Comment by mariobehling** [comment]
@aneeshd16 Awesome ideas and great implementation of layout plugins! Thanks! Please create another issue for an image wall.
