### ISSUE TITLE
Move "Show statistics" to "Design area" and rename to "Leaderboard"

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#332]

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/8934314/b87fe21e-3564-11e5-9cfc-042b407abf72.png)

**Comment by mariobehling** [comment]
Feature is not fully implemented as leaderboard does not show up in preview.

![screenshot from 2015-07-28 19 53 32](https://cloud.githubusercontent.com/assets/1583873/8939031/73f83c60-3562-11e5-99a1-6d93a3629692.png)

Compare to:

![screenshot from 2015-07-28 19 53 56](https://cloud.githubusercontent.com/assets/1583873/8939035/7b170576-3562-11e5-9bbc-c8793c733299.png)
