### ISSUE TITLE
Implement additional design options in "design" area for wall

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#333]
Implement additional design options in "design" area for wall:
* [ ] Leaderboard Type
* [ ] Show event name
* [ ] Show loklak Logo

![screenshot from 2015-07-09 17 32 51](https://cloud.githubusercontent.com/assets/1583873/8599560/823add38-2661-11e5-8ef5-1d2da7babb41.png)

**Comment by mariobehling** [comment]
In the test site I see, that you moved the "Start twitter wall". I am not sure why. Also there is no more error message if I did not enter an event name.

![screenshot from 2015-08-02 23 25 34](https://cloud.githubusercontent.com/assets/1583873/9028108/ee549c38-396d-11e5-8a72-dadc10e0d234.png)

**Comment by mariobehling** [comment]
The color of "Next" is also changed making the distinction of the function less visible. Please return to former way.
![screenshot from 2015-08-02 23 27 30](https://cloud.githubusercontent.com/assets/1583873/9028116/29e3a4a6-396e-11e5-8bf4-b47586502111.png)

**Comment by aneeshd16** [comment]
I changed the colour of the next button. The reason why I moved the "Start wall" button is because I will be soon be implementing #334 and it would look like this:
![image](https://cloud.githubusercontent.com/assets/5436027/9039211/98675d38-3a17-11e5-97c8-fd1cfe9fba0e.png)

**Comment by mariobehling** [comment]
Ok, I see. Well, let's not overwhelm the user with options. These are too many prominent buttons.

1. [ ] If the user does not want to save the wall on the top right is an X. (Tweetwall does not have it, but we do.) So this will let us have one button less - no need for "close without saving"
2. [ ] In Step "Info" and "Content" the user has not chosen the design. Hence, please take out the button "start twitter wall" here. (Even though it would be possible just to offer the standard wall. We do not want to confuse the user with too many buttons.)
3. [ ] Now in the final step "design" the "start twitter wall" button can go back where it was before.

**Comment by aneeshd16** [comment]
I see. Sounds good.

**Comment by aneeshd16** [comment]
As for leaderboard type, there is nothing like that in the server. The leaderboard lists the top hashtags and top twitterers.
From tweetwall:
>The Engagement Leaderboard uses replies and retweets as Leaderboard votes 

Cannot be done right now. Details: https://github.com/loklak/loklak_server/issues/81#issuecomment-127195960
>The Interactions Leaderboard counts Tweets sent from a @user 

This is what we have.
>The Followers Leaderboard type ranks by the number of followers they have

 This would be too slow and would take a lot of resources just to display this.
