### ISSUE TITLE
Map search and video search replaces new search word with old one

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#346]
This is a really strange effect, you should have seen it yourself when doing a unit-test.

- Open test.loklak.net
- search for "stone"
- click on the map - > this shows results for stone (so far ok)
- enter in the search box "water"
- the map shows again in the search box the word "stone" and shows results for "stone" (but far less, but thats another problem)

**Comment by mariobehling** [comment]
@fuksi @Orbiter Has this been solved?

**Comment by fuksi** [comment]
I didn't realize this issue until now.    
I also noticed the issue and did a patch long time ago to fix this. The obstacle is when trying to delete the old map.   

The solution is ( I don't think it the best, but it works ok for user experience), the application will detect if you already did a map search, and try to do a new map search, the url will be changed for the new search and the page is reload.

**Comment by Orbiter** [comment]
I just tested this and the behaviour did not change at all. Please point me to the commit where you 'fixed' this.

**Comment by Orbiter** [comment]
The same behaviour can be seen on the 'videos' view, but not on the 'photos' view where it works correctly.

**Comment by fuksi** [comment]
The old solution in in here, on line 36-38 : https://github.com/loklak/loklak_webclient/blob/master/app/js/directives/globalSearchForm.js

However the solution seems obsolete with many cases. I found a way to deal with removing old map. Will create a PR today, possibly along with the solution for behavior in `videos` filter.
