### ISSUE TITLE
Twitter wall displays irrelevant results

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#347]
the hashtag is: mozweekend

![screenshot from 2015-07-12 10 25 53](https://cloud.githubusercontent.com/assets/1583873/8637052/6d9a5b94-2880-11e5-9e9e-b07249309b27.png)
http://test.loklak.net/wall/display?data={%22headerColour%22:%22%233c8dbc%22,%22headerPosition%22:%22Top%22,%22layoutStyle%22:1,%22headerForeColour%22:%22%23FFFFFF%22,%22images%22:[%22both%22],%22videos%22:[%22both%22],%22audio%22:[%22both%22],%22allWords%22:[],%22anyWords%22:[],%22noWords%22:[],%22allHashtags%22:[{%22text%22:%22mozweekend%22},{%22text%22:%22mozweekend%22}],%22from%22:[],%22to%22:[],%22mentioning%22:[],%22eventName%22:%22mozweekend%22,%22mainHashtagText%22:%22mozweekend%22,%22mainHashtag%22:%22%23mozweekend%22,%22sinceDate%22:%222015-07-01T09:00:00.000Z%22,%22untilDate%22:%222015-07-30T20:00:00.000Z%22,%22showStatistics%22:true}

**Comment by aneeshd16** [comment]
@Orbiter, the wall is making this query for the link posted above:
http://loklak.org/api/search.json?callback=angular.callbacks._1&count=10&q=%23mozweekend+OR+%23mozweekend+since:2015-07-01_14:30+until:2015-07-31_01:30

**Comment by Orbiter** [comment]
fixed with https://github.com/loklak/loklak_server/commit/e529743f9db88ed83987951037796ea7df136509

Big news: AND and OR can now be mixed in search requests. OR binds stronger than AND.
`A OR B C` is equal to `(A OR B) AND C`.
This behaviour was tested on search.twitter.com and it is the same there.

**Comment by aneeshd16** [comment]
This is great!
I just need to construct the query such that all the OR params are first, and then come all the AND params.

**Comment by Orbiter** [comment]
no you can mix then also:

`A B OR C D OR E /images` would be interpreted as `A AND (B OR C) AND (D OR E) AND /images`
