### ISSUE TITLE
special display of search term on the wall (aka: tell people what the hashtag is)

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#35]
This feature has the target to reach the milestone at 
https://groups.google.com/forum/#!msg/loklak/7azwyuslmTU/q9ueCSgwjZUJ
it also is based on https://github.com/loklak/loklak_webclient/issues/31 and https://github.com/loklak/loklak_webclient/issues/34

When the wall is showed the first time, it should NOT display a search input box any more (in contrast to a normal search page), because a wall usually is left as it is and it refreshes automatically.

Instead, the search term shall be written in a large font at the top of the left column, right below the loklak icon (see https://github.com/loklak/loklak_webclient/issues/34 )

This shall show the audience the tag that the people should use if they want to appear on the wall. Therefore the text below the icon shall be
"hashtag: #hashtag" if the search term starts with a hash

If the search term does not start with a hash, then the line shall be
"wall for 'query'"

**Comment by sudheesh001** [comment]
@Orbiter Do we use a specific URL like `/wall?q=IPL` if we want to avoid the search input box in the wall/ page ? Currently I've just cloned the search functionality to wall. If we decide on how the URL has to be taken, I can proceed.

**Comment by sudheesh001** [comment]
![screen shot 2015-05-10 at 5 15 33 pm](https://cloud.githubusercontent.com/assets/4545925/7554634/34dda1e0-f738-11e4-9eb1-f8a1daef4b50.png)

Locally i've the commit which displays the heading search query. Currently the wall is as follows.

**Comment by julianfox** [comment]
Hey @sudheesh001 i an working also on this, i already did the live update mechanism and the fact that the first tweet is highlight

**Comment by julianfox** [comment]
I'll try to make a pull request this evening or tomorrow evening

**Comment by Orbiter** [comment]
@julianfox :+1: :+1: 

@sudheesh001 yes, the suggested URL would be great. After the first time the input was made, the input box should not be shown any more.

**Comment by sudheesh001** [comment]
Fixed the `/wall?q=`, Fixes the wall functionality at fa579871791cb847fcb7af154b8f6783d6ac6453
