### ISSUE TITLE
Very few Followers displayed / Following missing

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#359]
![screenshot from 2015-07-15 07 59 00](https://cloud.githubusercontent.com/assets/1583873/8691782/7d19b242-2ac7-11e5-8c90-3ff48652fe8e.png)

**Comment by prasht63** [comment]
@mariobehling I am planning to add a drawer navigation showing stats and info about the followers/following which will also be helpful in showing data for other Map Issues like startups on map and other IOT Issues.I will send a PR today for the followers following map.Preview
![image](https://cloud.githubusercontent.com/assets/2105062/8717331/08a1881c-2bb8-11e5-9749-77794a6bc920.png)
![image](https://cloud.githubusercontent.com/assets/2105062/8717369/77d59cdc-2bb8-11e5-81f6-7dc7150920f6.png)

This will also present a list view of the followers/following for a particular user

**Comment by mariobehling** [comment]
Just tested the currently deployed version. 
a) Followers: Only ten are displayed (before there were dozens already)
b) Following: Currently zero are displayed

**Comment by mariobehling** [comment]
Followers/Following info as a sidebar sounds interesting. Please move the sidebar to the right and keep it similarly small to the activity sidebar like in Facebook.

**Comment by Orbiter** [comment]
please retrieve the follower list from loklak_server, documentation is online at http://loklak.org/api.html#account .. please scroll down to "Retrieval of Twitter User Account Data" for details

**Comment by mariobehling** [comment]
1. Ok, I see the sidebar and I do not understand what feature you try to implement here. There are some followers/following showing up in a sidebar. I cannot click on them and show them and they show on a map or I cannot see their tweets or anything. These might be interesting features, but I do not see them on our list. Also, there is no mockup or anything where you actually explained what you are doing. When you said you plan a sidebar, I would have expected that you explain your idea more. I had a very different thing in mind - an activity bar of the timeline like in Facebook, where you can click on stuff and then it pops up on the map for example. As this feature is not thought through please take the sidebar out.

2. I am seeing a erroneous display on the map. 
a) Followers/Following are showing up twice even though they are in the same category (e.g. an account "shows up twice as follower)
![screenshot from 2015-07-25 08 52 57](https://cloud.githubusercontent.com/assets/1583873/8888366/d1d2876a-32aa-11e5-8509-68817e93cd28.png)
b) Followers/followings appear/disappear depending on the zoom of the map.
![screenshot from 2015-07-25 08 53 20](https://cloud.githubusercontent.com/assets/1583873/8888372/08022eee-32ab-11e5-94da-dded3224b9f7.png)

b)

**Comment by prasht63** [comment]
@mariobehling The side bar is just temporary until we have support from loklak for followers and following both.The current side bar just lists out all the followers plotted so that you know how many followers/following are there on the map.As it is an added option as a drawer which does not obstruct the view, I don't see any point removing it for now. Although it can be removed easily if you want.

**Comment by prasht63** [comment]
For the erroneous display of followers.Thats strange, I am looking into that.

**Comment by mariobehling** [comment]
> The side bar is just temporary until we have support from loklak for followers and following both.

Why do we need it? Where is the issue relevant to get this?

> The current side bar just lists out all the followers plotted so that you know how many followers/following are there on the map.

It does not do that. And the sidebar design displays people in a view with all kinds of things. 
 It is not clear what you want to achieve. 

![screenshot from 2015-07-25 10 15 29](https://cloud.githubusercontent.com/assets/1583873/8888672/57fe7888-32b7-11e5-8e82-2787208f54ec.png)

If you just want to show the number of followers/followings, please simply add the number in the top right overlay item. (where the red crosses are).

![screenshot from 2015-07-25 10 19 28](https://cloud.githubusercontent.com/assets/1583873/8888670/4bdfc5c0-32b7-11e5-8639-3d357b8e0822.png)

Please take that sidebar out unless you can explain the usefulness of the design and feature. Currently it does not add anything except for the two numbers - how many followers/following are on the map.

I do not understand why I have to look into this now. We have a lot of things that are more important and in your task for a milestone, which you did not do. There is no reason to work on this for me.

Simply showing the number is a small feature and there is no need for your sidebar, which is not thought through.

**Comment by prasht63** [comment]
Okay I will remove this.

**Comment by mariobehling** [comment]
The whole point of this issue was to identify why there are only so few followers/followings displayed. The good thing is, that you put up the number. Why are there only 13 followers displayed? What can we do to get more people?

**Comment by prasht63** [comment]
The problem is that we are still plotting followers from Hello.js and it has limitations on it put by Twitter.I am working on removing this dependency on Hello.js and bring Loklak into since now Loklak supports followers info.

**Comment by mariobehling** [comment]
I am assigning this to @fuksi. Let's try to solve this by using loklak instead of the twitter-API.
