### ISSUE TITLE
refresh the timeline in the wall

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#36]
This feature is part of the milestone target at https://groups.google.com/forum/#!msg/loklak/7azwyuslmTU/q9ueCSgwjZUJ
Because this feature changes the content of the top-tweet, it is based on the feature https://github.com/loklak/loklak_webclient/issues/32

The wall shall re-load itself. The refresh period shall be based on the number, given in the search result json search_metadata.period which is the average time between tweets in milliseconds. The refresh time shall be
20 seconds if period is > 30000
0.7 * period if period is <= 30000
5 seconds if period is < 7000

An update period below 5 is very rare and we don't want to put the scraping frequency on twitter too high.

The refresh method must compare the previous list with the new one and identify the number of tweets which are new. For each new tweet, there shall be an update animation:
- replace the top tweet by the new one
- add the previous top tweet to the timeline below, which shall be moved smoothly downwards
- wait at least three seconds before doing this again with the next new tweet.

**Comment by julianfox** [comment]
This feature is only for the wall view, right ? not the search view ?

**Comment by Orbiter** [comment]
right, this is only for the wall, not the search view.

**Comment by Orbiter** [comment]
This is working well, but the update does not shift the entries, it just reloads the whole page.
Can you make this with animations, like move the content down and place the first on top?

**Comment by julianfox** [comment]
It's already done, it's weird that you can't see it...

**Comment by fuksi** [comment]
There're already some animations. Let's close this!
