### ISSUE TITLE
custom map layers, show tweets on *other* maps

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#364]
Will it be possible to show a custom map (instead our own) with our loklak messages shown live on it?
The custom map would be something like http://campmap.mazdermind.de/

If yes, I would consider this an option for the wall, where:
- the user adds an url pointing to the overlay of the *other* map
- the user defines a fixed viewport on the map to have only things visible from the overlay of the *other* map

If this is possible, let's turn this into a feature. This would be huge thing to show at the #CCCamp15!

**Comment by mariobehling** [comment]
So you are talking about the base map - the background map - right? It depends if they offer an API similar to Google or OpenStreetMap.

**Comment by Orbiter** [comment]
Yes the base map optional with an already existing overlay. The idea is, that there is a conference building layout or a large area like the CCCamp as given in the example above. This would enrich the tweets appearing on the map with the necessary background information which would show how exactly tweets and event map belong together.

**Comment by mariobehling** [comment]
Let's define an issue for this, when it comes up.
