### ISSUE TITLE
show the statistics "top twitterers", "top mentions", "top hashtags" in wall

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#37]
This feature builds up on https://github.com/loklak/loklak_webclient/issues/31

The statistic widgets from the statistic view shall be displayed in the left column of the wall, below the hashtag line (see https://github.com/loklak/loklak_webclient/issues/35 ).

The refresh time of the widgets must be independent from the update cycle of the wall. While the wall updates in a period as given in the search result, the statistic widgets shall update only once a minute. The time frame for the statistics must be from: (actual time - 1 hour) to: actual time

**Comment by Orbiter** [comment]
consider this feature as 'hold on' since we currently discuss different wall designs which may make this feature superfluous.

**Comment by Orbiter** [comment]
This feature is still valid. Please integrate this into the wall as intended and as an option. This is related to https://github.com/loklak/loklak_webclient/issues/156#issuecomment-111016380

**Comment by aneeshd16** [comment]
This is the same as #73, we can close this so that #73 can be the single issue to track all discussion related to showing stats in the wall.

**Comment by mariobehling** [comment]
Done.
