### ISSUE TITLE
pop-up of tweet details on the map not on the right position / broken

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#370]
steps:

- search something on the map
- click on a dot
- this shows up:

![markerbroken](https://cloud.githubusercontent.com/assets/238730/8743909/32827cac-2c73-11e5-83e1-8b17d16d72ad.PNG)

You can see that there is a marker sign (with the arrow down) which overlaps with the message box. The box should be above the marker, not the marker inside.

**This is one of the many totally superfluous and extremely time-killing bug issues which makes me completely depressed about this project. It would be obvious for EVERYONE that here is something broken. Instead of fixing these things right away, you just drop that stuff in the code and leave it until someone has to do MUCH MORE work to write an issue, make screen copies and put it into the workflow than it would be for you to simply change a vertical display value to make it look beautiful.**

PLEASE try avoid such kind of issues in the future. PLEASE try to do complete, beautiful work.

**Comment by prasht63** [comment]
@fuksi I think this started after the design changes regarding moving CSS files.Can you look into it?

**Comment by fuksi** [comment]
I already noticed and fixed this four days ago at https://github.com/loklak/loklak_webclient/commit/719f55c6429cfb86e0246d9f490d2c8ca5960658

http://test.loklak.net/search?q=%23fossasia%2B%2Fmap
