### ISSUE TITLE
Gitter chatroom private

### ISSUE THREAD

**Issue by pguth** [loklak/loklak_webclient#379]
... but advertised as "chat with devs" in the README.

**Comment by Orbiter** [comment]
@mariobehling when I added that chatroom comment in the README I did not know that it is private. Should we keep that?

@pguth good to know that you want to get in contact. please contact me @0rb1t3r (twitter) or @mariobehling (twitter) to ask anything.

**Comment by sudheesh001** [comment]
@Orbiter We currently have an organization chatroom, keeping this private, we can create a chatroom for this repository and keep it public, also then we'd need to change the gitter join badge in the readme

**Comment by mariobehling** [comment]
@pguth Good to see you here! I invited you to the organization. Please join the discussion on https://gitter.im/loklak

**Comment by SilentFlame** [comment]
@Orbiter , @mariobehling , @sudheesh001 

Is there a Gitter chatroom for ```loklak_server``` and ```loklak_webclient``` repo's.
