### ISSUE TITLE
Create a RESTful API for loklak apps.

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#382]
This API will be a part of the oauth-proxy code.

The required routes are:

1. GET /:user/:app/ (list)
2. GET /:user/:app/:id (read one)
3. POST /:user/:app/ (create)
4. PUT /:user/:app/:id (update)
5. DELETE /:user/:app/:id (delete)

Once these routes are added, it will be easy to add authentication as middleware. Also, these routes can be used by any loklak app. Currently, only the "wall" app will use this.

**Comment by sudheesh001** [comment]
For moving towards IoT, we also need to have the following
1. GET /:user/tweets
2. GET /:user/:tweet/:id
3. POST /:user/:app/:tweet
4. POST /:user/:app/:tweet/:media
5. DELETE /:user/:app/:id

What do we do for IoT devices, do they need to have a twitter account ? There should be a way to save the tweets from these devices from an app for the device.

**Comment by aneeshd16** [comment]
The CREATE route (POST /:user/:app/) accepts JSON in the body, creates a unique id using the npm package shortid https://www.npmjs.com/package/shortid.
