### ISSUE TITLE
Refactor search.js

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#383]
This controller has almost 500 lines of code.  
https://github.com/loklak/loklak_webclient/blob/master/app/js/controllers/search.js  
A lot of the method can be shared between other controllers/services. Things to do
- [x] Separate those mutal methods to services, comment here about new services
- [x] Refactor length of methods
- [x] Similar refactoring for advanced search as well

**Comment by mariobehling** [comment]
@fuksi Are you planning to finish this until tomorrow for M3?

**Comment by fuksi** [comment]
Yes, main tuning for search.js is done. I'll do the same with advanced search as well, but the process will be quicker. It will be done before M3 :)

**Comment by fuksi** [comment]
All map creation related method are moved to MapCreationService

**Comment by mariobehling** [comment]
> MapCreationService

What issue?

**Comment by fuksi** [comment]
That is just a separation of code in angular. I had similar methods for creating map, both used in search & advanced search, so it seemed logical to separate the the code in a service. As I take on the /map view, I'll be using this service as well. The service's name along with its code comment are very clear, so I don't think an issue to inform this is necessary. 

https://github.com/loklak/loklak_webclient/blob/master/app/js/services/mapcreation.js
