### ISSUE TITLE
Markdown tweet attachment tracker

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#388]
- [x] Be able to post the attachment text to loklak, retrieve markdown and attach to twitter
- [x] Allow tweet to be sent along with markdown content attachment.

Quoting @Orbiter 

>For the large-text attachment, I suggest to use http://lab.lepture.com/editor/ https://github.com/lepture/editor for the markdown. Thats easy and compatible to the markdown used here in github.

This is how I am looking forward to solve this.

1. There should be an option similar to in emails to attach a large text attachment 
2. Clicking on this extends the current tweet box and shows up the text editor space where the attachment content should be available.
3. Then the user hits the tweet button and the content is then shared with twitter along with the tweet and the image version of the large text markdown content rendered by the server

**Comment by mariobehling** [comment]
There are relevant comments here https://github.com/loklak/loklak_webclient/issues/97#issuecomment-106980363
Please consider: 
* Markdown text is an attachment - this means the twitter text itself does not offer markdown capabilities. 
* There needs to be a separate text field for markdown text below similar to emails with a) Tweet text and b) click "Markdown" and get a field below, where people can enter more text
* The markdown text shows up as text in loklak, but in twitter it shows up as an image. Therefore when cross posting loklak needs to generate an image

**Comment by sudheesh001** [comment]
Markdown can successfully be attached but the server stub of markdown needs enhancements which are listed as follows in the issues
https://github.com/loklak/loklak_server/issues/106 Markdown stub enhancements
https://github.com/loklak/loklak_server/issues/102 Highlighting code segments when sent as markdown attachments

Cross posting is being separately discussed on https://github.com/loklak/loklak_webclient/issues/437
