### ISSUE TITLE
List of possible editors that can easily be configured with npm

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#389]
>For the large-text attachment, I suggest to use http://lab.lepture.com/editor/ https://github.com/lepture/editor for the markdown. Thats easy and compatible to the markdown used here in github.
Or maybe https://github.com/jbt/markdown-editor ? Or, if possible, let the user choose which editor he wants to use.

Tracking for #388

**Comment by mariobehling** [comment]
What is the goal of this issue? This question is already covered in two other issues. Please show us some code instead of opening tons of issues. Relevant issues: https://github.com/loklak/loklak_webclient/issues/97 and https://github.com/loklak/loklak_webclient/issues/388 Please follow up there.
