### ISSUE TITLE
How can we support different languages a) in the interface and b) for tweets

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#39]
Also think of services like Weibo in China, which we want to support. Any services in your region apart from twitter? Please let us know and we could have a chet how to support them as well.

**Comment by Orbiter** [comment]
This is actually two challenges:
- how to integrate different message services (i.e. Weibo)
- how to handle different languages (i.e. translate them automatically)

the first challenge can be realized in the loklakserver: add another scraper. The data structures in loklak are prepared to handle different sources (including 'self': messages generated within loklak)

The second challenge is difficult and requires the presence of a translation service. Who knows a system that can be plugged-in in directly in the browser?

**Comment by mariobehling** [comment]
@sudheesh001 What are your ideas here?

**Comment by mariobehling** [comment]
I have some interest from friends in Asia who would like to add Loklak as an additional service to their web services. We need a strategy for loklak localization. Please provide more input.

**Comment by aneeshd16** [comment]
Does localization here refer to just the language of the loklak frontend, or also translation of tweets?

**Comment by sudheesh001** [comment]
If only the front end has to be translated, what we could do is to have a seperates `locales` file where each of the string is present, we can then replace the string based on the browser default language of the user.

Tweeting in a particular language (support of unicode) I guess shouldn't be a problem if the tweets can be stored with the loklak_server and posted to twitter. When it comes to automatic translation of the tweets, we need to look into the services google apis might offer. I had previously worked with angularjs application for automatic translation to a few languages using the google translate API but it seems to be nonfunctional now. Its present at @sudheesh001/AngularJSTranslate but I need a little more time to check what could be done in that case, there's no free API to do that yet and considering the paid ones, I have no clue of how reliable they are.

**Comment by julianfox** [comment]
For angular localization, the best is to use https://github.com/angular-translate/angular-translate, about the fact to create a automatic translation of tweets that sound weird...

**Comment by mariobehling** [comment]
@julianfox If Angular translate covers the translation of all frontend components, it sounds good to me.

**Comment by fuksi** [comment]
I went through the first video of the [angular-translate]( https://github.com/angular-translate/angular-translate) and I don't think it's going to cover anything. Like many other multi-lang plugins, it can provide us only the services and interfaces, for us to input our translation, and then the translations are labor work.

Implementation example (although it's recommended to use a json containing table of translations):

```javascript
app.config([$translateProvider', function($translateProvider) {
   $translateProvider.translation('fi', {
     "APP_TITILE": "Loklak hajautettu tweet hakupalvelin"
    ....
```

**Comment by mariobehling** [comment]
Ok, just to clarify: My main question is the support of the interface language and the possibility to insert tweets in different languages. Regarding the translation of tweets - this is not my main concern or focus currently. Although it sounds interesting. So, if we can change the interface language, that is already great. Thank you!

**Comment by Orbiter** [comment]
> My main question is the support of the interface language and the possibility to insert tweets in different languages.

the loklak_server uses UTF-8 for tweets everywhere and alternative charsets are supported, so that should not be an issue

> Regarding the translation of tweets - this is not my main concern or focus currently. Although it sounds interesting. So, if we can change the interface language, that is already great. Thank you!

**Comment by sudheesh001** [comment]
I think its possible to translate and have the i18n using angular translate for all the strings that are present in the application interface.

**Comment by sudheesh001** [comment]
As far as I see it, its best to have a seperate locales file and its internal files as follows
```
- app
- build
- gulp
- locales \
        - en.json
        - fr.json
        - de.json
        - hi-IN.json
        - es.json
        - .....
- nodemodules
- server
- test
```
As newer files are added, using the file system `fs` of nodejs we can get all the names of modules by getting the list of files and stripping the `.json` and all the contents in them being ` key - value ` pair will just be binded to the front end. It can directly be served from the server itself in that language if the language of the browser is set or we can serve an En-US version and put a small drop down somewhere in the top-nav bar for a different language.
