### ISSUE TITLE
Links with the # character are not correctly parsed

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#391]
Example:
Original tweet: https://twitter.com/Gaydio/status/625234239055896576
Tweet on loklak: http://test.loklak.net/tweet?q=id:625234239055896576

![image](https://cloud.githubusercontent.com/assets/5436027/8893570/d512ac3a-33b2-11e5-9f19-c67357ea1f36.png)

Example 2
Original: https://twitter.com/MysteryOf7Seals/status/625266875153264640
Loklak: http://test.loklak.net/tweet?q=id:625262449567010817

**Comment by sudheesh001** [comment]
I don't think it's the link filter over here. The regex in the link filter
`/(https?:\/\/[^\s]+)/g` can successfully retrieve URLs which have a masked `#` present in them like `https://something.com/apple#apple`

**Comment by aneeshd16** [comment]
What if the url is `https://something.com/apple#`?

**Comment by sudheesh001** [comment]
Still seems to work, https://regex101.com/#javascript

**Comment by aneeshd16** [comment]
Okay, it does. What else could be the problem?

**Comment by sudheesh001** [comment]
In this, it looks like the mentions filter http://test.loklak.net/tweet?q=id:625262449567010817 and here http://test.loklak.net/tweet?q=id:625234239055896576 looks like the link. this is strange.

**Comment by sudheesh001** [comment]
No issues found with the regexes. Please reopen in case these similar filter issues are encountered.
