### ISSUE TITLE
Attach multiple images while uploading to twitter

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#395]
Multiple image attachments can be seen but they do not get uploaded that way.

> Multiple images that need to be uploaded. The hellojs API has its limitation because of which only one file can be uploaded at a time and not multiple files, the code supports upto 4 to be uploaded but if all 4 images have to be uploaded, it can upload them as 4 different tweets instead.

**Comment by mariobehling** [comment]
This is already covered in https://github.com/loklak/loklak_webclient/issues/95

I am not sure, why you need to create an issue again to cover something that is already covered. Less issues and more code and tests would be great.

Such things should be taken care of when you develop the feature. This is part of the normal testing procedure. Please follow up on detailed tests here https://github.com/loklak/loklak_webclient/issues/95
