### ISSUE TITLE
Reverse geocode the tweet location and show it from the lat, long coordiantes

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#396]
With reference to https://github.com/loklak/loklak_webclient/issues/355#issuecomment-124848940

**Comment by mariobehling** [comment]
It might be interesting to have this feature, but it is not what the comment in #355 is all about. The goal of issue #355 is to get an embedded map to show up as an attachment below the tweet, which the user can also change.

**Comment by sudheesh001** [comment]
Fixed via https://github.com/loklak/loklak_webclient/pull/402
