### ISSUE TITLE
A topology view

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#399]
Instead of creating a new view for searching followers, followings, we can create instead a random user's view, just like twitter: https://twitter.com/loklak_messages, except we can choose to provides all information in one page.

![image](https://cloud.githubusercontent.com/assets/6878677/8927168/367613ce-351e-11e5-8f08-8cbcda42b2c8.png)

- Center: tweets from that user, provided by search servlet
- Left: instead of photos and videos, show a list of followers
- Right: instead of suggesting who to follow & # trends: show a list of followings

**OR**

We can just do it exactly like twitter, provide different tabs for tweets, following, followers, and favorites ( if available)

![image](https://cloud.githubusercontent.com/assets/6878677/8927221/8cab8e18-351e-11e5-8399-e97cdd6bedec.png)

**Comment by mariobehling** [comment]
Yes, this is a good idea, but this feature integrates loklak even more with twitter. We need to consider to develop loklak into a more independent service. Offering features that twitter does not have is a good way to do this. So, please focus on the search view of followers and followings of a user first.

**Comment by fuksi** [comment]
This is overlapped with https://github.com/loklak/loklak_webclient/issues/411
