### ISSUE TITLE
OAuth Shim fails to work behind a browser on a proxy network 

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#404]
If the user is behind a proxy and setting up the loklak webclient, the oauth-shim fails with the error
```
This webpage is not available

ERR_CONNECTION_REFUSED
```
at the URL during sign in
 `http://localhost:3002/oauthproxy?client_id=...........oauth_proxy%22%3A%22http%3A%2F%2Flocalhost%3A3002%2Foauthproxy%22%7D`

At the same time, when a tweet is posted, it hits a 502 Bad Gateway error. I couldn't find any document for how to make this proxy run when on an actual proxy network. Any clues ?

**Comment by mariobehling** [comment]
Closed due to inactivity. Reopen if needed.
