### ISSUE TITLE
Attach Activity Bar to the right side of the screen, get rid of bottom space, enable reload of tweets on bottom scroll

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#406]
Please 
* [ ] attach activity bar on right hand side
* [ ] use bottom of the screen
* [ ] enable reload functionality on bottom scroll

![screenshot from 2015-07-30 16 43 32](https://cloud.githubusercontent.com/assets/1583873/8986097/d75621f4-36da-11e5-9ba7-e13be1f294b1.png)

**Comment by fuksi** [comment]
Done with #415
