### ISSUE TITLE
Test all Walls in different resolutions

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#407]
Please create a table for each display with different resolutions that you have tested and a screenshot of the test walls.

![img_20150730_202653](https://cloud.githubusercontent.com/assets/1583873/8991660/50dc7edc-36fa-11e5-9c99-5f4fa3aa3599.jpg)

**Comment by aneeshd16** [comment]
@mariobehling, will do.
However, the card layout is buggy, and I wouldn't recommend using it as of now.
