### ISSUE TITLE
Process authorized request to account servlet through Oauth Proxy

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#408]
For now we only have the use case of request to `account.json`, but let's make a foundation between modules so that we can add more cases in the future.

Based on what a request is authorized:
- user session's `oauth_token`
- user session's `oauth_token_secret`
(I choose these because these are the fields that, currently, saved for each user, `clien_id` doesn't seem to be there)

Implementation: 

**From the web client** : a new search service will be created, where request to oauth proxy are defined. Included in request GET params are
- `oauth_token`
- `oauth_token_secret`
- `screen_name` 
- `servlet`
- & other related args, depends on the servlet option

E.g. `http://localhost:3002/authorized?oauth_token=12345&oauth_token_secret=54321&servlet=account.json&screen_name=foo`

**From the oauth proxy** : api will listen to the according path, i.e. `/authorized?`. When request from the client are made:
- the oauthproxy then will request to loklak account servlet, with `screen_name` from the client, to retrieve the tokens
- if matches, make request to the given `servlet`, along with the rest of the args (this is not needed in this case, since we're already got the result from account servlet from step 1, pass it right away)

**From the loklak server** : nothing changes, since oauth proxy will be making request from localhost to localhost.

**Comment by aneeshd16** [comment]
This is similar to what I was thinking, but instead of having a dedicated `/authorized` endpoint, we can have middleware called `isAuthorized` which can be used on other routes as well.

**Comment by Orbiter** [comment]
The loklak_server should (if authentication is made right) only return account information for users which are authentified. Since 'user is authentified' is check in the loklak_webclient, this information must be passed to the server as additional call parameter. To be able to access the access.json servlet, the request must come from oauth-proxy, but the oauth-proxy must send along also the information which user has initiated the communication.

This will enable the loklak_server to strengthen the security of the account.json servlet: access should not only be granted to localhost access but also only to one specific account which the oauth-proxy names as the authentified user.

**Comment by fuksi** [comment]
This is implemented. 
- The client can do authorized request to the oauth proxy with 4 params: `servlet`, `screen_name`, `oauth_token`, `oauth_token_secret`. Service code  https://github.com/loklak/loklak_webclient/blob/master/app/js/services/authorized-search.js
- The proxy will pass a request along to the according servlet, which is only `account.json` for now. Line 42-63 in https://github.com/loklak/loklak_webclient/blob/master/oauth-proxy/api.js

Currently account servlet is not processing the oauth_token nor secret and return the result anyway to the oauth proxy. @Orbiter you can implement the tokens checking when you can. If some parameter needs to be changed, please comment here.

**Comment by aneeshd16** [comment]
Suggestion, if we make this into a middleware, it can be used for other routes as well. For example, we define a function:
````
var isAuthorized = function(req, res, next) {
        if (/*condition to check if req has valid token and secret*/) {
            res.next();
        }
        else { res.end('Unauthorized'); }
    }
````
After that we can use this in any route.
For example, this is the handler for reading a wall object
````
//CREATE
router.post('/:user/:app', isAuthorized, function(req, res) {
    var newWall = req.body;
    getData(req.params.user, function(error, response, body) {
        var appData = JSON.parse(response.body).accounts[0].apps;
        if(!appData){
            appData = {};
        }
        if (!appData[req.params.app]) {
            appData[req.params.app] = [];
        }
        newWall.id = shortid.generate();
        appData[req.params.app].push(newWall);
        console.log(newWall.id);
        updateData(req.params.user, appData, function(error, response, body) {
            console.log(response.body);
            return res.json({
                id: newWall.id
            });
        });
    });
});````
All the wall routes require that the user be authorized. Currently, anyone can make direct requests to oauth-proxy which is a HUGE security hole. This patch is step in the right direction, but it doesn't look to be scalable. It will become useful once we start integrating payment systems. What do you think?

**Comment by fuksi** [comment]
@aneeshd16, good point. I can wrap the authorized process in a reusable method with a callback.

**Comment by fuksi** [comment]
Implemented, please checkout lines 45-85 for how to/ an example 
https://github.com/loklak/loklak_webclient/blob/master/oauth-proxy/api.js
