### ISSUE TITLE
Inspect/Reproduce error on live

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#413]
When open `/map` view on live, markers are not showing up, and the error in console log is
```error
Error: iconUrl not set in Icon options (see the docs).
    at a.Icon.a.Class.extend._createIcon (http://test.loklak.net/js/main.js:6:14854)
    at a.Icon.a.Class.extend.createIcon (http://test.loklak.net/js/main.js:6:14690)
    at a.Marker.a.Class.extend._initIcon (http://test.loklak.net/js/main.js:6:17599)
    at a.Marker.a.Class.extend.onAdd (http://test.loklak.net/js/main.js:6:16555)
    at L.Marker.include.onAdd (http://test.loklak.net/js/main.js:1:29816)
    at a.Map.a.Class.extend._layerAdd (http://test.loklak.net/js/main.js:5:31975)
    at a.Map.a.Class.extend.addLayer (http://test.loklak.net/js/main.js:5:23479)
    at a.Marker.a.Class.extend.addTo (http://test.loklak.net/js/main.js:6:16722)
    at http://test.loklak.net/js/main.js:13:15743
    at Array.forEach (native)
```
According the debugging instructions [link](https://github.com/Leaflet/Leaflet/issues/826), it is implemented the right way at lines 65-70: https://github.com/loklak/loklak_webclient/blob/master/app/js/services/mapcreation.js

I wasn't able to find the bug on live...yet. Meanwhile, it works fine at local, and remote http://gofullstack.me:3001/map ([the related PR](https://github.com/loklak/loklak_webclient/pull/401) was reviewed by multiple peers). 

@aneeshd16, @sudheesh001, @prasht63 can you try to run master at local and your remote server to see if the markers are showing on map & you're not getting the error?

**Comment by fuksi** [comment]
I was able to diagnose why markers are not showings on test.loklak.live. Somehow, at the end point, the problem is related from the result of the server. This is an example result from user servlet - a following.   
On TEST.LOKLAK.NET
```javascript
{
....
profile_image_url: "2838735506"
....
}
```

On my remote server & localhost
```javascript
{
....
profile_image_url_https : "https://pbs.twimg.com/profile_images/517920769402105856/n22C6FsD_normal.jpeg",
profile_image_url: "http://pbs.twimg.com/profile_images/517920769402105856/n22C6FsD_normal.jpeg"
....
}
```
Shortly about debugging the initial error (backward):
- ` iconUrl not set in Icon options` => Check the iconUrl value
- It is undefined => Check the resource value
- The field `profile_image_url_https` is not in the result from user servlet => Compare with local and other remotes
- It happens only on the TEST.LOKLAK.NET server. Also `profile_image_url` is not used at the moment.

@Orbiter: can you give me some more info about the number value? Should I write separate code for the live server? If you want to inspect the values, you can do some curl on the server, or I also created a global variable on live, which you can just go to the dev console of test.loklak.net and inspect the variable `topo`.

**Comment by Orbiter** [comment]
The live server should produce the same result as your test server, the live server code is identical to the code in git.

You should not write separate code!

If you see that the result from loklak.org is different from your own server, then this is strange. Please drop the url which you used to get this result.

**Comment by fuksi** [comment]
Actually you can test it straight from the browser, since user servlet is available without auth:
- Live http://loklak.org/api/user.json?callback=angular.callbacks._1&followers=500&following=500&screen_name=phucdn2005
- Same link for local:
[http://localhost:9000/api/user.json?callback=angular.callbacks._1&followers=500&following=500&screen_name=phucdn2005](http://localhost:9000/api/user.json?callback=angular.callbacks._1&followers=500&following=500&screen_name=phucdn2005)

You can see the difference quickly by searching for `profile_image_url`

**Comment by Orbiter** [comment]
I can reproduce this. That is really strange. I just checked if this `profile_image_url` is overwritten anywhere, but is not. I cannot see a cause why these results are different. Right now I can just suggest that you test if the value from `profile_image_url` starts with `htttp://` and if not, take the url from `profile_image_url_https`. I will continue looking for a cause, but right now I don't know.

**Comment by fuksi** [comment]
I actually used `profile_image_url_https`. The field wasn't there yesterday, hence the error. But now it's there so we're good to go now.
