### ISSUE TITLE
Attach Map to a Tweet

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#414]
Getting more into details based on https://github.com/loklak/loklak_webclient/issues/97

Goal of the attachments of a map is: To show a map anywhere in the world as an attachment below a tweet (similar to an image). Use cases are for example - the user wants to show a location of a meetup. Things to consider:
* [x] User clicks button "Attach Map"
* [x] An expand area opens with OpenStreetMap below the tweet. Here the user can zoom in/out and set a marker.
* [x] Now the user tweets and the system cross posts the tweet to twitter
* [x] As it is not possible to embed maps in twitter, the system generates and image and cross posts a map image attachment to twitter

**Comment by sudheesh001** [comment]
> An expand area opens with OpenStreetMap below the tweet. Here the user can zoom in/out and set a marker.

The last time I spoke @Orbiter wanted the location of the user to be tweeted instead of the user setting a location, the latitude and longitude are taken and plotted

**Comment by mariobehling** [comment]
You are mixing everything up and discussing this at the wrong place. What you are writing above is not relevant at all in this issue. It seems like you have not understood the goal at all.

**Comment by sudheesh001** [comment]
The goal is to send an attachment to twitter of a map. If this is the way that has to be done, it'll be done this way.

**Comment by mariobehling** [comment]
It is not "The Way" - this is one feature and you are talking about another feature. Repeat again "add location" and "attach map" are two different things.

**Comment by sudheesh001** [comment]
Fixed via https://github.com/loklak/loklak_webclient/pull/402
