### ISSUE TITLE
Display of excluded accounts in wall

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#416]
Accounts in the wall are shown despite the fact that they are excluded. See atomsoffice here.
![screenshot from 2015-08-02 13 17 26](https://cloud.githubusercontent.com/assets/1583873/9025898/ddd88270-3918-11e5-8947-956a46e8cc5d.png)

![screenshot from 2015-08-02 13 15 48](https://cloud.githubusercontent.com/assets/1583873/9025896/c8ee376a-3918-11e5-9b25-338290d7721a.png)

**Comment by aneeshd16** [comment]
@mariobehling Could you please share the URL of the wall so that I can debug this?

**Comment by mariobehling** [comment]
URL of the wall: http://test.loklak.net/mariobehling/wall/EyEPDywq

**Comment by aneeshd16** [comment]
Thanks.
@Orbiter the query that is being made is http://loklak.org/api/search.json?callback=angular.callbacks._0&q=%23netzpolitik+-from:atomsoffice+-from:SEOanders+since:2015-07-01_05:30+until:2015-09-01_00:30 (I removed the `count` parameter for checking). Is this the right way to make this query?

**Comment by Orbiter** [comment]
yes, thats right!
(Detail: excluding A and B for a Query X has the logic "X AND -(A OR B)" which is equal to "X AND -A AND -B")

**Comment by aneeshd16** [comment]
But according to the query, tweets from `atomsoffice` should be excluded, but they still appear in the results.

**Comment by aneeshd16** [comment]
@Orbiter bump

**Comment by Orbiter** [comment]
this is a bug in the query parser of loklak_server. It is currently only able to include one from-modifier, not two. I am fixing this.

**Comment by Orbiter** [comment]
fix is up!

**Comment by aneeshd16** [comment]
@mariobehling Please check, this should be fixed. No change was required client side.

**Comment by mariobehling** [comment]
Great! Thanks a lot.
