### ISSUE TITLE
Implement Cycle/Repeat tweets in wall

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#418]
If cycle is activated please give options 
* [ ] cycle delay time
* [ ] cycle post limit

![screenshot from 2015-08-02 23 30 19](https://cloud.githubusercontent.com/assets/1583873/9028132/9aade3c2-396e-11e5-864d-095e6c074349.png)

* [ ] If cycle is deactivated do not show options
![screenshot from 2015-08-02 23 30 05](https://cloud.githubusercontent.com/assets/1583873/9028141/c5ce3606-396e-11e5-974d-8b354cd62ed4.png)

**Comment by aneeshd16** [comment]
Duplicated issue, added comments to #377
