### ISSUE TITLE
Display spinner icon in waiting state.

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_webclient#419]
I think we lack a spinner icon similar to twitter when loading heavy services. In loading state, the middle-top twitter bird turns into a spinner (unable to make a screenshot since it disappears too quickly..).

 The aim is to implement the spinner icon as a reusable angular service, with simple interface. All controllers could then call the service like this : 

```javascript
SpinnerService.start();
SpinnerService.stop();
```

**Comment by aneeshd16** [comment]
@zyzo, http://chieffancypants.github.io/angular-loading-bar/ has already been integrated! The spinner automatically activated when an Ajax request was made. Currently, it's hidden as the white spinner wasn't visible with our white top bar. Check out https://github.com/loklak/loklak_webclient/blob/master/app/js/routes.js#L89-L90

**Comment by zyzo** [comment]
Nice. That's a way better solution. Could you help activating it ?

**Comment by aneeshd16** [comment]
Yep, just set those values to true. https://github.com/loklak/loklak_webclient/blob/master/app/js/routes.js#L89-L90

Only problem is, both the spinner and the bar are white in colour, so you might want to change their css to a different colour to make them visible against our white topbar.

**Comment by mariobehling** [comment]
Any update on this? M3.5 is tomorrow.
