### ISSUE TITLE
Adjust all blue colors to match "tweet" button of start page

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#420]
It looks like there are different blue colors implement across the site. Please adjust all blue colors and fonts to match the tweet button in the connect area.

![screenshot from 2015-08-03 10 25 18](https://cloud.githubusercontent.com/assets/1583873/9033722/2ea9c6a8-39ca-11e5-8ae6-5233213da1cd.png)

**Comment by sudheesh001** [comment]
For simplifying the work, the color is #55acee
I hope that helps @zyzo

**Comment by aneeshd16** [comment]
Is it okay if we override the style for `btn-primary` with our colour (`#55acee`)

**Comment by mariobehling** [comment]
Which CSS is the btn-primary? Where did it come from? If this is a css that we make, please override. If this is something we take from another source, please check what other solution we have, e.g. a seperate CSS we can all follow.

**Comment by aneeshd16** [comment]
btn-primary is from bootstrap's CSS. True, we can override that, or create a custom class `btn-custombutton` which we apply to all our buttons. The advantage in overriding `btn-primary` is that no changes would have to be done in our views, all blue buttons will be changed to  `#55acee` with a 1-line change in our CSS file.

**Comment by mariobehling** [comment]
With override, you mean change bootstrap CSS, right? With the next update of bootstrap we have to change that again. Please use for all custom styles a separate CSS that stores our styles. Please reuse these custom styles across the site.

**Comment by zyzo** [comment]
@aneeshd16 I think it is best to create a new custom class to make it easy to change & customize later. It shouldn't take too much time to do so.

**Comment by zyzo** [comment]
About the name, I'm thinking `btn-loklak-blue`. Please go ahead if you have any other suggestion.

**Comment by aneeshd16** [comment]
`btn-loklak-blue` sounds good. :)

**Comment by zyzo** [comment]
Fixed in #427
