### ISSUE TITLE
Implement Activity Sidebar on Map Page as "Push Transition"

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#421]
An example how the "push" transition effect can work is here: http://tympanus.net/Development/SidebarTransitions/

Use an arrow on the top to push in/out.

![screenshot from 2015-08-03 11 31 13](https://cloud.githubusercontent.com/assets/1583873/9035009/71fa300a-39d4-11e5-9315-1450c76921cf.png)

**Comment by fuksi** [comment]
Added in #435
