### ISSUE TITLE
Show number of followers/following and number of followers/following on the map

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#422]
Currently the number of followers is shown on the map. Some followers do not have a location. Please distinguish between all followers/following and those shown on the map, e.g. Followers 1330/723 (i)

![screenshot from 2015-08-03 11 59 32](https://cloud.githubusercontent.com/assets/1583873/9035444/17ce49f0-39d8-11e5-9e6b-656c385777cd.png)

* [x] The first number is slightly less strong and shows the number of all followers/following e.g. "1330"
* [x] The second number shows the actual followers on the map with a location e.g. "723"
* [x] Clicking on an "i" in a circle shows a small info "The first number shows the actual followers. The second number shows the number of followers with a location info. These are displayed on the map."
* [x] Add the twitter "t" in front of the text in each line
![45778-31wgfk1428250201](https://cloud.githubusercontent.com/assets/1583873/9035485/8315cea4-39d8-11e5-9153-e8d343582fee.png)

**Comment by fuksi** [comment]
Instead of click on (i), the hint will show/hide on hover in/hover out. I think it's more UX friendly.

**Comment by fuksi** [comment]
Added in #435
