### ISSUE TITLE
turn off browser built-in autocomplete for input field which are supported by loklak autocompletes

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#425]
With https://github.com/loklak/loklak_webclient/issues/162 autocomplete was implemented which is working fine. However, my firefox browser suggests input values on it's own which causes an overlay of both suggestions. The browser suggestions partly overlays the loklak suggestions and makes them unavailable.
<img width="605" alt="doublesuggestions" src="https://cloud.githubusercontent.com/assets/238730/9037169/c66e8ce4-39e8-11e5-85f8-43949fccf562.png">

What we must do here is to prevent the browser built-in suggestions.
This can be done with `autocomplete="off"` like in `<input name="q" type="text" autocomplete="off"/>`.
I don't know how this influences your custom autocomplete. Please test.

**Comment by fuksi** [comment]
I don't see it's happening in my browsers. Added patch anyway  #435
