### ISSUE TITLE
Implement embed contents in home view like in search

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#428]
The implementation might be different from search view since the data are from Twitter API, not loklak, so
- Try to abstract the implementation so that when data source changes, the mark up doesn't
- Find the mininum number of tweets to show at init for a faster experience

**Comment by mariobehling** [comment]
The goal is to generate the same view as in search with the same technology.

**Comment by fuksi** [comment]
We're not getting as much content from HelloJs comparing to Loklak. However the results are still very positive. Please open this again if there is new support from the server & a need for enhancement.
