### ISSUE TITLE
Map Layout in Wall

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#431]
Requirements:
* [ ] Accept a city/place in the wall creation phase
* [ ] Make a UI for setting a bounding box to restrict tweets within a particular area
* [x] Add the `/location` parameter when doing a search when the map layout is selected
* [x] Proposed Strategy: Load 10 tweets (pins) at every `refreshTime` (`refreshTime` is calculated in the usual way). Pins start dropping and accumulating on the map. Once the total number of pins on the map reaches 50, clear the least recent 10 pins from the map. Numbers are configurable, will need to test what works best.
* [x] Every fixed interval of time, use a round-robin strategy to popup those pins one by one. However, when new tweets come, popup the new tweets first, and then get back to the old ones.

**Comment by mariobehling** [comment]
Great sum up!

**Comment by aneeshd16** [comment]
Map prototype: http://aneesh-ojl02abl.cloudapp.net/aneeshd16/wall/VJRDSK_c
The map automatically pans so that the marker and the popup are in the center. If this is okay, I will proceed with this, otherwise I can revert back to the old static map.

**Comment by mariobehling** [comment]
Very nice. At the moment looks like the arrow points are not all displayed yet and seem a bit off location.

Please also use complete available screen area. (see screenshot in red.)
![screenshot from 2015-08-08 14 16 18](https://cloud.githubusercontent.com/assets/1583873/9150422/4dcd3f3a-3dd8-11e5-846f-e14523de8f16.png)

**Comment by mariobehling** [comment]
The account maps show a picture of the account instead of a marker. I think that is pretty nice. 

![screenshot from 2015-08-08 14 33 21](https://cloud.githubusercontent.com/assets/1583873/9150479/98a05b30-3dda-11e5-82e5-43c1487dd7e6.png)

**Comment by aneeshd16** [comment]
Done, http://aneesh-ojl02abl.cloudapp.net/aneeshd16/wall/VJRDSK_c

A lot of markers are around the same area, so some of those are hidden by the marker that is in the front. I want to bring that marker to the front when the popup is opened. @fuksi @prasht63 Any ideas?
Link: http://aneesh-ojl02abl.cloudapp.net/aneeshd16/wall/4JnIHY_5

**Comment by aneeshd16** [comment]
Number of tweets to be displayed at a time has been set to 20. Whenever, the total number crosses 20, the least recent tweet is deleted.

**Comment by aneeshd16** [comment]
When the map is dragged/panned/moved/etc the coordinates of the center and the zoom level is added to the URL. This URL can now be shared, and when this wall-map opens, it takes the values from the URL. Use case: Person creates a wall-map for cccamp15, sets "Cycle tweets" to "No" and pans and zooms the map so the desired map is shown. Now, the person can directly share the URL and the center coordinates and zoom level will be preserved. However, this new state is not saved as a part of the wall object. 
Example: http://aneesh-ojl02abl.cloudapp.net/aneeshd16/wall/VJRDSK_c?lat=50.49246334187725&lng=9.73388671875&zoom=6
