### ISSUE TITLE
If the search input box has no focus (cursor not in box) then do not show suggestions

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#432]
currently, if a search was done, there is no focus on the search box (which is correct), the search result page is shown (correct) but search suggestions are showed below the search box and this overlaps with the search result, see example:
![suggestionsoverlap](https://cloud.githubusercontent.com/assets/238730/9082850/f0b9c85e-3b66-11e5-905b-d13edf87d6cd.PNG)

Please do not show the suggestions if there is no focus on the search input box

**Comment by fuksi** [comment]
This is now can be checked on live.
