### ISSUE TITLE
Cross-Posting Message Format Description

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#437]
This is a general description for all cross-posting requirements as mentioned in https://github.com/loklak/loklak_webclient/issues/355 https://github.com/loklak/loklak_webclient/issues/97 https://github.com/loklak/loklak_webclient/issues/94 https://github.com/loklak/loklak_webclient/issues/63

This feature is supported by the push api as described in http://loklak.org/api.html#push and with the new `canonical_id` field which is implemented in https://github.com/loklak/loklak_server/issues/54

To cross-post a message to Twitter AND Loklak, the message shall first be posted to Twitter, then a Message-ID is received from Twitter and using this information the same message shall be posted to loklak as well. The Message-ID from twitter is used to connect the both messages in loklak and inserted into the field `canonical_id`.

We consider different types of messages:
- (1) simple messages without rich content
- (2) messages with attached locations (map coordinates)
- (3) messages with attached high-resolution media (images)

For simple cross-posts, the following example data must be pushed to http://loklak.org/api.html#push
```
{
    "created_at" : "2015-03-03T19:30:43.000Z",
    "screen_name" : "exanonym77s",
    "text" : "check #DoctorWho forums #TheDayOfTheDoctor #TheMaster @0rb1t3r http://www.thedoctorwhoforum.com/ https://pic.twitter.com/FvW6J9WMCw",
    "canonical_id" : "572841550834737152",
    "source_type" : "TWITTER"
  }
```
all other fields will be added automatically in the loklak_server. This works only if the `screen_name` is known in the loklak_server which should be the case if the user is logged in. In that case, all account data is present and there is no need to attach it again in the message.

Please implement this as a first step. The cases (2) and (3) will be added with more detail description in this feature as the first case had been implemented.

**Comment by Orbiter** [comment]
Please note that `created_at` value submitted to the push api should be identical to the date of the twitter-message, not just the current date.
Please also note that I removed the `provider_type` field, this will be set automatically. You don't need to submit it, it will be overwritten.

**Comment by sudheesh001** [comment]
@Orbiter For a tweet this is the response I can provide after posting to twitter, what are the fields you'd need here ? Is there anything other than 
```json
{
"created_at": "Sun Aug 09 05:33:46 +0000 2015",
"screen_name" : "//retrieve from "user"."screen_name" of the response json",
"text" : ".....",
"canonical_id": being the "id_str" eg. "630250595308322816",
"source_type": "twitter"
}
```
I also noticed that the `created_at` value needs a response like `2015-03-03T19:30:43.000Z`, Can the server also handle the response as `Sun Aug 09 05:33:46 +0000 2015`
```json
{
  "created_at": "Sun Aug 09 05:33:46 +0000 2015",
  "id": 6.3025059530832e+17,
  "id_str": "630250595308322816",
  "text": "Cross posting tweet response test, packing into #loklak",
  "source": "<a href=\"http:\/\/loklak.net\/\" rel=\"nofollow\">Loklak<\/a>",
  "truncated": false,
  "in_reply_to_status_id": null,
  "in_reply_to_status_id_str": null,
  "in_reply_to_user_id": null,
  "in_reply_to_user_id_str": null,
  "in_reply_to_screen_name": null,
  "user": {
    "id": 390171807,
    "id_str": "390171807",
    "name": "SudheeshSinganamalla",
    "screen_name": "sudheesh001",
    "location": "Hyderabad",
    "description": "CEO and Founder Pixanor Inc., Google Summer of Code, FOSSASIA, Researcher, Hacker and Entrepreneur",
    "url": "http:\/\/t.co\/PPagAzO0lR",
    "entities": {
      "url": {
        "urls": [
          {
            "url": "http:\/\/t.co\/PPagAzO0lR",
            "expanded_url": "http:\/\/www.pixanor.com",
            "display_url": "pixanor.com",
            "indices": [
              0,
              22
            ]
          }
        ]
      },
      "description": {
        "urls": [
          
        ]
      }
    },
    "protected": false,
    "followers_count": 210,
    "friends_count": 204,
    "listed_count": 23,
    "created_at": "Thu Oct 13 15:35:51 +0000 2011",
    "favourites_count": 46,
    "utc_offset": 19800,
    "time_zone": "Chennai",
    "geo_enabled": true,
    "verified": false,
    "statuses_count": 944,
    "lang": "en",
    "contributors_enabled": false,
    "is_translator": false,
    "is_translation_enabled": false,
    "profile_background_color": "352726",
    "profile_background_image_url": "http:\/\/abs.twimg.com\/images\/themes\/theme5\/bg.gif",
    "profile_background_image_url_https": "https:\/\/abs.twimg.com\/images\/themes\/theme5\/bg.gif",
    "profile_background_tile": false,
    "profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/500559201542762498\/IvDEqWy1_normal.jpeg",
    "profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/500559201542762498\/IvDEqWy1_normal.jpeg",
    "profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/390171807\/1436768268",
    "profile_link_color": "3B94D9",
    "profile_sidebar_border_color": "C0DEED",
    "profile_sidebar_fill_color": "DDEEF6",
    "profile_text_color": "333333",
    "profile_use_background_image": false,
    "has_extended_profile": false,
    "default_profile": false,
    "default_profile_image": false,
    "following": false,
    "follow_request_sent": false,
    "notifications": false
  },
  "geo": null,
  "coordinates": null,
  "place": null,
  "contributors": null,
  "is_quote_status": false,
  "retweet_count": 0,
  "favorite_count": 0,
  "entities": {
    "hashtags": [
      {
        "text": "loklak",
        "indices": [
          48,
          55
        ]
      }
    ],
    "symbols": [
      
    ],
    "user_mentions": [
      
    ],
    "urls": [
      
    ]
  },
  "favorited": false,
  "retweeted": false,
  "lang": "en"
}
```

**Comment by sudheesh001** [comment]
- [x] Cross posting simple content complete
