### ISSUE TITLE
Make number of Top-Twitterers and Top-Hashtags configurable

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#442]
If we start a wall with statistics, then we see exactly three top twitterers and three top hashtags in the right column. I believe this is not enough and there is also space left!

<img width="1336" alt="more-top-on-wall" src="https://cloud.githubusercontent.com/assets/238730/9155228/480b823a-3eb1-11e5-9e44-1828ff6327f7.png">

Because we don't know how much more would fit there, it would be nice to have a configuration option for the maximum number of those top-values.
Please
- add a configuration value in the wall definition
- render the new configured maximum number of top-values

**Comment by mariobehling** [comment]
Maybe the simplest option for now, increase the value to 6 (like in tweetwall). Making the number configurable we need to look at the UI of the wall editor as well.

**Comment by aneeshd16** [comment]
duplicate issue #436
