### ISSUE TITLE
Add and view data sets

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#447]
Follow up issue to https://github.com/loklak/loklak_webclient/pull/394#issuecomment-129701455 and https://github.com/loklak/loklak_server/pull/83#issuecomment-124116874

Regarding Login to add and view messages
> The constraint must login before adding connection is not implemented yet therefore the list displaying is also the full list without authentication. But implementing the contraint also raises a concern : how the server knows that a client is authenticated ? More in loklak/loklak_server#83 (comment)

Users already need to authenticate for a number of functions. Please follow this implementation.

> But I think it's best to identify an import profile by its url and importer (screen_name) <source_url>-<screen_name>. The problem is, the user is not required to authenticate to twitter, to be able to push messages. This should be the default behaviour. 

The user needs to login to loklak (at the moment through twitter) in order to add and view his own data sources, but he should be able to make "view" public.

Several users can add the same data source and in some views (e.g. map) there should be a way to display "this data has been shared by x number of people". Therefore <source_url>-<screen_name> probably is not the best option. What suggestions do you have to implement this in way that works with the requirements?

**Comment by zyzo** [comment]
> The user need to login to loklak (at the moment through twitter) in order to add and view his own data sources, but he should be able to make "view" public.

By this do you mean that the user can make their imported data public or private (can or cannot be seen by other users) ? My suggestion is, for the sake of simplicity, any imported data can be seen by any user. 

> Several users can add the same data source and in some views (e.g. map) there should be a way to display "this data has been shared by x number of people". Therefore - probably is not the best option. What suggestions do you have to implement this in way that works with the requirements?

Currently when a message is pushed to loklak, 2 things are saved : the message itself, and an Import Profile, which contains several info about the push : message id, owner user, creation time, harvesting frequency, etc.. So by saving two import profiles that "point" to the same message, and have different owner users, the following requirement is automatically achieved.

**Comment by mariobehling** [comment]
> any imported data can be seen by any user. 

Sounds ok for now.

> So by saving two import profiles that "point" to the same message, and have different owner users, the following requirement is automatically achieved. 

How about achieving "this data has been shared by x number of people"? Do you know how to do this?

**Comment by zyzo** [comment]
> But implementing the contraint also raises a concern : how the server knows that a client is authenticated ?

This is a concern I raised in #394, that will be cleared out, if we accept the proposition that any imported data can be seen by any user. Therefore there's no need for server to verify that the client is logged in as what https://github.com/loklak/loklak_webclient/issues/408 is dealing with.

**Comment by mariobehling** [comment]
Well, we ultimately need this feature. Think of private data that users want to see on their map, but do not want to change publicly. Any current development should already ensure, that this "privacy feature" can be added.

**Comment by mariobehling** [comment]
Regarding offering users "add and share this data to your account": Do you know how to do this? This would also mean, that users would have the option of adding a certain data set to their own account as well. Again this is similar to "like" on FB. "Add and share on your account".

**Comment by mariobehling** [comment]
Look, e.g. we also want to add "address books" and connect to Linkedin Apis in the connect area. Of course this has to be private. Authentication is already implemented. Please talk to fuksi about it, if needed.

**Comment by zyzo** [comment]
> How about achieving "this data has been shared by x number of people"? Do you know how to do this?

It is possible, by searching for import profiles that points to that data, and retrieve the user from each profile. But that does sound like an overkill. An obvious solution is to save the list of shared users as message field.

> Well, we ultimately need this feature. Think of private data that users want to see on their map, but do not want to change publicly. Any current development should already ensure, that this "privacy feature" can be added.

Yes, implement private data just requires that the server is able to check if and which user is authenticated. @fuksi could you provide inputs on how we can achieve this ?

> Regarding offering users "add and share this data to your account": Do you know how to do this? This would also mean, that users would have the option of adding a certain data set to their own account as well

Sure. Until now I think users can share a message because they add the same url. That is different from users "sharing"/"retweeting" others users message. I will put more thought on how this can be achieved.

**Comment by mariobehling** [comment]
> It is possible, by searching for import profiles that points to that data, and retrieve the user from each profile. But that does sound like an overkill. An obvious solution is to save the list of shared users as message field.

I discussed this with @Orbiter already some time ago. Please follow up with him in chat. I think there are lots of small questions, that you could clear out that way.

> Yes, implement private data just requires that the server is able to check if and which user is authenticated. 

This has also been discussed in a number of issues. Please use the github search function and chat to @fuksi. He already asked you in chat today about this. Unfortunately there was not a reaction from your side. Please add the concluding info here.

**Comment by mariobehling** [comment]
>> Regarding offering users "add and share this data to your account"

> I will put more thought on how this can be achieved.

Relevant here: https://github.com/loklak/loklak_webclient/issues/449

**Comment by zyzo** [comment]
Privacy option added for imported data 
![screenshot from 2015-08-17 13 45 43](https://cloud.githubusercontent.com/assets/6483446/9299473/7886df5a-44e6-11e5-8b81-150c98a3fb75.png)
![Uploading Screenshot from 2015-08-17 10:02:08.png…]()

**Comment by mariobehling** [comment]
Closing it as changes depend on new server implementations.
