### ISSUE TITLE
'Add Map' shows strange viewpoint, broken map and marker not possible

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#448]
- click on 'compose new tweet'
- click on 'attach map'
you then see that:
<img width="1129" alt="attachmap" src="https://cloud.githubusercontent.com/assets/238730/9192737/e6c210b2-400d-11e5-92a5-8a19fd37a17a.png">

Things to fix:
- better viewpoint (if available, current location of user, taken from browser location data, in center)
- zoom in in such a way that at most 1 mile around is visible
- the map must not be broken and fill the input window completely
- it must be possible to place a marker

**Comment by sudheesh001** [comment]
<img width="1440" alt="screen shot 2015-08-11 at 5 07 22 pm" src="https://cloud.githubusercontent.com/assets/4545925/9196709/8eb0529c-404b-11e5-8354-bdc43046bea5.png">

**Comment by Orbiter** [comment]
yeah! where can I test that?

**Comment by mariobehling** [comment]
* [ ] Please change "Tweet" button to blue as on home page top bar.

**Comment by sudheesh001** [comment]
Test link at http://loklak.cloudapp.net:3001/
