### ISSUE TITLE
Connect: Add "Open File", "Map" View and "Shared by"

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#449]
We are still figuring out, what are the best ways to visualize open data and IoT. It would be helpful to start with this in the connect area for now. Please add three fields in the table at the end (on the very right side):
* [x] "Item" (header) and "File" link in the row, which opens an overlay with the actual imported file
* [x] "Map" (header) and "View" in the row, which opens an overlay with a map and the data of the file displayed on a map
* [x] "Shared by" (header) and in the row "number of people sharing this source item" e.g. "5" on click on the number show the people sharing this item. (This is similar to Facebook likes, e.g. "5 people like this page".)

Please also fix:
* [x] the column width, so columns are displayed more evenly

![screenshot from 2015-08-11 13 25 13](https://cloud.githubusercontent.com/assets/1583873/9196526/6f2ef51e-402c-11e5-9055-cd078ad779ec.png)

**Comment by zyzo** [comment]
> "Item" (header) and "File" link in the row, which opens an overlay with the actual imported file

By "overlay with the actual imported file", do you mean this ? : 
![screenshot from 2015-08-13 09 33 27](https://cloud.githubusercontent.com/assets/6483446/9241500/933ad0fe-419e-11e5-981d-03e551d4bd57.png)

It is an popup showing message content, when clicking on the message in loklak map. I could find a way to reuse this popup in connections list.

**Comment by mariobehling** [comment]
Where is that page with that popup? Please create a page that acts the same as the import overlay page, but: With a map and the data displayed.

![screenshot from 2015-08-13 09 26 08](https://cloud.githubusercontent.com/assets/1583873/9244649/83c8e058-419d-11e5-9c4e-3003fc7ea85e.png)

**Comment by zyzo** [comment]
The current implementation looks like this :
![screenshot from 2015-08-17 10 02 08](https://cloud.githubusercontent.com/assets/6483446/9297286/281b9336-44c7-11e5-8fd5-6785b62c299e.png)

@mariobehling where & how should I implement a share button ? Without which, shared by column is useless.

**Comment by mariobehling** [comment]
Sorry to say that, but I have no clue what you are implementing and it is very tiresome to look at some many details, that after you are working on this since midterm, are still not clear. Some issues I see:
* [ ] View map shows mariobehling with hackerspace.sg - why? It should be similar to the fossasia api including possibly showing the three most recent blog entries e.g. here:
![screenshot from 2015-08-18 13 05 08](https://cloud.githubusercontent.com/assets/1583873/9328597/45cccc68-45aa-11e5-8c74-d38166a6f0f0.png)

* [ ] same applies for other API files e.g. freifunk nodes. They should show up just like they show up on the original maps.

* [ ] map is very small? why? just make it the same size as the wizard overlay
![screenshot from 2015-08-18 13 05 08](https://cloud.githubusercontent.com/assets/1583873/9328590/2b2fed5e-45aa-11e5-8e8c-a0e8aaa66845.png)

Regarding the share, please do take the time to actually read what I am writing on different channels and what we talked about several times:

* [ ] "Shared by" (header) and in the row "number of people sharing this source item" e.g. "5" on click on the number show the people sharing this item. (This is similar to Facebook likes, e.g. "5 people like this page".) We are talking here about "how many people have shared the same URL or file". I do not know how I can make this more clear.

**Comment by mariobehling** [comment]
* [ ] I have added a URL. There wizard does not close. After "submit" the wizard should close and the new file should show up in the list.

* [ ] the bottom of the wizard is out of design. See screenshot.

![screenshot from 2015-08-18 13 13 33](https://cloud.githubusercontent.com/assets/1583873/9328688/229c060e-45ab-11e5-9810-726178c7c644.png)

**Comment by zyzo** [comment]
Hi @mariobehling 
>  View map shows mariobehling with hackerspace.sg - why? 

It is because, we decided to attach the pushed data to logged in user. It can't show hackerspace.sg as owner, since that username doesn't exists anyway. The popup template is reused from loklak map, which shows the user avatar and screen_name, and data content.

> It should be similar to the fossasia api including possibly showing the three most recent blog entries e.g. here:
screenshot from 2015-08-18 13 00 45
> same applies for other API files e.g. freifunk nodes. They should show up just like they show up on the original maps.

This is because, the data format in loklak is message-based & very different from fossasia api & freifunk data. I had a discusstion with @Orbiter a while ago & we agree that attach custom data (blog, feed, etc.) as rich-text field is a good idea https://github.com/loklak/loklak_server/issues/55#issuecomment-118917334, but I was waiting for the rich-text concept to be fully implemented. Now might be the good time to look at how we can achieve it. 

As for the map popup, it is difficult to expect the design to match exactly fossasia, freifunk or any other map design. It would mean different design for each message type. It is inconsistent. The data is imported to loklak so I think it is best to fit in loklak style, & benefit from loklak wall & map. Otherwise, why would we need to integrate the data into loklak ? 

>  "Shared by" (header) and in the row "number of people sharing this source item" e.g. "5" on click on the number show the people sharing this item. (This is similar to Facebook likes, e.g. "5 people like this page".) We are talking here about "how many people have shared the same URL or file". I do not know how I can make this more clear.

> Again: It should be "Shared by" e.g. "Shared by 5 users". On scroll over the name of the users show up. These are all the users who have shared the same file.

The version you're testing at loklak.net is not the latest version. I provided a screenshot at previous comment https://github.com/loklak/loklak_webclient/issues/449#issuecomment-131664801, with the Shared by column showing number of shared user. Sorry that I couldn't get my test env running, I still can solve the twitter login problem. 

> Sorry to say that, but I have no clue what you are implementing and it is very tiresome to look at some many details,

I'm sorry that you feel that way, but I am also confusing. I followed your guidelines, implemented the design as your mockup & suggestion. I believe there is some work to be done to get the data connect useful, namely the share feature (please provide input here #447), and the custom data attachment as rich text. But I don't think what I'm implemented is meaningless. Could you please specify which part of the design that you have no clue about ?

**Comment by mariobehling** [comment]
> It is because, we decided to attach the pushed data to logged in user. It can't show hackerspace.sg as owner, since that username doesn't exists anyway. The popup template is reused from loklak map, which shows the user avatar and screen_name, and data content.

Look the goal is to follow the overall design, but of course the view needs to be displayed in a way that makes sense for a user. The way you implemented that is not useful.

> As for the map popup, it is difficult to expect the design to match exactly fossasia, freifunk or any other map design.

We do not expect to match FOSSASIA. The goal is to show the relevant data here. We do not aim to follow other designs. We expect to see the relevant data here, just like it is on the FOSSASIA maps or other maps.

**Comment by mariobehling** [comment]
Where are those fields - blog, facebook etc. - in the popup on loklak?
![screenshot from 2015-08-18 19 01 18](https://cloud.githubusercontent.com/assets/1583873/9336760/90881808-45db-11e5-88f8-7622e87c0cac.png)

**Comment by mariobehling** [comment]
Here is a mockup how the FOSSASIA items could look on the map.
![screenshot from 2015-08-18 19 01 18](https://cloud.githubusercontent.com/assets/1583873/9337126/b453b3f8-45dd-11e5-98c0-cb9782244993.png)

**Comment by mariobehling** [comment]
I am not clear which data set to enter for each API. Please give an example URL for each API.
* [ ] Freifunk Node
* [ ] GeoJSON
* [ ] Netmon
* [ ] Nodelist
* [ ] OpenWifiMap

**Comment by zyzo** [comment]
> I am not clear which data set to enter for each API. Please give an example URL for each API.

- For freifunk routers wifi urls can be extracted from each community url in https://raw.githubusercontent.com/freifunk/directory.api.freifunk.net/master/directory.json. I collected them into a list here which might be useful : 
https://github.com/zyzo/ff2ll/blob/master/urls.json

**Comment by mariobehling** [comment]
Not working for me:
* [ ] ffmap
* [ ] nodelist
* [ ] GeoJSON (e.g. try the listed files on right sidebar here: http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php)

Import Working
* netmon 
* OpenWifiMap

But: Does not show a map.
![screenshot from 2015-08-19 07 47 26](https://cloud.githubusercontent.com/assets/1583873/9349458/964cfdf6-4646-11e5-85f0-b3cb496e7d25.png)

**Comment by mariobehling** [comment]
As you do not have a test system up, maybe merge current progress and continue on the issues.

**Comment by zyzo** [comment]
Merged #482.

**Comment by zyzo** [comment]
>  GeoJSON (e.g. try the listed files on right sidebar here: http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php)

I believe the reason why this doesn't work is because of missing `mtime` value. The stack trace should have something like this : 
```text
Failed to load resource: the server responded with a status of 400 (Error computing id : geojson format error : member 'mtime' required in feature properties)
```
This was a constraint for geojson data. The constraint was removed in https://github.com/loklak/loklak_server/pull/110 & will be fixed after the merge

**Comment by zyzo** [comment]
File view, Map View and Shared by columns added to connection lists. Fixed with https://github.com/loklak/loklak_server/pull/117 https://github.com/loklak/loklak_webclient/pull/502.
