### ISSUE TITLE
Wall search box shall appear only once

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#45]
The wall shall NOT show the search box, once the box was used to input a search term.

If the wall was selected from the menu, it MUST show the box.

**Comment by sudheesh001** [comment]
We can simplify this by using `/wall?q=FOSSASIA` rather than keeping track of a the button from which the user has bounced. Another possibility in case we want to retain the search box is to `hide` the box as soon as the query is sent, Which one do you think is a good option ?

**Comment by julianfox** [comment]
@sudheesh001 i used the second solution in my last commit... but may be we can add a button for make another search ?

**Comment by sudheesh001** [comment]
@julianfox Done, Added the button to make a new search. :smile:
