### ISSUE TITLE
Merge "Home" and "Map" View into one view "Home"

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#452]
* [x] First add an "Arrow" pointing to the left to the map view (on the right next to the right pointing arrow). See below ![screenshot from 2015-08-11 14 21 21](https://cloud.githubusercontent.com/assets/1583873/9197677/9fa850fa-4036-11e5-993b-419deed368ee.png)

Clicking this arrow will result in the following view, which is similar to the current home view:
![screenshot from 2015-08-11 14 24 44](https://cloud.githubusercontent.com/assets/1583873/9197709/f1dd6770-4036-11e5-97a1-cb13f6e782d6.png)

* [x] On the left hand side now appears a label "Map" with a right pointing "Arrow". Clicking this arrow will result in the original map view.

* [x] Also fix the background of the page and change it into the standard grey background.

* [x] Add followers and following areas into the left sidebar as shown in the mockup.

**Comment by fuksi** [comment]
@mariobehling . The first version of this implementation is here. I moved the "Map >" to the top of the user banner (I think it looks very inbalance if it is placed on the far left, especially when the browser width is squeezed) and define 0.5s transition between timeline & map.

http://gofullstack.me:3001/

Please comment here if there is some change necessary. If it's ok I can move forward & add the folowers & followings areas to finish this feature.

**Comment by mariobehling** [comment]
Very nice work. Is it possible to make the effect like a slide in/slide out effect of the map (just like the activity sidebar) and instead of loading the side expanding the central *activity bar* to become the main area?

Check out http://tympanus.net/Development/SidebarTransitions/

Maybe something like "slide on top" over the map where also additional content is added? Is this feasible?

**Comment by mariobehling** [comment]
The current slider effect does not seem to achieve the desired result. The challenge is to have a good view square of the map. Please change it the "Push" effect and let's see how that works. Cheers.  http://tympanus.net/Development/SidebarTransitions/

**Comment by fuksi** [comment]
Live at http://gofullstack.me:3001/
- Activity feed `Push` effect is implemented.
- Regarding slide in/slide out of the map. I implemented it anyway but here my thoughts:
  + Sliding big content usually hurt the eyes. 
  + I used native css animation for the best performance, but still the content area are really big, you can still see some uncomforting flickering in transition. The animation was smoothest only in Microsoft Edge (since it's 64 bits and the rest is 32 bits)

Please comment here if you want to follow through with the slide In/slide Out, or the old fade transition :)

**Comment by mariobehling** [comment]
Ok, I see. I guess it is difficult to explain. The question is in regards to mobile. I think, we should start to focus on mobile now that we get to a stable release. However, maybe the image I have in mind is not working out here.

So, the idea is, that you click on the button and the area "activity" expands. Currently the area disappears and you have a completely new screen moving in from the right. It would be nice to actually tip on the arrow and the right side bar slides in and expands. Please see below. How would something like that be achievable and what would make sense the most?

![screenshot from 2015-08-20 10 51 25](https://cloud.githubusercontent.com/assets/1583873/9379637/f3d7bb84-472a-11e5-9fd1-c28da1401c7d.png)
