### ISSUE TITLE
Start Screen shows up shortly when loading loklak page on new window/tab 

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#456]
Even though I am logged in, the "What's going on" start screen for anonymous users shows up for a second or so.
* [x] Avoid loading screen for logged in users.

![screenshot from 2015-08-11 17 53 54](https://cloud.githubusercontent.com/assets/1583873/9202453/3886c43a-4052-11e5-93b8-56f6903db5ec.png)

**Comment by fuksi** [comment]
Solve with the PR above.
