### ISSUE TITLE
Reports not displaying account user, country wise info and having style issues

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#460]
1. Clicking on "report" results in "Sorry we did not find anyone with this account".
![screenshot from 2015-08-12 10 19 55](https://cloud.githubusercontent.com/assets/1583873/9219528/c9b05a8c-40db-11e5-9faa-482de54c68b5.png)

2. Correct: report:username Incorrect: report:@username. 

3. It does not look like fitting into the style and there are round edges between the columns.
![screenshot from 2015-08-12 10 21 22](https://cloud.githubusercontent.com/assets/1583873/9219543/e6e26c6c-40db-11e5-984a-1850769de3e1.png)

4. Country wise followers not available
![screenshot from 2015-08-12 10 21 55](https://cloud.githubusercontent.com/assets/1583873/9219560/030e5df6-40dc-11e5-885e-124917167ce1.png)

5. Testing incognito should not be possible. I see columns without content. That should not happen. In logged in mode here should be the data of the account holder. Is that the case?
![screenshot from 2015-08-12 09 19 59](https://cloud.githubusercontent.com/assets/1583873/9218549/a2548aa6-40d3-11e5-8fe1-98815ecc3ac4.png)

**Comment by mariobehling** [comment]
@prasht63 As this is live, this is a top priority.

**Comment by prasht63** [comment]
@mariobehling I am working on it.Will send a PR in a couple of hours
