### ISSUE TITLE
Connect : Fix remaining design issues & improve UX on dataConnect page

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_webclient#461]
There are some several issues left with `/dataConnect` page, that need to be fixed soon for the feature to make sense for user. Specifically : 

- [x] Fix error message `[$rootScope:inprog] $apply already in progress` when clicking on a source type
- [x] Most of the time, user doesn't have to worry about harvesting frequency, and lifetime. To not to scare them, display those inputs as advanced options & only open when clicked on.
- [x] Currently, only geojson data needs (& supports) map rules. Show 'Map rules are not activated for data of type _` for other source types.
- [x] Improve map rules helper messages. Add some more loklak fields that user can map to (video, audio ...?)

These issues are expected to be quickly resolved.

**Comment by mariobehling** [comment]
* [ ] Please use the actual logo of Freifunk and center all logos
![screenshot from 2015-08-12 10 43 24](https://cloud.githubusercontent.com/assets/1583873/9220045/db13de9e-40df-11e5-82b4-cad76a6d2fc8.png)

* [ ] And please avoid scrollbars if not necessary (why to scroll here? there is no content to scroll to in all three steps at the moment.)

* [ ] a) Please use correct spelling and capitals: "Final step : map your data to loklak" -> "Final step: Marp your data to loklak." b) Maybee adjust your keyboard standards to English or fix the space before the colon by hand

* [ ] Take out username, as we are using the name of the account holder

* [ ] Please add helper texts, that make sense to the user

  * [ ] "The field name that matches to message's coordinates, in the following format [lon,lat]. Message' coordinates are used to locate the message on loklak map." What is the user expected to enter? Please write a message like "Please enter xyz here. This information will show up at... An example for a useful entry is ... "

  * [ ] Please take care more of details - two "t's", no full stop at the end! And create a message that makes sense to the user. "Tthe field name that matches to message's text. This is the actual content of the message" -> "Please enter xyz here. This information will show up at... An example for a useful entry is... "

**Comment by zyzo** [comment]
> Please use the actual logo of Freifunk and center all logos
I just thought it would be nice to use this logo for freifunk wifi routers, and the official logo for freifunk communities. What do you think ? 

> And please avoid scrollbars if not necessary (why to scroll here? there is no content to scroll to in all three steps at the moment.)
![screenshot from 2015-08-12 16 07 46](https://cloud.githubusercontent.com/assets/6483446/9220449/e08fb938-410c-11e5-9b6e-4bfcb2035b22.png)
I can't replicate this at my dev env (or at test.loklak.net). Which browser & screen resolution are you on ?

**Comment by mariobehling** [comment]
> I just thought it would be nice to use this logo for freifunk wifi routers, and the official logo for freifunk communities. What do you think ?

I think we need a designer to think about this. The image you created is not up to standard.

> I can't replicate this 

Testing in different resolutions and browsers should always be part of your testing. Then this issue will come up at one point. Just hit Shift+ and you will probably also see that. I already posted a screenshot with the issue. What reply do you expect from me now? If I have this issue, then others will also have that. Please solve this.

**Comment by mariobehling** [comment]
@zyzo Please do fix these things quickly. I have not seen how the actual data can be displayed and searched in loklak. There are tons of things to do. Please speed up.

**Comment by zyzo** [comment]
> An example for a useful entry is... 

This is not really relevant since the field name is different for each source. It is why we need mapping rule.

All items are fixed via https://github.com/loklak/loklak_webclient/pull/465. A concept introduced in this PR is dynamic mapping rules that depend on each source type. For source type that doesn't require map rules (internally supported by loklak), a message `This step is not required for ..` is displayed. Currently, only GeoJson needs mapping rule. And since its coordinates field is well known (inside `geometry` field), coordinates map rule for geojson is also removed. Things will probably get more interesting with rich text attachment.
