### ISSUE TITLE
Adapt report page design to match search page design

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#464]
Currently the report page looks a bit messy. Please help to adapt it to the standard search page, e.g. reuse the same style for the white secondary menu bar.

Specifically use the top bar structure with the white bar below (with Followers/Following/IoT) as seen in search.
![screenshot from 2015-08-24 22 05 16](https://cloud.githubusercontent.com/assets/1583873/9450989/484c92e6-4aac-11e5-8200-6f38e84b7555.png)

**Comment by fuksi** [comment]
Done with the PR above
