### ISSUE TITLE
Create area with loklak info to show up on bottom of right hand sidebar home, search, report etc.

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#472]
* [x] Add button line as in comment and image https://github.com/loklak/loklak_webclient/issues/424#issue-98722644
* [x] © 2015 loklak
* [x] About (link to /about)
* [x] Blog (link to http://blog.loklak.net) - new tab
* [x] Github (link to http://github.com/loklak) - new tab
* [x] Facebook (link to http://facebook.com/loklakmessages) - new tab
* [x] Match twitter design with white background

![screenshot from 2015-08-14 13 21 31](https://cloud.githubusercontent.com/assets/1583873/9272923/68741dc8-4287-11e5-8df1-562fa2561a98.png)

**Comment by fuksi** [comment]
Done with the PR above
