### ISSUE TITLE
Search bar buggy and regularly disappears

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#483]
The search bar actions are not working as expected yet.
* [x] bar disappears regularly (sometimes refreshing the page works)
![screenshot from 2015-08-18 09 54 09](https://cloud.githubusercontent.com/assets/1583873/9324994/7752d4d2-458f-11e5-8b85-7a4bb42f8978.png)
![screenshot from 2015-08-18 09 53 50](https://cloud.githubusercontent.com/assets/1583873/9324993/774de198-458f-11e5-856c-447a359cb26a.png)

* [x] loading of search results is often slow and entering a new search while the old search is performed does not seem to work. Expected behaviour: Abort old search and display new search.

**Comment by fuksi** [comment]
Regarding the first point: what I was trying to do is to show only 1 search box to user at a time. (This is also the same at twitter). Will fix the strange behavior in the next PR

**Comment by fuksi** [comment]
Done with the PR above
