### ISSUE TITLE
Search bar suggestions bugs

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#485]
When adding a search the search bar offers suggestion. Please make the suggestions work as in other services including
* [x] entering suggestion on the main page, suddenly the result page shows suggestions on top right
* [x] clicking outside of suggestion bar should close suggestions
* [ ] please test this feature in more detail and fix other potential bugs

 ![screenshot from 2015-08-18 11 18 24](https://cloud.githubusercontent.com/assets/1583873/9326565/ee8036de-459a-11e5-81ac-62f82858bec8.png)

**Comment by fuksi** [comment]
Done with the PR above
