### ISSUE TITLE
Account Search missing links to profiles/list of tweets and no links to hashtags etc.

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#490]
Please implement in accounts search:
* [x] links to all tweets/profile of the account
* [x] links to hashtag/URLs etc.
* [x] show if user follows account
* [x] show if searched accounts are following user

Current state with missing features:
![screenshot from 2015-08-18 18 35 27](https://cloud.githubusercontent.com/assets/1583873/9336148/4460487c-45d8-11e5-9d0d-27a5163666d1.png)

* [x] Adapt size of (width/height) to match twitter and distance between found items in account search
![screenshot from 2015-08-18 18 40 58](https://cloud.githubusercontent.com/assets/1583873/9336256/eb99c802-45d8-11e5-9515-56b2c733e8f7.png)

**Comment by sopu** [comment]
I have added a PR for it! I have fixed part-2 and 5. Will be adding more fixes soon.
