### ISSUE TITLE
Show overlay login only once per session and increase time to show to 10 seconds

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#504]
Currently the overlay shows up every 7 seconds without activity.
* [ ] increase this time to 10 seconds
* [ ] show login overlay only once per session (or day?). If user has clicked it away, keep it away.

![screenshot from 2015-08-20 20 36 52](https://cloud.githubusercontent.com/assets/1583873/9392184/76b062e0-477b-11e5-864a-6b0b2ab57f9a.png)

**Comment by fuksi** [comment]
This is implemented among other commits. Can be checked on live.
