### ISSUE TITLE
Avoid loading/showing fall back images and empty area on loading home screen

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#514]
When a user loads the home screen for a short time fall back images and empty areas on the home screen appear. Please 
* [x] do not load fall back images when actual account images are available
* [x] do not show empty areas

![screenshot from 2015-08-22 18 25 31](https://cloud.githubusercontent.com/assets/1583873/9424844/7e0f13fc-48fb-11e5-9d1e-470665ed1049.png)

**Comment by fuksi** [comment]
Solved with the PR above
