### ISSUE TITLE
Research twitter wall designs

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#52]
The twitter wall was on display yesterday at the OpenTechSummit. Lots of people added content, because they saw the wall. We now need to improve the design, e.g. text was too small for the wall. Please research how other twitter walls display tweets and post links and screenshots of twitter walls here.

**Comment by sudheesh001** [comment]
At the moment we have a vertical scroll animate and the main tweet on top, what we could do is rather, use horizontal scroll animate and show the large tweet in the centre and fade out up or down with another tweet taking over, that way the main tweet is always the `center of attraction`
What say @fuksi ?

**Comment by mariobehling** [comment]
@sudheesh001 It is easier to imagine what you propose, if you offer a wireframe of something similar. Also, it would be great, if you could each of you put a screenshot here of other existing twitter wall services. This would help us to understand what design options we have.

**Comment by aneeshd16** [comment]
@sudheesh001 That sounds good.
I have another suggestion. Currently, as new tweets come, they keep on adding to the list. After a while, this list would undoubtedly become very long. Since the wall is supposed to be used in a desk/kiosk mode, why not just limit the list to 3 tweets or so? There will be one main tweet, as a `centre of attraction` as you mentioned, and just three below it. Older tweets will not be shown.

**Comment by mariobehling** [comment]
@sudheesh001 Yes, it is a possibility. We could also have a small menu on top, that appears when you go to the top with your cursor. Here people could configure options. BUT: Let us all take a step back, please and look at existing walls to understand how they function in regards to the interface and appearance. 

I would like to see screenshots and short wrap ups of 10 different twitter walls here first before we talk about more details.

**Comment by julianfox** [comment]
A good exemple: http://tweetwall.com
Ux/design totally different... But it's the core feature of this company, so i am pretty sure that know what is the best solution for this :-)

**Comment by sudheesh001** [comment]
Other examples are
- http://www.tweetbeam.com/show?query=loklak
![screen shot 2015-05-16 at 2 35 13 pm](https://cloud.githubusercontent.com/assets/4545925/7665968/265c8bf4-fbd9-11e4-9168-29df4733f1ee.png)

- http://www.activitywalls.com/?h=Loklak&c=fc1fff666 (Needs to authenticate app)
![screen shot 2015-05-16 at 2 34 22 pm](https://cloud.githubusercontent.com/assets/4545925/7665970/360694fa-fbd9-11e4-8bf5-6ffabda1353a.png)

looking at the sites tweetwall, tweetbeam and activitywalls, I really think we need to get our landing page a makeover. Can I take that redesign work up until we decide on the wall UI/UX ?

`Will post a wireframe soon for the wall`

**Comment by aneeshd16** [comment]
Mockup for twitter wall 1
![page 1](https://cloud.githubusercontent.com/assets/5436027/7669240/1202412e-fc85-11e4-8f34-e905122583ad.jpg)

**Comment by aneeshd16** [comment]
Mockup for twitter wall 1, opacity is important
![page 2](https://cloud.githubusercontent.com/assets/5436027/7669245/819e9294-fc85-11e4-936b-1a779115e0fd.jpg)

**Comment by aneeshd16** [comment]
Mockup for twitter wall 3
![page 1](https://cloud.githubusercontent.com/assets/5436027/7669599/ae6a615e-fc99-11e4-8746-5053b482b0c7.png)

**Comment by mariobehling** [comment]
Hi @sudheesh001 Good ideas for mockups, but this issue is dedicated to research about twitter walls. Mockup should go into another issue. Let's stay with the topic of issues, please. I added an issue for you here https://github.com/loklak/loklak_webclient/issues/54

@everyone Please have a look around, if there also maybe already an existing twitter wall or several twitter walls, that we might be able to integrate. Github gives me 122 results. Which ones do you like? Please post screenshots: https://github.com/search?utf8=%E2%9C%93&q=twitterwall and https://github.com/search?utf8=%E2%9C%93&q=twitter+wall
Someone even made a twitterwall.js.

**Comment by sudheesh001** [comment]
@mariobehling https://github.com/EightMedia/TwitterFontana , This looks promising.

**Comment by aneeshd16** [comment]
There seems to be two kinds of twitterwalls:
*Display one tweet at a time utilizing most of the screen http://twitterfontana.com/
*Display a queue of tweets, with new tweets getting added to the top. https://confwall.com/archived/54c565df1e7ea9e310691b0e
(This could also include a special highlighted tweet, like in the mockups me and @sudheesh001 posted.)

Although the first option looks aesthetically better, IMO we should go for the second option because it gives more information at a glance to the user. The first option is not particularly “useful”.

**Comment by mariobehling** [comment]
@sudheesh001 @aneeshd16 Give us some screenshots.
Other questions to consider: What technologies are they using? How easy is it to set them up? Could we possibly integrate them with Loklak? What options do those twitterwalls have for the users e.g. can the user change the display time of feeds, start date of tweet postings. Is there an option to exclude certain tweets or users? Is it possible to display a common list made from different hashtags?

**Comment by fuksi** [comment]
Based on the mentioned examples above I suggest that the wall consists of 3 components:  

![loklakwall](https://cloud.githubusercontent.com/assets/6878677/7670284/2ebf779c-fca7-11e4-8a5a-15aabf2b07b5.png)

- Centre of attraction: the newest tweet. 
- A stream of tweets: the minor purpose of these is to show to capability of loklak, and also from this, the users can quickly see how popular is the current affair. We can easily integrate this form our current wall.
- A stream of images: similar to stream of tweets.

Extra libraries that we can use: [TwitterFontana](http://twitterfontana.com/) for the center, [Masonry](http://masonry.desandro.com/) for the pictures, and simple animate.css for all components.

1. For a user who watches the wall (literally on a projected screen or sth), the center should be big enough.
2. Normal users with browsers should be able to:
  * From the stream of tweets: Drag or just type ```right``` for older tweet
  * From the stream of images: hashtag ```#loklak```can disappear when hovered to the images area. Either that a modal is popped up or we can create a slide of images with [slick](http://kenwheeler.github.io/slick/), which is much more flexible than PhotoSwipe
  * Conduct an advanced search (we've already done this part before in statistics view)

@mariobehling About the last question, I believe it's already a feature from the server, if the search term contain multiple hashtags e.g. ```#javascript #web```, we should receive only those tweets with both hashtags. Of if you meant the tweet should contain at least one of those hashtags, then we need to do multiple requests, but yes it's possible!

**Comment by aneeshd16** [comment]
1. We do have a variety of options now, I especially liked @fuksi 's suggestion that shows images, the centre of attraction and the tweet stream in the same page, without making it too messy or cluttered.

2. Additional options like filters can be hidden in a popup linked to something like a gear icon. All the options that @mariobehling mentioned are supported by the server and have already been implemented in the statistics page. It should be easy to put them here.

3. The wall could possibly have an alternate view that shows statistics. So we have a **stream** view and an **aggregate** or **statistics** view. There could be a simple option that can switch views quickly.

**Comment by aneeshd16** [comment]
I have been assigned the wall feature, and would like to use the one proposed by @fuksi 
![loklakwall](https://cloud.githubusercontent.com/assets/6878677/7670284/2ebf779c-fca7-11e4-8a5a-15aabf2b07b5.png)

But i would like to get some opinions and feedback from @loklak/loklak_developers, especially from @mariobehling and @Orbiter :)

**Comment by mariobehling** [comment]
@aneeshd16 Let's have a chat about this. Please ping me on Gitter.

**Comment by Orbiter** [comment]
Thank you for the research, I close this now because we have a strategy for the wall now. @mariobehling please reopen if disagree on strategy.
