### ISSUE TITLE
Wall: Increase used area of horizontal images

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#520]
* [ ] Please try to use maximum height of images in available area
![screenshot from 2015-08-25 23 24 00](https://cloud.githubusercontent.com/assets/1583873/9480068/23ae5642-4b81-11e5-9f9f-d9feceef282b.png)

**Comment by sopu** [comment]
I think the issue has been fixed.

**Comment by sudheesh001** [comment]
@sopu did you try resizing the screen and checking if the issue still exists ?

**Comment by sopu** [comment]
@sudheesh001 I beg your pardon. The issue still persists as the data is being reduced in size as screen-size decreases whereas the card size and profile pic size remains the same. 
Moreover notice that "tweets frequency" card is dangling with change in screen-size.

**Comment by sudheesh001** [comment]
Could you send a patch to that in case you're interested :smile:

**Comment by sopu** [comment]
@sudheesh001 Sure will do :+1:

**Comment by sopu** [comment]
@sudheesh001 Please check the PR I put for this issue.

**Comment by sopu** [comment]
I believe this can be closed now?
