### ISSUE TITLE
Add followers/following widgets to /report

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#525]
* [x] These two widgets could probably best fit on the left hand side right now at /report.
* [x] Please also reduce the widgets on /home and /report to 3 rows.
* [ ] If possible sort the accounts by who followed/following recently (so show the most recent followers/following on top).

![screenshot from 2015-08-27 17 19 33](https://cloud.githubusercontent.com/assets/1583873/9524611/098e8538-4ce0-11e5-9ee3-f6ce57c0a6ce.png)

**Comment by fuksi** [comment]
Unfortunately sorting is for now not possible due to limited information from user.json servlet
