### ISSUE TITLE
Ensure left and right sidebars match top bar edges on report and search results

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#534]
The design of the left and right sidebars is out of line. Please ensure the design edges match on the left and right in
* [x] /report
![screenshot from 2015-09-01 17 20 52](https://cloud.githubusercontent.com/assets/1583873/9608487/e20b1f6a-50ce-11e5-86ca-fb6cb860d904.png)
* [x] /search results
![screenshot from 2015-09-01 17 21 13](https://cloud.githubusercontent.com/assets/1583873/9608493/e8d759da-50ce-11e5-82df-79a58787c9d6.png)

**Comment by sopu** [comment]
I believe it has been fixed #579 
Closing!
