### ISSUE TITLE
Loklak search page on loklak.net/search should show search bar just as start screen

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#535]
![screenshot from 2015-09-01 17 26 24](https://cloud.githubusercontent.com/assets/1583873/9608508/131e877c-50cf-11e5-9e19-cbf538860a75.png)

Expected behavior:
![screenshot from 2015-09-01 17 31 15](https://cloud.githubusercontent.com/assets/1583873/9608542/44ada156-50cf-11e5-85f9-b64b7b6ca54d.png)

**Comment by sopu** [comment]
This can be closed imo @mariobehling
