### ISSUE TITLE
Report Search Button Design

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#538]
The "Create New Report" button is attached/overlapping with report box. Maybe also change "Create New Report" to "Create Report" to keep it shorter.
![screenshot from 2015-10-17 12 55 47](https://cloud.githubusercontent.com/assets/1583873/10558425/b44a80e2-74ce-11e5-9ce6-c47e8239362a.png)

**Comment by Orbiter** [comment]
I know, I already messed around at that button. 'Stealing' CSS code from other buttons did not help to fix the design. I actually don't know why those other buttons have a different font and this one not.

**Comment by sopu** [comment]
Refer the PR #571 and please suggest modifications!

**Comment by sopu** [comment]
#571 fixes it! 
Closing.
