### ISSUE TITLE
Mockups for Twitter wall

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#54]

**Comment by sudheesh001** [comment]
Aneesh has uploaded a few twitter wall mockups. :+1: 
![1](https://cloud.githubusercontent.com/assets/4545925/7669846/7655989a-fc91-11e4-8d11-531246dd366c.jpg)
![2](https://cloud.githubusercontent.com/assets/4545925/7669847/78237ae8-fc91-11e4-9114-78d4297f2f34.jpg)
![3](https://cloud.githubusercontent.com/assets/4545925/7669848/7a600bb4-fc91-11e4-8fcf-89d975bb6318.png)

A few design inspiration sources are:
- http://www.tweetbeam.com/show?query=loklak
![screen shot 2015-05-16 at 2 35 13 pm](https://cloud.githubusercontent.com/assets/4545925/7665968/265c8bf4-fbd9-11e4-9168-29df4733f1ee.png)

- http://www.activitywalls.com/?h=Loklak&c=fc1fff666 (Needs to authenticate app)
![screen shot 2015-05-16 at 2 34 22 pm](https://cloud.githubusercontent.com/assets/4545925/7665970/360694fa-fbd9-11e4-8bf5-6ffabda1353a.png)

One of Aneesh's template also matches
![screen shot 2015-05-17 at 12 39 11 pm](https://cloud.githubusercontent.com/assets/4545925/7669854/c86ec2fa-fc91-11e4-8a25-dfb76d9354ac.png)

The product is open source [here](https://github.com/EightMedia/TwitterFontana)

**Comment by sudheesh001** [comment]
I think we should start with using the https://almsaeedstudio.com/AdminLTE bootstrap template, its really clean and pretty easy to customize, Fontana is great too. @fuksi @aneeshd16

**Comment by mariobehling** [comment]
@sudheesh001 Good input I like this theme. The idea to get this twitter wall started is to follow existing designs of services like tweetwall.com. So, will help us to get to a first stable version without having to decide on a lot of detailed questions.

After the first version, we should implement additional features, e.g. an image only view, adding more statistics, adding other services etc.

@aneeshd16 Does this bootstrap theme proposed by sudheesh work to get you started?

**Comment by julianfox** [comment]
+1
