### ISSUE TITLE
Results in Wall not relevant to search terms

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#541]
Results in wall are not relevant, e.g. searching for "gsoc" and "#gsoc"
http://loklak.net/fossasia/wall/VypzmYxfx

![screenshot from 2015-11-02 18 18 46](https://cloud.githubusercontent.com/assets/1583873/10888730/2e36d754-818e-11e5-8203-e1444aa80ea9.png)

![screenshot from 2015-11-02 18 19 14](https://cloud.githubusercontent.com/assets/1583873/10888746/3e153864-818e-11e5-9e61-9e9b1d335c28.png)

**Comment by aneeshd16** [comment]
This is the request by the wall:
http://loklak.org/api/search.json?callback=angular.callbacks._6&count=10&fromWall=true&q=gsoc+OR+%23gsoc+-%2Fprofanity+include:retweets
The server seems to be giving strange results

**Comment by Orbiter** [comment]
I tried to fix this with https://github.com/loklak/loklak_server/commit/c767379f07441d790a74e17dbb96096ea4603fa0 but that was not successful (yet). I will continue..

**Comment by Orbiter** [comment]
fixed
