### ISSUE TITLE
Loading icon not in line

### ISSUE THREAD

**Issue by codethejason** [loklak/loklak_webclient#562]
When the wall is being loaded, the loading circle in the header is not aligned to the center of the page:  

![align](http://puu.sh/mF0tX/ef1c9c3bae.jpg)

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/12872215/bde7aec0-cdc2-11e5-8b9f-3bf6f3a6491d.png)

@codethejason Should be fixed via #563

**Comment by SilentFlame** [comment]
is it resolved or still open??

**Comment by aneeshd16** [comment]
@SilentFlame will be fixed once #563 gets merged.
