### ISSUE TITLE
Photoswipe button content displaced on retina displays

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#57]

**Comment by aneeshd16** [comment]
@sudheesh001 , this 86152c93a27958a9c02e4ab2a59c4fc1d50b43fa doesnt solve it?

**Comment by sudheesh001** [comment]
![screen shot 2015-05-20 at 5 13 26 pm](https://cloud.githubusercontent.com/assets/4545925/7727748/9c933d4e-ff13-11e4-8de9-2467d992f5ef.png)

Seems to be fixed but dislocated on the screen, the last tab moves out of the screen on the Mac retina, works fine on a non-retina display.
