### ISSUE TITLE
Import errors while gulp-dev

### ISSUE THREAD

**Issue by SilentFlame** [loklak/loklak_webclient#572]
When I was developing the `webclient` I came across the following errors.
```
Error: app/styles/main.scss
Error: It's not clear which file to import for:

- @import "datetimepicker

- @import "skins/skin-blue"

- @import "default-skin/default-skin"
```
this is because of the presence of file `X.css` and `_X.scss`.
Either we add this all in the readme.md file or can remove it so as to have low conflicts.

**Comment by aneeshd16** [comment]
@SilentFlame This should have been fixed via 086e7b55e174a0bed287e86c70bc806408b678c0. Please pull the new changes and try again. You might also need to do a `npm install` to update the libraries.

**Comment by SilentFlame** [comment]
That's great, Let me try then.

**Comment by SilentFlame** [comment]
Ok this works fine. 
closing this Isuue.
