### ISSUE TITLE
getting problems with running webclient locally.

### ISSUE THREAD

**Issue by SilentFlame** [loklak/loklak_webclient#574]
Home page works fine.
![pic01](https://cloud.githubusercontent.com/assets/9693795/13577652/88d078a8-e4b9-11e5-8725-d995d4ceae50.png)
some problem with the report page.
![pic02](https://cloud.githubusercontent.com/assets/9693795/13577669/9b3ad0b0-e4b9-11e5-9af0-e99d29fe4f7b.png)
Twitter walls are empty every other times I visit this.
![pic03](https://cloud.githubusercontent.com/assets/9693795/13577701/c2cd5ec2-e4b9-11e5-9345-6e9cece3d320.png)
No idea whats going on the connect page.
![pic04](https://cloud.githubusercontent.com/assets/9693795/13577709/d5cc029e-e4b9-11e5-8e5b-c4d74eaae726.png)

Please help me to get going. any sort of help appriciated.

**Comment by aneeshd16** [comment]
You also need to have the loklak server running

**Comment by SilentFlame** [comment]
@aneeshd16 doesn't the `gulp-dev` runs one server for itself?

Let me try once. Thanks

**Comment by SilentFlame** [comment]
@aneeshd16 do I need to change the port for loklak_server?

**Comment by aneeshd16** [comment]
Have you made a custom_configFile.json? That file should contain all configuration options including server urls and ports. If you make a copy of configFile.json, it should have the correct default values.

**Comment by SilentFlame** [comment]
ya  I do made it, that's why the webclient is running that way I guess.

**Comment by SilentFlame** [comment]
@aneeshd16  what are the fields which I need to change in the `custom_configFile.json` . coz now the home page is too not opening properly.

**Comment by aneeshd16** [comment]
From the docs:
> Create an twitter application at https://apps.twitter.com, remember to set the correct website url & callback url (for localhost, http://127.0.0.1/ works better), then modify custom_configFile.json: 
1. Set the twitterConsumerKey var in custom_configFile.json to set the Consumer Key (API Key) from your Twitter app 
2. Set the twitterConsumerSecret var in custom_configFile.json to set the Consumer Secret from your Twitter app
A twitter app is valid only for a domain (defined when creating the app). So the credentails above need to be changed also according to the domain (e.g. you'll need to create 2 twitter apps separately for a clone in localhost and for a clone in a remote server)

**Comment by SilentFlame** [comment]
@aneeshd16 that's all I followed but unable to follow the last point. `you'll need to create 2 twitter apps separately for a clone in localhost and for a clone in a remote server`
what exactly I have to do here?

**Comment by mariobehling** [comment]
Set up needs to be improved. This will be part of a bigger update of code. Closing this issue therefore.
