### ISSUE TITLE
Profile does not show on Reports page

### ISSUE THREAD

**Issue by akigupta131** [loklak/loklak_webclient#575]
<img width="1280" alt="screen shot 2016-03-14 at 12 12 36 pm" src="https://cloud.githubusercontent.com/assets/4313602/13736721/1c6395dc-e9dd-11e5-950b-2d291cd6f458.png">

**Comment by akigupta131** [comment]
@aneeshd16  In home page, user information is fetched from root, e.g. for User's name, `root.twitterSession.name` is used while in Report page, user data is fetched calling the user.json API. On top of that, as I can see data object does not contain user object in it. 
<img width="1280" alt="screen shot 2016-03-14 at 12 58 37 pm" src="https://cloud.githubusercontent.com/assets/4313602/13737527/0f60a6e8-e9e4-11e5-81a2-7007e222d402.png">
<img width="462" alt="screen shot 2016-03-14 at 1 03 36 pm" src="https://cloud.githubusercontent.com/assets/4313602/13737577/662d8978-e9e4-11e5-88dd-ad89267530f3.png">

**Comment by akigupta131** [comment]
Can I please get the contributor access?
Thanks

**Comment by aneeshd16** [comment]
@akigupta131 in custom_configFile.json set `domain` to `http://localhost:3000`

**Comment by akigupta131** [comment]
@aneeshd16 Already had done that.
1. Is there any documentation, where some description of what each page/feature is associated with? 
2. On the reports page, the profile box is for the user(me) or for the one I am creating report for?

**Comment by akigupta131** [comment]
Solved! Checkout the Pull Request #576

**Comment by SilentFlame** [comment]
@akigupta131 how did you got all things running?
can you help me please?
as I'm facing some problems.

**Comment by akigupta131** [comment]
@SilentFlame Documentation is really cool and straightforward. 
1. First you will have to get your loklac_server running on your machine. Follow simple [instructions](https://github.com/loklak/loklak_server#how-do-i-install-loklak-download-build-run). After this you should be able to run http://localhost:9000 successfully.
<img width="1280" alt="screen shot 2016-03-15 at 10 13 08 pm" src="https://cloud.githubusercontent.com/assets/4313602/13785591/23a4788e-eafa-11e5-9cdd-89d005336e58.png">

2. After this build loklac_webclient following [steps](https://github.com/loklak/loklak_webclient#build)
Note: Answer to your [comment](https://github.com/loklak/loklak_webclient/issues/574#issuecomment-194692572), you can proceed with one twitter app. Second one is required if you are deploying on VM or something. So you can ignore that for the time being.

From your issue #574 
1. Home works pretty well
2. On Report View, user profile was not showing but I did some workaround #576 but according to @aneeshd16, that is not to be solved that way. So let's see. And 'Sorry we did not find anyone with this account' error/issue is still there with me too. 
3. For wall view, you will have to create your twitterwall by clicking 'Create a new wall'. And that too works pretty well
4. I am also facing same problem in connect page. @aneeshd16 Can you please see that?

**Comment by SilentFlame** [comment]
@akigupta131
after Initial some tries now I'm unable to even generate the Home page well.
nothing works for me here.
![shot2](https://cloud.githubusercontent.com/assets/9693795/13788770/28cfac72-eb07-11e5-9874-be9b43e90a1d.png)
Is there a different setup if I'm behind a proxy?

unable to understand the problem.

**Comment by SilentFlame** [comment]
@aneeshd16 @akigupta131 is this might the reason?

**Comment by aneeshd16** [comment]
@SilentFlame try doing `gulp prod` once and then `gulp dev`

**Comment by SilentFlame** [comment]
@aneeshd16  the problem persists still.
any idea as if it works well behind proxies or not?

**Comment by mariobehling** [comment]
This is related to loklak server. Closing it here therefore.
