### ISSUE TITLE
Current view topnav item not being highlighted

### ISSUE THREAD

**Issue by akigupta131** [loklak/loklak_webclient#577]
<img width="1280" alt="screen shot 2016-03-15 at 2 03 02 pm" src="https://cloud.githubusercontent.com/assets/4313602/13771759/20a68ab2-eab6-11e5-9417-91a245498740.png">

This is happening in case of Report and Connect etc

**Comment by sopu** [comment]
Thanx for suggesting it @akigupta131. Working on it!

**Comment by akigupta131** [comment]
@sopu Solved! Checkout the Pull Request #578

**Comment by sopu** [comment]
:+1:

**Comment by mariobehling** [comment]
We postpone the connect feature. Closing this for now therefore.
