### ISSUE TITLE
Statistics page display only after second click on 'Search'

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#58]
The statistic page does not load upon first click on 'Search', only on second.
Steps to reproduce:
- open /statistics
- enter a search term, a start date and a end date
- click on 'Search'
-> effect: the url changes (good!) but no statistics is shown (bad!)
- don't change any settings and simply click a second time on 'Search'
-> effect: the statistics are shown

..should show when the first time search is clicked.

**Comment by aneeshd16** [comment]
@Orbiter could you please check your Network log? I've been getting `Status Code:503 your request frequency is too high errors` lately from the loklak server, making a request again is usually successful. Are you also getting 503's?

**Comment by sudheesh001** [comment]
Reproducable error. Need to search twice before the stats show up.

**Comment by Orbiter** [comment]
I close this because we are doing a redesign now an the issue does not apply any more. If the new pages show the same issue, it should be opened again.
