### ISSUE TITLE
Emoji in the tweets are too big in size

### ISSUE THREAD

**Issue by akigupta131** [loklak/loklak_webclient#585]
<img width="1280" alt="screen shot 2016-03-21 at 6 58 18 pm" src="https://cloud.githubusercontent.com/assets/4313602/13920121/5a943252-ef97-11e5-85df-90f1c988f24d.png">

**Comment by sudheesh001** [comment]
This is quite a simple fix
```
.Emoji.Emoji--forText 
```
class should have width as somewhere between 4 - 7 %

Would you like to send a pull request to fix this ?

**Comment by akigupta131** [comment]
#586

**Comment by daminisatya** [comment]
#587 587
