### ISSUE TITLE
Cannot login to web client - No connection

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#592]
![screenshot from 2016-05-13 18 25 53](https://cloud.githubusercontent.com/assets/1583873/15254681/44f7b93a-1938-11e6-829a-127297a1c950.png)

**Comment by sudheesh001** [comment]
I think this is internet connection specific, I was able to reproduce that error on a proxy connection but not on a direct mobile hotspot/noproxy internet connection. Could you retry this @mariobehling I've mentioned on gitter about the same

**Comment by mariobehling** [comment]
working again. not sure, what it was. closing it. Thanks!
