### ISSUE TITLE
remove dependency on loklak_server user accounts

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#594]
loklak_webclient shall become self-contained in the future. As far as I know there is only one dependency, the storage of twitter accounts and twitterwall specifications. This dependency shall be removed and the information shall be stored within loklak_webclient itself.

Therefore you must choose a storage solution for such information in a node application. Please discuss options and please consider to use what is already there.
Then start to implement the storage service for accounts on loklak_webclient.

**Comment by Orbiter** [comment]
@leonmak @niteshkhadanga please join in here

**Comment by sopu** [comment]
@Orbiter : "This dependency shall be removed and the information shall be stored within loklak_server itself." I dont understand this. If we are trying to make webclient self contained then all kind of info should be there only right?

**Comment by mariobehling** [comment]
@sopu The information shall be installed in the loklak webclient. Currently there are dependencies on the server. Please remove them. We need an accounting system in the web client, ACL etc.

**Comment by mariobehling** [comment]
@leonmak Could you please help with this issue?

**Comment by leonmak** [comment]
@mariobehling Sure, I didn't see the assignment before sry

**Comment by leonmak** [comment]
I'm not too experienced with user accounts, but can something like passportjs, node_acl, and mongodb for storage be considered?

**Comment by mariobehling** [comment]
@leonmak Yes, you can consider those solutions. What solution do you prefer? @sopu Any input?

**Comment by leonmak** [comment]
@mariobehling I meant using those together (passportjs for auth, node_acl for permissions, mongoose for storage), if I understand the requirements right

**Comment by leonmak** [comment]
for auth hello.js is used, I'm still trying to figure that out
