### ISSUE TITLE
Refusal to connect on SignUp with Twitter

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_webclient#595]
It's been quite a few days. Whenever it is tried to `Sign Up using Twitter` the following `loklak.net refused to connect.` error is displayed (refer screenshot attached)
Without signing in, [loklak.net](http://loklak.net/) works just fine. 
Enabling/Disabling firewall doesn't help too.

![screenshot from 2016-05-28 22 56 50](https://cloud.githubusercontent.com/assets/9291400/15628765/a072e50a-2527-11e6-91e5-aa9c62b60528.png)

**Comment by sudheesh001** [comment]
This is known issue because the server side proxy for this has stopped and crashing because an existing pm2 instance is crashing. I've tried to restore the pm2 services but they just keep erroring. Looks like it needs a clean reinstall, we'll do it soon.

@aneeshd16 Could you help a little here ?

**Comment by jig08** [comment]
@sudheesh001 @aneeshd16 
Works fine now. Closing this issue. Thanks :v:

**Comment by sudheesh001** [comment]
Resolved this yesterday.
