### ISSUE TITLE
Glitch to create reports in Loklak

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_webclient#599]
Been quite a few tries, unable to create reports by clicking `Click a new report` in [loklak.net](http://loklak.net/).

![screenshot from 2016-05-31 23 01 12](https://cloud.githubusercontent.com/assets/9291400/15684203/a9f7b228-2783-11e6-817a-853a0dffc4cb.png)

**Comment by mariobehling** [comment]
Reports will be refactured. Let's not work on the current report code.
