### ISSUE TITLE
Sign up form lacks email verification and validation

### ISSUE THREAD

**Issue by leonmak** [loklak/loklak_webclient#605]
It should use an email service to confirm registration.
Also should check register/login form for empty fields, invalid email, etc

**Comment by niteshkhadanga** [comment]
@leonmak You mean the Sign up form ?

**Comment by shivenmian** [comment]
@leonmak add a confirm password box to the signup form as well.

**Comment by mariobehling** [comment]
@shivenmian @leonmak Please keep it very simple. Many signup processes only require to enter the password once. If people put it in wrongly, they can ask for a reset link. Please let's keep it very simple.

**Comment by leonmak** [comment]
@mariobehling ok, I'll take pinterest.com as a reference.

**Comment by shivenmian** [comment]
@leonmak The current one is ok. Just remove the name field and sign up button. 

Also tell me. In this page, is "Sign Up" and "Sign In" the same thing? Because you have a "Signup with twitter" and now a "Signup with email". So I guess there's no need of having a sign-in option, is there?

**Comment by shivenmian** [comment]
@leonmak The current one is ok. Just remove the name field and confirm password.

Also tell me. In this page, is "Sign Up" and "Sign In" the same thing? Because you have a "Signup with twitter" and now a "Signup with email". So I guess there's no need of having a sign-in option, is there?

**Comment by mariobehling** [comment]
Please here add option:
*  [ ] use loklak instead of twitter
![screenshot from 2016-06-05 14 11 59](https://cloud.githubusercontent.com/assets/1583873/15805346/93a8e3b4-2b27-11e6-831a-9efff8d756e7.png)

Next steps: Support registered twitter API as soon as it is implemented.

**Comment by shivenmian** [comment]
@mariobehling Is the Sign Up option by email the same as sign in? Like for Twitter we have "Signup with Twitter" option in loklak webclient so probably it's the same thing.

**Comment by mariobehling** [comment]
@shivenmian I am getting confused with Signup or signin. There are tons of services, where you can first login with a twitter, facebook or gmail account. Then in a second step an account on the service is created. In future people can login either with their twitter, fb, g+ ID or with the email. Check out how Pinterest does it for example.

**Comment by shivenmian** [comment]
@mariobehling Even pinterest has separate Sign Up and Login. You can continue with Facebook, else, you can Sign Up with your email and create an account, and then later you just login to Pinterest with that account.

<img width="1280" alt="screen shot 2016-06-05 at 7 55 51 pm" src="https://cloud.githubusercontent.com/assets/14081800/15806028/a610ad36-2b57-11e6-85e6-c633bf2f0057.png">

**Comment by mariobehling** [comment]
Ok, so now you understand. Pinterest let's people think they can continue with their facebook ID and then prompts them to create an account and they have already all the data. This is also what we want.
