### ISSUE TITLE
Remove the name field and add sign in button 

### ISSUE THREAD

**Issue by niteshkhadanga** [loklak/loklak_webclient#606]
This issue aims to make changes to the recently updated home page by @leonmak.  As the name field is not required and the sign in button has not been added, so the former one would be removed and the latter one is to be added.

**Comment by shivenmian** [comment]
@leonmak Can you solve this? This really doesn't look like it should take so many days to do. 

Just remove the Confirm Password Field and create a small Sign In page (or you could have a Sign In button which on clicking will lead you to the Sign In page. Alternatively, you could have the Sign In page and its fields on the same dialog box in which the Sign Up fields are).

Signing In through email ID / Twitter should lead to the same account. Please refer to [Pinterest](https://www.pinterest.com/). This is due today. If you need more time (although I'm not sure this is too long a task), postpone it to Milestone 5. Thanks :)
