### ISSUE TITLE
Store wall data locally

### ISSUE THREAD

**Issue by leonmak** [loklak/loklak_webclient#609]
Currently the wall data are stored in the loklak_server through /account.json. They should be stored with the accounts locally

**Comment by mariobehling** [comment]
How do you plan to implement this? Could we store them as a json and would it make sense to work this out by implementing an wall API?

**Comment by leonmak** [comment]
Yea sry I meant using the logged in user's id to query the api

**Comment by sudheesh001** [comment]
@leonmak When you update the apps object in case there are other walls created, you need to resend the entire `json` dict to the apps object again. I think it'd be best if that's not the case. What do you think about this issue https://github.com/loklak/loklak_server/issues/558 

It's currently blocking efficient IOT implementation

**Comment by leonmak** [comment]
@sudheesh001 I think this method of bucketing the walls to each user fits the 1-to-few access pattern for now. As mentioned above, I take it that each user only has a few walls, around tens at most, so when accessing the wall route, I can query for the user, then search that user's walls. The alternative I think would be to create a collection for all the walls, then find the wall that matches both the userId and the wallId, which would be more taxing. My rationale is that comparing the number of put to the number of get requests for each wall, wouldn't there be more get requests?

**Comment by leonmak** [comment]
transferring to loklak_walls
