### ISSUE TITLE
Loklak Projects - Tweets, Wall, Search frontend

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#61]
This is a plan for summer projects for each student. Please provide input and feedback.

Project 1: Loklak Tweets (Sudheesh) - Goal of this project is to fully develop the functionality to tweet on loklak and set up loklak as a twitter app (so, we can tweet on both platform). Also implement additional features including adding attachments (images, videos, maps, location data, code e.g. pastebin like).

Project 2: Twitter Wall Frontend (Aneesh) - Implement a fully functional twitter wall and follow design patterns and functionality of existing twitter walls, e.g. http://tweetwall.com, http://www.tweetbeam.com/show?query=loklak, Also refer to https://github.com/loklak/loklak_webclient/issues/52

Project 3: Search Frontend (Phuc) - Implement a search frontend and start development by implementing features of the twitter search. And, we would like to see additional functionality for search in further miltestones.

Feature Project (Julian/Michael): Implement authentication for loklak and enable loklak to become a twitter app. 

Please start to work on your project by writing down a list of features and then adding issues with the respective labels

**Comment by Orbiter** [comment]
Project 4: Map View of messages. (Prashant Kiran) This is strongly related to https://github.com/loklak/loklak_webclient/issues/120 because its (also!) the visualization of IoT data.
