### ISSUE TITLE
all designs must display properly in very low resolutions, i.e. 1024 × 768

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#62]
When we first started the wall at ots15, the available screen resolution for the projector on a VGA cable was very limited. The wall was very messed up, full of window sliders and images moved below other design elements. This is a typical situation that you encounter when using unknown and possible old hardware during conferences. Therefore I believe its important that we have a general rule, that all designs must fit into 1024 × 768 and still look beautiful!

This means, this feature will constantly apply to all html pages that you design! For each designed page, follow the following steps:
- set your screen resolution to 1024 × 768 or re-size your browser window to that size
- test the web page and identify all bad behaviour (i.e. sliders where no should be, invisible text parts, bad formatted images etc)
- fix all cases, where this test fails on your own!

ps: never close this feature!

**Comment by mariobehling** [comment]
Other tweetwalls actually can adapt to different screen sizes. Please try to ensure this here as well.

**Comment by Orbiter** [comment]
This feature shall apply independently of time. Therefore it also applies for Milestone 1

**Comment by Orbiter** [comment]
@prasht63 I assigned this to you because you currently have the least workload. Please look around in _all_ the features and identify resizing-problems. Then, either fix them as you see them or if the issue is more complex, open an issue and assign it to the corresponding developer.

**Comment by prasht63** [comment]
Sure

**Comment by mariobehling** [comment]
@prasht63 This was assigned 10 days ago. What is the progress?

**Comment by prasht63** [comment]
Reassigning to @sudheesh001  since he is handling design issues.

**Comment by mariobehling** [comment]
@prasht63 I do not think this is well-tested yet. Please close this after checking with all kinds of designs. Please document which designs you tested the different views including search and maps.

**Comment by fuksi** [comment]
@aneeshd16, you might want to modify the width of the popup to fix in 1024 * 768 size. [Example link](http://i.imgur.com/zcsZGF6.png)

**Comment by smokingwheels** [comment]
Also try the Zoom in Function it puts the leader board etc at the bottom of the page.in 1024 X 768.
If you iframe it its ok on a webpage.
![screenshot from 2015-10-19 16_06_05](https://cloud.githubusercontent.com/assets/11748913/10572520/cca91bf4-767b-11e5-8992-8992ba6c1d08.png)

**Comment by mariobehling** [comment]
This is expected to be understood now.
