### ISSUE TITLE
Integrate a background process for loading newer tweets

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#66]
A feature taken from twitter search. Sorry for the strange language. :) It means "20 more results"

![screen shot 2015-05-21 at 12 02 03](https://cloud.githubusercontent.com/assets/6878677/7745113/57ed10d6-ffb1-11e4-8fa4-a32f90652466.png)

**Comment by mariobehling** [comment]
It does not seem to be present in the new design anymore. Could you check, please?

**Comment by fuksi** [comment]
Fixed with the new codebase change.
