### ISSUE TITLE
Filter search result by photos

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#67]

**Comment by Orbiter** [comment]
the loklak_server already provides  a filter option to produce only search results containing images: just add a " /image" to the user's query.

**Comment by fuksi** [comment]
Done with https://github.com/loklak/loklak_webclient/pull/164 , commits on 12/4

**Comment by Orbiter** [comment]
I cannot see this function any more, the twitter search result view is broken

**Comment by fuksi** [comment]
It's fixed. The cause was from an unsolved conflict in some merge, in which break the css syntax, so style wasn't included at all!
