### ISSUE TITLE
Filter by people, news, videos

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#68]
Consider more details from loklak_server

For people, need description to out put like this.
![image](https://cloud.githubusercontent.com/assets/6878677/7745324/0bf73240-ffb3-11e4-8193-fcdbc62771e8.png)

Video: Need video thumb and source  
Uutiset: Find a filter database for "news" tweets if possible

**Comment by Orbiter** [comment]
There is already a field in the json that will be filled with video links, once video links can be added through our own edit input. The field is called "videos" and will contain an array of links, like the "images" field. Same with audio, the field will be called "audio".

**Comment by Orbiter** [comment]
filtering is analogous to the '/image' modifier for video: add a ' /video' to the query to restrict the results to only tweets which contain videos.

**Comment by fuksi** [comment]
Query with `/video` does return result with status, in which most does not contain video at all, but only photos, some article link
Try for example: 
![image](https://cloud.githubusercontent.com/assets/6878677/8147678/f637a95e-1280-11e5-9abc-24ccdf91d490.png)
![image](https://cloud.githubusercontent.com/assets/6878677/8147680/0204debe-1281-11e5-98bf-17453bb47614.png)

@aneeshd16. @Orbiter would you know how it works or it is working at the moment?

If it doesn't, it's okay. I'll go with the different approach to debug the link to see if a iframe containing video can be rendered.

**Comment by Orbiter** [comment]
Its possible that video links are not recognized yet and therefore not searchable with constraints. I will have a look and fix it.

**Comment by Orbiter** [comment]
furthermore, loklak also recognizes youtube and vimeo links, attached to tweets. You must imlement a case selection where you distinguish native mp4 links and links to vimeo and youtube.

**Comment by fuksi** [comment]
Regardless of the filter, I'm using a debugging server (also a node process, is not yet included in the repo), which take the link and debug it. It can recognize videos from most of the page that support, except twitter native video. Good thing to know that loklak can recognizes server.Example of the debugging api.

http://gofullstack.me:8061/oembed?url=https://www.youtube.com/watch?v=cdG_T6ufcbE

Please comment here, when server_loklak repo is updated as well.

**Comment by Orbiter** [comment]
The feature is online http://loklak.org/api/search.json?timezoneOffset=-120&q=%2Fvideo

**Comment by Orbiter** [comment]
hint: vine.co links are now also recognized - to be embedded as well

**Comment by mariobehling** [comment]
Wow! Now we are talking! This is cool.

**Comment by fuksi** [comment]
Noted.

**Comment by fuksi** [comment]
Done with merge #192
