### ISSUE TITLE
Create a getting started view for the wall

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#71]
This view will contain all the options and customizations that can be used to create a wall.

Options offered are:
* Name of the event
* Date of the event
* Main hashtag
* Additional hashtags, keywords or @users
* Choice of 4 base layouts: list, masonry, or centre of attraction with tweet
* Choice of wall with (tweets with and without images)/(tweets with no images)/(tweets with images)
* Customization of wall colour

Will also contain a basic preview of what the wall would look like.

**Comment by aneeshd16** [comment]
Shelved temporarily.

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/8067748/51fab438-0f0d-11e5-8627-a375c604d4e2.png)
![image](https://cloud.githubusercontent.com/assets/5436027/8067754/5fe58b18-0f0d-11e5-9204-79a4698c898c.png)
![image](https://cloud.githubusercontent.com/assets/5436027/8067765/6c001bac-0f0d-11e5-89c4-dad3aa070a2b.png)

**Comment by aneeshd16** [comment]
@Orbiter , `Additional hashtags, keywords or @users` is pending support from loklak_server https://github.com/loklak/loklak_server/issues/41. All the other options have been implemented in PR https://github.com/loklak/loklak_webclient/pull/148. Can I shift the milestone?

**Comment by Orbiter** [comment]
This is unrelated to https://github.com/loklak/loklak_server/issues/41 because all the options you have must be combined in conjunction. This is the standard operator if you simply search for all the entities, separated with space which is already implemented.

**Comment by Orbiter** [comment]
However, I think your wall settings are nice!

**Comment by Orbiter** [comment]
I added a function in loklak_server which makes it possible for you to fullfill the "tweets with no images" requirement: it's now possible to add an '-' in front of all constraints (all search modifiers starting with '/') to invert the search constraint. https://github.com/loklak/loklak_server/commit/2b8759b8c9c3be65e8aed96b0c459a6abb5dcfa9

Example: you can search for images of cats using ```cat /image``` and now it is possible to search for all tweets about cats which do not have images attached with ```cat -/image```

**Comment by aneeshd16** [comment]
Awesome! I'll do the required changes shortly.

**Comment by mariobehling** [comment]
@aneeshd16 Hi, what is the status?
a) of the saved wall or beginners tab
b) of the lightbox implementation

compare e.g.
![tweetwall-0](https://cloud.githubusercontent.com/assets/1583873/8127616/95eca060-10f8-11e5-9591-2a8ebd8e8062.png)

**Comment by aneeshd16** [comment]
1. The saved walls feature will be done only after user auth is complete. We just finished auth a few hours back. In terms of design I am aiming for exactly the same design you posted. This will take a few days as I need to get acquainted with hello.js.
2. Till now, the view had been done without a lightbox (screenshots above). All that can be moved into a lightbox. Will try to do this by EOD.

**Comment by aneeshd16** [comment]
The 4th option in design->layouts will be a map. Related to #169

**Comment by aneeshd16** [comment]
LIghtbox:
![image](https://cloud.githubusercontent.com/assets/5436027/8137141/ce7fd53a-115e-11e5-820e-039b2cdc0f83.png)
![image](https://cloud.githubusercontent.com/assets/5436027/8137149/db58b5ec-115e-11e5-83c0-c0553084a4e0.png)
![image](https://cloud.githubusercontent.com/assets/5436027/8137153/e67c1ebe-115e-11e5-9b68-7d22964347b0.png)

Some small changes left. I will open a PR tomorrow.

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/8199930/35008258-14db-11e5-919b-d6b26a3f2d71.png)
![image](https://cloud.githubusercontent.com/assets/5436027/8199934/39db3566-14db-11e5-91a0-ef5dd5dc1563.png)
![image](https://cloud.githubusercontent.com/assets/5436027/8199939/3fe4bae0-14db-11e5-9bcb-8a036341f5b7.png)

Now you can open the wall configuration modal directly from the display page:
![image](https://cloud.githubusercontent.com/assets/5436027/8199967/88d59922-14db-11e5-9621-5a60f0f4a197.png)

**Comment by aneeshd16** [comment]
What's left:
* Modify design. Simplify step 2 to make it user friendly. Right now its too complex.
* Enable fields when OR support gets added on loklak server.

**Comment by aneeshd16** [comment]
Closing this since discussions have moved to #305 and #330
