### ISSUE TITLE
Implement the base layouts in the wall

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#72]
The base layouts are:
* list: linear, similar to search results
* masonry: a stacked view in which tweets are arranged in a brick like structure
* centre of attraction with tweet stream: the latest tweet occupies a large area of the screen, with a smaller section for older tweets

**Comment by aneeshd16** [comment]
Linear Layout:
![image](https://cloud.githubusercontent.com/assets/5436027/7906308/7bdc1c88-0846-11e5-92d2-d341866f7b90.png)
Need to find a way to isolate the view.

**Comment by sudheesh001** [comment]
@aneeshd16 Looks great so far, How about a small change, put the main hashtag in the center and the event name to the left side and put something like `Powered by Loklak` in the blue area at the right side with a smaller text, that'd give a beautiful UI UX when the sidebar is collapsed, Also, At the same time keep the right side of the grid like
```
| col-lg-8 | col-lg-4 |
```
We'll try to put up live visualizations over there to make the wall more attractive.

**Comment by aneeshd16** [comment]
@sudheesh001 , i want to remove the sidebar and topbar altogether for the wall. It is not required when the wall is on.

**Comment by sudheesh001** [comment]
@aneeshd16 I think opening this page with the sidebar collapsed by default should do well, the `3 bar` icon is what many users know as menu and it'd be great to have the navigation there itself than to clutter the top navigation, Lets keep the top nav bar for the user profile and different other settings or notifications.
The default collapsed view would be perfect for organizations using our tweet wall to serve as an actual wall. This way we don't have to isolate or remove components, we'd be just using it in a different way, what do you think about that ?

**Comment by aneeshd16** [comment]
I was basically aiming for this
![image](https://cloud.githubusercontent.com/assets/5436027/7906943/5c0a5ab4-0850-11e5-96dd-612d508c1c4b.png)

Having a clean view without navigational links. When running in kiosk mode, on a big screen, navigation is not really necessary and adds some clutter. What do you think?

**Comment by mariobehling** [comment]
@sudheesh001 @aneeshd16 Let's think about the use case: The wall should work for logged in user and for anonymous users. You can have an event with several walls in different rooms and you want your tweet wall to be displayed everywhere. It is not necessary to login. How can we make this unique? How do others do this? On tweetwall.com they do a subdomain for example e.g. xyzevent.tweetwall.com. What can we do? How do we implement the configuration of the wall?

**Comment by aneeshd16** [comment]
@mariobehling , since we are starting with only anonymous users, (Authenticated users are in milestone 2), I propose we put all the parameters in the URL.
`/wall/display?eventName=abcd&mainHashtag=loklak...`
The URL would look very messy, but since it will be running in full screen, it wont be visible.

**Comment by sudheesh001** [comment]
@aneeshd16 That's exactly how I wanted it to be too. the right side instead of leaderboard lets have piecharts / other visualizations.
@mariobehling I think using `/wall?event=fossasia&hashtag=fossasia` would serve this purpose.

How about providing the wall with the functionality from the authenticated user to control the wall settings or use different widgets, One great plugin most conferences need is the `Next speaker` or `Next Event/Workshop` So yes, we need to decide on who controls the view of that page in case we wish to implement this, I suggest that the same wall have 2 seperate routes, one authenticated and one public, spewing out the same results to the end user but with differences of being authenticated.

`/wall?event=fossasia&hashtag=fossasia` for the wall thats being projected and a panel at `wall/manage/?event=fossasia&hashtag=fossasia` so that changes can be made. This probably aligns with @Orbiter in one of the discussions we were having on `loklak_server` on profanity filtering where he suggested that this option be given to the user/manager of the wall.

**Comment by mariobehling** [comment]
@aneeshd16 This is a nice feature, but how can I go back later and change the wall? I can do it in the URL, but most users won't be aware and know how to do it. Maybe something like an autohiding top bar would be good and a link "Wall Preferences".

**Comment by aneeshd16** [comment]
Exactly. On the same page, there will be maybe a gear icon somewhere, which will lead back to the configuration screen.

**Comment by mariobehling** [comment]
@sudheesh001 Yes, we want widgets to choose from on the leaderboard. That is the idea. Regarding anonymous and logged in users. The wall is already defined through the URL. For logged in users we can have the option "save wall" and provide them with a shorter URL, that they can share.

So, for the question "who controls the view", it does not matter, cause it is defined in the URL.

**Comment by sudheesh001** [comment]
so @aneeshd16 Are you suggesting that we offer the gear option for preferences for the application to any of the authenticated users or owner to one specific user ? Are we going to dedicate a specific /wall to a user so that only he/she can make the preference changes ?

Why not going for this instead ? `/username/wall?`
That way the wall can be accessed by the username and is registered to them whereas the same publicly can be accessed to `/wall?event=`

**Comment by mariobehling** [comment]
@aneeshd16 In the URL maybe instead of the eventname, we should have a unique ID number here. Also, we can also imagine a wall for other use cases, not just events. Think of advertising, company walls, sports etc.

**Comment by aneeshd16** [comment]
Both authenticated and anon users will get the same wall and same url. Only difference will be that authenticated users will be able to save that URL with their account. How's that sound?

**Comment by mariobehling** [comment]
@aneeshd16 sounds good to me. And a future feature is a unique URL they can save as well.

**Comment by aneeshd16** [comment]
1. @mariobehling , the string "Event Name" will not be displayed on the wall. Users can enter whatever they want in the `eventName` and even leave it blank.

For eg: If i enter "This is my wall" in `eventName`, it wont be displayed as 
`Event Name: This is my wall`
It will be displayed only as
`This is my wall`.

In this way, the `eventName` field can contain the name of a brand, product, company or any other random string.

The field `eventName` should be renamed to something more intuitive to facilitate this.

2)For authenticated users, we can perhaps have a short url that redirects to the main url. For eg:
`/wall/display?id=some_id` will redirect to` /wall/display?eventName=abcd&mainHashtag=loklak...`

**Comment by mariobehling** [comment]
@aneeshd16 
1. The question is then what is the unique URL? There must be one unique identifier in the URL. The unique identifier should be a number, that is generated in the system. Several different events, brands, products can have the same name in different countries. So the name should not be the unique identifier. I also prefer to avoid "eventName" as we are not only targetting events. If possible, just name it "name" or "id", please.
2. Is a feature, we should think in a separate thread. This can be a pro-feature as well.

**Comment by aneeshd16** [comment]
Why do need an unique URL? If all the parameter fields are same, then the same wall will be displayed, irrespective of who creates it. And that is the desired result, I guess.

I think I am missing your point on this though :)

**Comment by mariobehling** [comment]
I was following other thoughts - that you generate an id based on the name of the event. Ok, got it now. Ok, good idea, excited to see the result!

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/8199954/6ea794ec-14db-11e5-9e77-f55891b844d9.png)
![image](https://cloud.githubusercontent.com/assets/5436027/8199956/749243e8-14db-11e5-976b-b6be58c95dae.png)
Added a full screen button that toggles full screen view.

The wall config modal can be directly opened from the display page: https://github.com/loklak/loklak_webclient/issues/71#issuecomment-112652698

**Comment by aneeshd16** [comment]
Can we close this? This has been solved by https://github.com/loklak/loklak_webclient/pull/191
