### ISSUE TITLE
Show statistics in the wall

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#73]
A toggle should control the display of a statistics view which would appear in a sidebar. Will contain "top twitterers", "top mentions", "top hashtags" and a histogram(if possible).
From #37

**Comment by aneeshd16** [comment]
Blocker:
In the wall, two types of requests are being sent. One for the tweets to show in the wall, the other for showing statistics in the wall (if enabled by the user). Both are JSONP requests. The trouble is that Angular requires a hardcoded callback parameter called "JSON_CALLBACK". So whenever I called the two request methods, the first request's callback got called with the second requests parameters. This resulted in the tweets been shown only once. Now I can do two things here
* Send the search and statistics requests at the same time, and use $q.all to get a promise that's resolved when both requests are complete. However, I do not know if this will be able to handle the multiple JSONP requests as well.
* Make a custom http interceptor that will allow me to use a different JSONP callback. http://stackoverflow.com/a/25406041/2463357 This might affect other functions which rely on the service as well, so i'll have to do some testing.

**Comment by Orbiter** [comment]
I cannot reproduce the problem. Just call this:
```
http://loklak.org/api/search.json?q=fossasia&source=cache&callback=JSON_CALLBACK
```
and you get what you need. Please post the urls which do not work here.

**Comment by aneeshd16** [comment]
@Orbiter, the URLs work perfectly fine. For eg:
For search, i have `/search.json?q=loklak&callback=JSON_CALLBACK`
For statistics, I have `/search.json?q=loklak&source=cache&count=0&fields=created_at,screen_name,mentions,hashtags&callback=JSON_CALLBACK`
Both URLs work perfectly fine independently. However since the `callback` parameter for both requests is `JSON_CALLBACK`, when I send the second request, the callback function of the first request is called. Unfortunately, angular requires that the `callback` parameter for jsonp requests should always be `JSON_CALLBACK` and I cant pass any custom name. I am working on implementing the custom interceptor, let's hope it works.

**Comment by prasht63** [comment]
Angular's $http.jsonp converts the request querystring parameter from callback=JSON_CALLBACK to callback=angular.callbacks._0.
you can add id at the end like
angular.callbacks._1 and use it as a separate callback parameter instead of using JSON_CALLBACK
Try it, it should do

**Comment by aneeshd16** [comment]
Blocker solved by https://github.com/loklak/loklak_webclient/commit/5fc3cc82da159773629195f2d05a2953b206a702. Manually constructed the URL instead of passing parameters.

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/8292485/8b90ef06-194d-11e5-8db1-4c93da488b57.png)

**Comment by sudheesh001** [comment]
This looks nice. A few ideas
- For piecharts you can show the labels inside the chart itself, here's a sample http://jsfiddle.net/wbkwdn79/
- I think using piecharts would be nice here as a widget below the `Leaderboard`.
- Can we make the bar chart spannable, so that it could hold more values and people could drag it left and right, i don't know if its possible but that kind of an interaction would solve that problem of unreadable charts when there's a lot of info.

**Comment by mariobehling** [comment]
@aneeshd16 Good job! Two things:
* Please add a "#" in front of the hashtags
* The leaderboard should animate people to tweet. So, we need a list of people with a photo. Think of gamification! Everyone wants to be the first.
![leaderboard](https://cloud.githubusercontent.com/assets/1583873/8300977/a64e4874-198a-11e5-8733-fc088e2ce6f9.jpg)

@sudheesh001 The wall is mainly intended to work without user interaction. Regarding pie charts - it is only useful, if we have very few items. The text will probably be too small.

**Comment by aneeshd16** [comment]
@mariobehling, correct the pie charts are too small and the text is unreadable. Loklak server doesn't give profile image urls in its aggregations object, but I can think of a workaround for that.
Will add the '#' in front of hashtags.

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/8314123/0ec85ca8-1a05-11e5-80e5-ad4b9204c5e7.png)

**Comment by mariobehling** [comment]
@aneeshd16 Veru nice. Let's increase the size of the fonts of people in the leaderboard a bit. Do you have an idea how to show the date in the tweet frequency in a shorter forms, so it does not use so much space?

**Comment by mariobehling** [comment]
@aneeshd16 What if people actually only use the twitterwall one day? Will the tweet frequency show up per hour? Or what if they use it one year. Then does it show up per month?

**Comment by aneeshd16** [comment]
Yes, i was thinking the same about the font size.
About your second question, loklak server handles all that automatically. From the docs:
`A special field is the "created_at" field which will create a date histogram if listed in the GET-attribute 'fields'. The date histogram resolution depends on the time frame as given in the query modifer with the 'since' and 'until' time limits: minutes if the time frame is below three hours, hours if the time frame is below seven days and days otherwise. `

The `since` and `until` fields are key here. A user can set them while creating a tweet wall. (Related: Also need to inform the user what these fields are actually doing)

So, in answer to your first question, if the time frame is short and server is returning time values, then we can show only the time. Else we can show the month and date, and ignore the year. As of now, only the last 25 values are shown on the graph. There might be better way to show this data rather than just taking the last 25 values, I will read up on this. The graph is too dense as it is, and showing more values will result in something like this:
![image](https://cloud.githubusercontent.com/assets/2913409/5914618/f7b47330-a61e-11e4-93ce-4c66b1608ee6.png)

**Comment by mariobehling** [comment]
Eager to see the remaining options being implemented.

**Comment by aneeshd16** [comment]
With the current view, there is no space to show "top mentions". Squeezing it alongside top twitterers and top hashtags will be too congested. Either we can drop "top mentions" altogether or squeeze it somewhere between the leaderboard and histogram. Frankly, I don't see how that can be done.

Another option is to have the user choose what to show on the wall. Any two options from - top twitterers, top hashtags or top mentions.

Thoughts?

**Comment by mariobehling** [comment]
> Another option is to have the user choose what to show on the wall. Any two options from - top twitterers, top hashtags or top mentions.

Yes, I see you understand where we want to go -> towards widgetization. Let the users choose. We can do this later like Wordpress does it. The user can drag and drop widgets. For now just make it simple, please.

**Comment by aneeshd16** [comment]
Okay, we won't show "top mentions" for now.

Regarding the histogram, I will be implementing histogram binning, which will be a better representation of the data rather than showing just the last 25 points.
