### ISSUE TITLE
loklak twitter wall frontend

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#75]
Create a list of features and add information about technology and milestones. Please include the following:

a) Feature List (add it to Feature.md)
b) Project Plan with possible milestones (Which features will be implemented at what time)
c) Technologies used

Proposed Milestones

    Milestone 1, Due by June 10, 2015
    Milestone 2, Due by June 26, 2015
    Milestone 3, Due by July 25, 2015
    Milestone 4, Due by August 21, 2015

also refer to https://github.com/loklak/loklak_webclient/issues/61

**Comment by aneeshd16** [comment]
Milestone 1: (main objective is to get a minimal wall working)
* Set up a landing page for the wall (#70)
* Set up a getting started page that will ask the user for options and create the wall accordingly (#71)
* Create a base layout. (#72). I would start with implementing the linear (list) layout first, and then other layouts if possible within the timeline.

Milestone 2: (Personalization)
* Users can log in with their twitter accounts (#74)
* Ability to store created twitter walls with the account (#102)
* Dashboard view for wall users (#103)

Milestone 3: (Control)
The major use case of the twitter wall is for event managers to project the wall on a large screen.
* Event Manager should have more control over what tweets are displayed.
* Filter tweets by location
* Block tweets based on a profanity filter.
* Promote tweets from certain accounts
* Control should be available from a separate window. The twitter wall need not be stopped to make changes. The wall will automatically update itself with the new changes.

Milestone 4: (Mobile and other Misc features)
* Enable a basic wall that can be viewed on mobile comfortably.
* (to be updated)

**Comment by mariobehling** [comment]
Please add details and a list for feature issues for the milestones until 4.5
 Milestone 3, Due by July 25, 2015
 Milestone 3.5 Sprint, Due by August 12, 2015 
 Milestone 4, Due by August 21, 2015
 Milestone 4.5, Due by August 31, 2015

**Comment by aneeshd16** [comment]
Will update by Wednesday (15th).
