### ISSUE TITLE
feature: search url with query in path

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#8]
It should be possible to mention loklak with links to search result pages. Therefore the search result page must be called with http-GET containing submitted attributes in the url as properties.

The twitter search page is at /search, we could use the same path. Lets use urls like
/search?q=fossasia&timezoneOffset=-120

**Comment by Orbiter** [comment]
this one is similar to the statistiscs page

**Comment by fuksi** [comment]
Done and merged in 8665b76cefb9844a5e0dd82a96dbc0932bd40510
