### ISSUE TITLE
Move keys and other sensitive application related information to a separate config file

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#83]
As of now we have a naming convention of `custom_configFile.json`. So this config file deals with the front end, Inside the `server/` we need to have another config file for the twitter app details and stuff, for convention sake let us call it `config.temp.json` with the instruction to be

`cp server/serverconfig.temp.json server/serverconfig.json`, Needs to be implemented with #80 as discussed.

**Comment by aneeshd16** [comment]
Used custom_configFile.json to store the keys.

**Comment by sudheesh001** [comment]
a8aa6e6 needs to ensure that the server is always run as
```
loklak_webclient $ node server/index.js
```
and cannot work through
```
loklak_webclient/server $ node index.js
```
results in throw of
```
ENOENT, stat '/path/loklak_webclient/server/build/index.html'
```
We need to fix this for later too if possible or start the node server through a shell command from the application root than from a folder.

**Comment by sudheesh001** [comment]
Closed as Fixed.
