### ISSUE TITLE
Integrate search view AdminLTE theme.

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#88]
Discuss with others what's the role of Navbar, Sidebar, and UserSetting of the AdminLTE, and integrate the search view accordingly.

**Comment by mariobehling** [comment]
Updating on the status as discussed on twitter. Awesome!
![screen-shot-2015-05-23-at-7 21 55-pm](https://cloud.githubusercontent.com/assets/1583873/7893758/3857a11c-0661-11e5-9b0d-69027bd3ac6a.png)
![screen-shot-2015-05-23-at-7 22 15-pm](https://cloud.githubusercontent.com/assets/1583873/7893759/388bdcc0-0661-11e5-90b5-f8527e12bfea.png)
![screen-shot-2015-05-23-at-7 23 07-pm](https://cloud.githubusercontent.com/assets/1583873/7893760/388f1e26-0661-11e5-9004-a1c591b3b389.png)

**Comment by sudheesh001** [comment]
@fuksi Amazing work. It looks beautifully flat now :heart_eyes:
