### ISSUE TITLE
Create a framework page for message evaluation widgets

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#9]
The context of this feature is described in https://groups.google.com/d/msg/loklak/7azwyuslmTU/JXh0vrgXhSAJ

There should be a framework page for histogram and statistic table widgets. The feature requests for these widgets are in separate issues. The result should look like:

![message_evaluation_sketch](https://cloud.githubusercontent.com/assets/238730/7424468/b3fea152-efa1-11e4-8c6d-8bc85c093178.png)

To get to this page, the user must be able to enter a search term, a start date and an end date. The back-end retrieval api needs also a timezoneOffset, which can be retrieved from the browser with JavaScript. The input box to enter a search term and the dates should be on the same page as the result graphics. Please use the path /eval.html?q= with similar attributes like the search page.

**Comment by fuksi** [comment]
Is anyone already working on this? If not I'm assigning it to myself.

**Comment by Orbiter** [comment]
thats the right spirit!

**Comment by Orbiter** [comment]
you probably need input from the feature assignees of
https://github.com/loklak/loklak_webclient/issues/11 and
https://github.com/loklak/loklak_webclient/issues/10
Please get in contact and try to organize together what you need from each other

**Comment by Orbiter** [comment]
thank you, good work!
