### ISSUE TITLE
Enable all filters and advanced search

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_webclient#90]
List all filters and advanced search filters when pass Milestone 1

**Comment by mariobehling** [comment]
Add link to "more options"
![search-adv-link](https://cloud.githubusercontent.com/assets/1583873/8133841/efbfdb20-112a-11e5-8cb3-47f493b3a98a.png)

And set up page with search parameters
![advanced-search](https://cloud.githubusercontent.com/assets/1583873/8133845/fafad486-112a-11e5-81e9-f500c6f12f69.png)

**Comment by fuksi** [comment]
Before advancing with this, I want to confirm available features from the search API (so I can try to implement the rest manually the from raw result). Please tick the feature which is working/available and if it does work, give an quick example in the comment. 

- [ ] Count
Changing the number of count in query is not valid at the moment.In the result, the changed field is `itemsPerPage`, but it is not effective either.
http://loklak.org/api/search.json?timezoneOffset=-180&q=%23loklak&count=5  

- [ ] from:user && a term
Getting statuses from a user, or, a search term is possible. However both at the same is not available, e.g. `from:phucdn2005+#loklak`. I can of course manually do a cross check of both search, but the result won't be as many.

- [ ] near:location && a term
Similar to above
- [ ] since & until  
This is not working: 
http://loklak.org/api/search.json?q=loklak%20since:2015-04-01%20until:2015-06-06


If it seems that multiple queries for one search is inevitable with advanced search like this, is it possible provide an option from the server to enable consecutive queries from the client (to prevent the blocking from high frequency)?

**Comment by mariobehling** [comment]
@Orbiter I think you should be able to answer this.

**Comment by Orbiter** [comment]
these had beed actual bugs, some of them introduced lately (since & until was working before). I fixed them right now.

**Comment by mariobehling** [comment]
Very good outcome. Please also ensure, that the search string shows up in the search box when you show the outcome and show the final result in the standard search output page (similar to twitter).

![adv-search-output](https://cloud.githubusercontent.com/assets/1583873/8323664/d695c5d0-1a47-11e5-9410-2c763528f3ef.png)

**Comment by mariobehling** [comment]
Please change the time search from to since xxxx until xxxx in loklak
![since-until](https://cloud.githubusercontent.com/assets/1583873/8323683/19413e64-1a48-11e5-85e9-483a7b88064e.png)

**Comment by mariobehling** [comment]
Tried to add different search terms, but could not add current date, as I could not scoll anymore. ![cannot scroll](https://cloud.githubusercontent.com/assets/1583873/8323749/cedd9236-1a48-11e5-9c1c-7aff11315b20.png)

**Comment by mariobehling** [comment]
When I enter lots of different options, I only get results back for the keyword.

**Comment by Orbiter** [comment]
@mariobehling https://github.com/loklak/loklak_webclient/issues/90#issuecomment-114740244  `from: ` is already a keyword to search for tweets from a specific user. That word can therefore not be used for date ranges. I therefore choosed `since:` and `until:`

**Comment by Orbiter** [comment]
the OR operand is now available, like `berlin OR frankfurt`. The operand works currently not in combination with explicit AND (like ` AND ` in query) or implicit AND (space). I made a quick-and-dirty implementation which will at least support OR usage in wall which is necessary for queries like `ots15 OR ots2015`

**Comment by mariobehling** [comment]
@Orbiter @fuksi Please change "since... since..." to "since... until...."

**Comment by Orbiter** [comment]
?

**Comment by fuksi** [comment]
- Added new behavior with operands "OR". 
  - Fixed typo "since ... until", fixed minor styles
  - Added new behavior for location search, using `/location...` feature from the server  

[Visit the PR for more info](https://github.com/loklak/loklak_webclient/pull/213#issue-90517783)

**Comment by fuksi** [comment]
@Orbiter, please open this again, when any new features are available from server :+1:

**Comment by mariobehling** [comment]
Let's use the standard search layout with advanced search. Or do you have another suggestion? 

![screenshot from 2015-06-26 19 35 48](https://cloud.githubusercontent.com/assets/1583873/8383456/afc3d40c-1c3a-11e5-8e8c-b22c77bd731e.png)
![screenshot from 2015-06-26 19 35 34](https://cloud.githubusercontent.com/assets/1583873/8383457/afca6916-1c3a-11e5-9551-6b6d862a14db.png)

**Comment by mariobehling** [comment]
* [ ] Please make two location buttons into one. Let's make it easier for the user to make less clicks.
(compare with twitter)
![screenshot from 2015-07-02 15 30 43](https://cloud.githubusercontent.com/assets/1583873/8478094/7cd0a716-20cf-11e5-971e-d4d7aa02899c.png)

![screenshot from 2015-07-02 15 27 16](https://cloud.githubusercontent.com/assets/1583873/8478095/7cece994-20cf-11e5-8ca2-3f158d638533.png)

**Comment by fuksi** [comment]
This will be changed along with #227
