### ISSUE TITLE
POST tweets to twitter after user authentication from the loklak app

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#92]

**Comment by mariobehling** [comment]
@sudheesh001 I do not find an issue where you implement authentication for loklak. Am I missing something? What is the status on authentication?

**Comment by mariobehling** [comment]
Related issue https://github.com/loklak/loklak_webclient/issues/138

**Comment by sudheesh001** [comment]
@mariobehling Authentication and getting the basic server was implemented by me and Aneesh since most of it was overlapping work. Once that was complete, that patch fixes the ability to post to twitter.

**Comment by mariobehling** [comment]
@sudheesh001 Where can I try that out? Did you contribute that to main? Please set up a client on a server of yourself, where everyone can try out your current developments.

**Comment by sudheesh001** [comment]
Yes @mariobehling It's already present in the main
bf72c93608e4d20512d9fb0dcefd2d79754c066c
0678b3f5196470f9b366c14141cf909bf6850bca
373df97ff4801a0eb482aa02ceeab82a89caea08 (Patched it together that night, Auth layer here)

**Comment by mariobehling** [comment]
Where can I try out this feature? Where is a button to tweet in the interface?

**Comment by fuksi** [comment]
Hi, I had my time researching for the solution for authentification and here it is:

About the current solution: 
- Authentification is served in a different node server (```/search```, ```/view```.. are different from ```/account```, ```/auth/twittet```
- Authenticated session has effect only in that server and its view 
- We can't integrate angular with this server.

To have authentifcation in our SPA application without a middle layer we'd have to:
- Expose application public/secret key on the client files (no good)
- Do OAuth manually with twitter, which is cubersome. 

If we use a middle layer, either we use service, e.g. [Oauth.io](https://oauth.io/home), or we create the service ourselves. I have an live example herer that use Oauth.io (2000 free oauth req/month, I guess we can live with that for now?)
- When we use a middle layer, we don't have to expose public/secret key of the twitter app (**Yay**)
- Do OAuth is much easier, and not just twitter (I'll discuss about code later)

Check the live example and tell me what you think? http://46.101.145.49/

**Comment by mariobehling** [comment]
@sudheesh001 the questions and discussions on this issue are ongoing. So, I am reopening this issue. What is your feedback on @fuksi's comments?

Please also add a tweet button to the top right and a light box for tweeting like at twitter.

Please take out the text on the page 

> "Feel like telling the world about something ? Why not start here ? Share your tweet !! We are planning to support you to post as many words as you want to twitter ! Support us on Github"

Please follow the design of twitter and show the tweets of the accounts the user follows. See below: 
![loklak-home](https://cloud.githubusercontent.com/assets/1583873/8107965/b4e56f98-104d-11e5-8291-97fc4a547d52.png)

**Comment by sudheesh001** [comment]
Moving to @prasht63 temporarily until complete design changes are made.

**Comment by mariobehling** [comment]
@prasht63 This was assigned 6 days ago. What is the progress?

**Comment by sudheesh001** [comment]
@mariobehling Prashant has sent a PR https://github.com/loklak/loklak_webclient/pull/204 It needs a few fixes

**Comment by mariobehling** [comment]
@prasht63 @sudheesh001 Please actively use the issue tracker and provide updates here. Some things might have been mentioned on the chat, but "chatting" and keeping a history in the issue tracker are two different things. We need to be able to follow the developments here.
