### ISSUE TITLE
Implement tweets with geo tagging and post to twitter (just like twitter)

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#93]
- Add geolocations to tweets
- Fetch both the geo tag hash and the actual  location and also POST it to the loklak_server
- Alternatively let the user choose the location

Added by Mario: This functionality is identical to the way twitters displays location information for tweets.

@Orbiter , In case I get the locations of the tweets from twitter, it can be retrieved in both the hash format as well as the plain text format, we were having trouble last time to unhash the hash as discussed and i proposed [this](https://gist.github.com/sudheesh001/ee26ba3cf8bf07425d54) as a possible solution, I was rather thinking to use the `id_str` value of the tweet and is it possible to send the hash as well as the plain text back to the server for storing it there in the same tweet object ? Also in case the database has the mapping between hashes and locations would it get easier for us in the long run to automatically detect the location without having twitter to give it to us from the existing hash set

**Comment by Orbiter** [comment]
The Google service for location resolution from the name is too fuzzy and it is also a bad dependency for loklak. Here is what I propose to attach exact locations to loklak rich messages:

- we must be compatible to 'normal' twitter tweets
- we therefore must add exact location information within the tweet text
- we therefore need a syntax to express exact locations
- an openstreetmap url provides a standard form to set markers on a map, like:
www.openstreetmap.org/?mlat=1.28376&mlon=103.84371
- the marker takes less space in the tweet since it is shortened (by twitter)
- when you send the tweet, you can send along the location lat=1.28376, lon=103.84371 to twitter which will hopefully show up in twitter as "Singapore, Chinatown"
- when we render the tweet, we detect the openstreetmap url and show a map with the coordinates and zoomed in with factor 19, like http://www.openstreetmap.org/?mlat=1.28376&mlon=103.84371#map=19/1.28376/103.84369

**Comment by Orbiter** [comment]
this affects https://github.com/loklak/loklak_webclient/issues/100 - please share the work for the display of geotagged tweets

**Comment by sudheesh001** [comment]
@Orbiter I am currently encountering 404 errors on
`http://loklak.org/vis/map.png?text=Test&mlat=1.28373&mlon=103.84379&zoom=18&width=512&height=256`

**Comment by Orbiter** [comment]
the peer was not upgraded. now its working

**Comment by Orbiter** [comment]
please start working on this!

**Comment by sudheesh001** [comment]
Moving to @prasht63 temporarily so that I can work on the new stable design.

**Comment by mariobehling** [comment]
@prasht63 This was assigned 6 days ago. What is the progress?

**Comment by prasht63** [comment]
@loklak/loklak_developers I am facing a blocker over here.With hello.js I am not able to send image with the tweet which is required for this feature. 
Hello.js  me/share POST request has two parameters 
``` hello('twitter').api('me/share', 'POST', {
        message : tweet ,
        file : files
    }).then(log,log);
```
Here the message will contain the tweet text and the file contains the image data. 
Now for this feature the server provides the image as http://loklak.org/vis/map.png?text=Test&mlat=1.28373&mlon=103.84379&zoom=18&width=512&height=256 . However the file parameter should be in html formdata file format. I have tried converting the image to formdata format taking help from here http://stackoverflow.com/questions/4998908/convert-data-uri-to-file-then-append-to-formdata but apparently Hello.js does not recognise it.
We have two options now
1.We can solve this by using a <input type=file> tag in the form which will ask the user to enter the data but that is so against usability.
2.We try to encode the image data such that it can be accepted by hello.js

Any help will be appreciated.

**Comment by prasht63** [comment]
I was trying to set the form data manually but that can't be done due to security reasons.
http://stackoverflow.com/questions/1696877/how-to-set-a-value-to-a-file-input-in-html
Does anybody have any other workaround.

**Comment by prasht63** [comment]
I have incorporated get Location with the new twitter design.Preview 
![image](https://cloud.githubusercontent.com/assets/2105062/8348883/d9f14b3e-1b35-11e5-970c-f6e4ebdb26c6.png)
However I am still facing the blocker described above.

**Comment by mariobehling** [comment]
Where can we test it?

**Comment by Orbiter** [comment]
@prasht63 regarding https://github.com/loklak/loklak_webclient/issues/93#issuecomment-114548974 do you mean http-post form-data? Thats not a specific image encoding, thats a http request format. I don't see any way to do a 'form-data' output of the image because there is no such thing. Is this maybe simply a misunderstanding of the problem?

**Comment by prasht63** [comment]
@mariobehling I am deploying it on my test server.I will update with link.
@Orbiter Problem is with hello.js limitations.Hello.js does something like this to send a image with tweet.
```
<input type="file" id="image"></input> // this lets you upload a image from computer
<script>
imagefile=document.getElementById("image").files[0]
hello('twitter').api('me/share', 'POST', {
        message : tweet ,
        file : imagefile
    }).then(log,log);
</script>

```
The problem is we have our location tile image as URL while hello.js supports through fie upload.

**Comment by Orbiter** [comment]
yes then you must download the image first before uploading that with hello.js. Is that not possible with javascript? I believe it should be.

**Comment by prasht63** [comment]
We can not upload the image through Javascript.That is disabled due to security reasons.Refer https://github.com/loklak/loklak_webclient/issues/93#issuecomment-114939710 .Only the user can.

**Comment by mariobehling** [comment]
@sudheesh001 As @prasht63 has a lot of IoT tasks, please take over this task again. Cheers.

**Comment by sudheesh001** [comment]
@mariobehling Sure :smile:

**Comment by sudheesh001** [comment]
@prasht63 Can you send the diff of the code you have so far on the branch related to this issue

**Comment by prasht63** [comment]
https://github.com/loklak/loklak_webclient/tree/Issue/%2393 has work done till now. Currently on clicking get location in the tweet modal, a location tile is displayed just below the tweet textarea.See preview above.

**Comment by mariobehling** [comment]
Regarding CORS @Orbiter made this comment in the gitter channel 

> CORS is ONLY necessary for JS loading external resources from OTHER domains. Both is not the case here. There should not be problem and implementing CORS would not solve it, it furthermore would open a problem.
Please correct me if I am wrong. But I don’t see it.

**Comment by mariobehling** [comment]
@sudheesh001 I have not seen a message from your about that. Any feedback?

**Comment by sudheesh001** [comment]
Sending a header along with the `$http` request which is can be done by breaking the current request into 
```js
var req = {
 method: 'GET',
 url: 'http://localhost:9000/',
 headers: {
   'Content-Type': undefined
 },
 data: { test: 'test' }
}
```
but sending a header specifically is failing and still throwing up an XHR error on CORS as mentioned above.

**Comment by Orbiter** [comment]
I just added the CORS header in https://github.com/loklak/loklak_server/commit/be178b1f151da241cd71e232f078214afc2ebf6c
I'm still not convinced that we will need that in future production, but right now you are right: it's needed since in test environments the server ports of loklak_webclient and loklak_server are different.

**Comment by sudheesh001** [comment]
Moving this to M3 because its a subset of #97

**Comment by fuksi** [comment]
Please refer back to #100 when this is done, along with a query example results in a status with the rich content mentioned on top.

**Comment by mariobehling** [comment]
Still does not work for me

Step 1: I click "location"
![screenshot from 2015-08-01 08 32 01](https://cloud.githubusercontent.com/assets/1583873/9020909/46aa9492-3828-11e5-9ae4-fc326df92ffe.png)

Step 2: I activate share location
![screenshot from 2015-08-01 08 32 47](https://cloud.githubusercontent.com/assets/1583873/9020910/57079c0e-3828-11e5-9a9e-6de68c07e6ee.png)

Step 3: Nothing happens

**Comment by mariobehling** [comment]
Just to clear this up: There are two distinct features
1. An "Add location" service, which is exactly the same as twitters "add location" to a tweet
2. An Attach map function, which is just like attaching an image to a tweet, but we attach an embedded map, that we show in loklak tweets (and we generate a photo for twitter when we crosspost it to twitter) Map attachments are discussed here: https://github.com/loklak/loklak_webclient/issues/97

**Comment by sudheesh001** [comment]
Fixes https://github.com/loklak/loklak_webclient/issues/357 and https://github.com/loklak/loklak_webclient/issues/93   Fixed with https://github.com/loklak/loklak_webclient/commit/9133cb5833d3e21dbab941de080282575b3ddd72

1. Get location
<img width="605" alt="screen shot 2015-08-01 at 3 52 02 pm" src="https://cloud.githubusercontent.com/assets/4545925/9021563/eb6978ee-3865-11e5-825d-86329b896701.png">

2. Allow access to share
<img width="375" alt="screen shot 2015-08-01 at 3 52 10 pm" src="https://cloud.githubusercontent.com/assets/4545925/9021564/f06b651e-3865-11e5-8542-0bdfb10867bb.png">

3. See the name of the place where you're posting from.
<img width="601" alt="screen shot 2015-08-01 at 3 52 30 pm" src="https://cloud.githubusercontent.com/assets/4545925/9021567/f9ac07c8-3865-11e5-9fa7-dcb9789b1b47.png">

**Comment by mariobehling** [comment]
1. How do you get the location? It does not work here on Firefox on test.loklak.net. Please provide a link to live system with your changes.
2. How can the user correct the location if necessary like with twitter?
![screenshot from 2015-08-01 14 06 36](https://cloud.githubusercontent.com/assets/1583873/9021790/8c04fd92-3856-11e5-8381-f549b77110c1.png)

**Comment by mariobehling** [comment]
Please adjust the design closer to twitter
* [ ] use twitter button as in main menu including the bird
* [ ] correct the color of the buttons to blend in (like twitter)
* [ ] change "post tweet" to "Compose new Tweet"
* [ ] all buttons should have the same color
* [ ] the blue fonts of your buttons should use the same blue color as the buttons in the top navigation bar
* [ ] the 140 character count should blend in with a grey color and turn red when it gets to the end just like twitter
* [ ] offer drop down menu as twitter and on the bottom "Turn off location"
