### ISSUE TITLE
Allow tweet attachments e.g. code as markdown content on loklak

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#94]
We can allow tweets to share their tweet in markdown which can be shown appropriately on loklak. Users should also be able to `compose` tweets in markdown and sent it to twitter.

- @Orbiter @mariobehling Discussion needed on if these tweets should be stripped of their markdown attributes and sent to Twitter in plain text without markdown, in that case how how do we store two seperate tweets.

eg.
"The __big__ brown _fox_ jumped in a `well`" sent to twitter as "The big brown fox jumped in a well"

**Comment by Orbiter** [comment]
see https://github.com/loklak/loklak_webclient/issues/97 for proposed process and markdown editor.

**Comment by mariobehling** [comment]
Just to be sure: The tweet itself, just works in the same way as twitter. There is no additional markdown. 

BUT: We have the option of additional rich text attachments and here we can have an editor. As mentioned by @Orbiter please refer to #97

**Comment by Orbiter** [comment]
for the text preview, there will be support by loklak_server, see https://github.com/loklak/loklak_server/issues/40 - this image shall be attached to the cross-posted tweet to twitter

**Comment by sudheesh001** [comment]
@Orbiter What is the API usage for this feature on the loklak_server ?

**Comment by Orbiter** [comment]
a stub for the feature was just uploaded and is life. Use the following attributes:
The GET/POST (preferred: POST) parameters are:
text:the markdown text; must include line breaks for line breaks in the resulting image
color_text: RGB color of the text
color_background: RGB color of the text background
padding: number of pixels around the text (leave empty for default number 3)
uppercase:boolean (default true) - the 5-pixel font includes lowercase chars but they don't look good.

i.e.:
http://loklak.org/vis/markdown.png?text=hello%20world%0Dhello%20universe&color_text=000000&color_background=ffffff&padding=3

**Comment by Orbiter** [comment]
Here is the process on how to show rich-text tweets, which is regulated with the message form convention for rich-text tweets in https://github.com/loklak/loklak_server/issues/66:

- when posting a rich text attachment to a tweet message, create the image for the rich text with https://github.com/loklak/loklak_server/issues/40
- You need a method to compose the rich text into the message to-be posted to loklak_server directly as well. This is regulated with https://github.com/loklak/loklak_server/issues/66
- concatenate the normal message text with `\n***\n` and the rich message text. This becomes the text to be posted to loklak_server
- then store this content to loklak_server using the /push.json api.

**Comment by mariobehling** [comment]
Please provide a link to a test system.

**Comment by mariobehling** [comment]
I do not see that this feature is finished.

**Comment by sudheesh001** [comment]
Markdown tool integrated. Highlight.js library included. Opened issue https://github.com/loklak/loklak_server/issues/102 related to this.

**Comment by sudheesh001** [comment]
Markdown tool enhanced on the server. Client side implementation and data packing is done line by line and follows markdown procedures as mentioned in http://lab.lepture.com/editor/

Pending, cross posting, tracking the cross posting all at once at https://github.com/loklak/loklak_webclient/issues/437
