### ISSUE TITLE
Attach images to the posted tweets

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#95]
- Image uploads, images can be jpg, png, gif

**Comment by Orbiter** [comment]
see https://github.com/loklak/loklak_webclient/issues/96 for proposed process

**Comment by Orbiter** [comment]
storage of such images will be with https://github.com/loklak/loklak_server/issues/42

**Comment by sudheesh001** [comment]
@Orbiter Is the server ready to handle this ? Or should the tweet be directly sent over to Twitter instead using their media upload API ?

If this has to be done via loklak server as planned, do we move the milestone ?

**Comment by Orbiter** [comment]
this is not implemented on server side, lets move the milestone.

**Comment by Orbiter** [comment]
the server is now able to handle attachments for rich tweets using the /api/asset servlet
See example in https://github.com/loklak/loklak_server/issues/42 how to use that

**Comment by mariobehling** [comment]
@sudheesh001 What has been the progress here today?

**Comment by sudheesh001** [comment]
Solving this would also resolve
- #93 
- #97 
- #94 (Markdown support yet needed from server)
The progress is that I can use the oauth values statically and push tweets but unable to retrieve the user auth values post login into the node part of the application. Will be looking into it.

**Comment by sudheesh001** [comment]
Blocked by #249 , commit for fixing https://github.com/loklak/loklak_webclient/issues/118 which makes the add photo a file picker.

**Comment by mariobehling** [comment]
* [ ] Please ensure that the photo thumbnail shows up once the image is uploaded
* [ ] Resize a copy of the photo to the maximum dimension allowed in twitter

**Comment by mariobehling** [comment]
Where can we test this?

**Comment by sudheesh001** [comment]
The PR is pending review from @prasht63 Once he reviews it, it should be good to test on test.loklak

**Comment by mariobehling** [comment]
when can this be tested on test.loklak.net?

**Comment by sudheesh001** [comment]
It can be tested now with latest deployment

**Comment by mariobehling** [comment]
![screenshot from 2015-07-25 15 45 29](https://cloud.githubusercontent.com/assets/1583873/8889673/97c0bf12-32e4-11e5-81db-5f5d44d32225.png)

Buggy implementation: More than 4 photos can be uploaded. The design of the thumbnails attached to each other. Please test more in detail yourself. Potentially more issues.

**Comment by mariobehling** [comment]
That is bad :( My unfinished tweet shows up after I login with another account.

![screenshot from 2015-07-25 15 56 50](https://cloud.githubusercontent.com/assets/1583873/8889717/2fe6fbb6-32e6-11e5-8d4e-af217b21d23e.png)
