### ISSUE TITLE
Strip EXIF data from images that are going to be uploaded through the app.

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#96]
@Orbiter The questions to consider here through out the process of discussion of implementation of this feature are

- [ ] Is there a client side service / node service which could be used to strip the EXIF from the images
- [ ] If we do it for each image that's being uploaded, the speed of the application is hampered as the image only uploads after streaming the EXIF information
- [ ] Do we upload two copies of the image, one to twitter and one to the loklak_server so that the server can retrieve the required EXIF tags and map it to the corresponding tweet object. 

@aneeshd16 @fuksi @julianfox The question to consider is, Do we get the tweet ID or `id_str` immediately as we post the tweet to twitter ? If thats the case, then we can push the image copy to a temporary cache on the `loklak_server` along with the `id_str` from where the required EXIF tags can be retrieved and appended to the object as `image_metadata`.

**Comment by Orbiter** [comment]
The question, wether or not EXIF has to be stripped must be discussed. There can be two reasons to do that: (1) the official version is, that this is a privacy feature. I don't believe that. The actual picture reveals much more privacy than some details in the exif text (2) I believe that twitter fears, that the exif data is artifically constructed to move along more data than wanted.

For now, I think we should not do anything here. What we actually want to do in the future is, to do a hosting of those images ourself. What we want to achive right now is simply the ability for the user, to post large images and see large images afterwards. The only way I see right now is, to do:
- post the image to twitter so it's compatible
- post a link within the tweet to the high-res version, which would be a link to loklak itself

I believe we need a loklak_server service for that:
- you push the image to the server for storage, in the response you get a link that you attach to the tweet

One very important thing is missing here: license of uploaded images! I suggest that we force the user to use CC0, everything else would be too complicated right now.

**Comment by sudheesh001** [comment]
@Orbiter So we deliver the image to `loklak_server` which gives us the URL of the image, which we'd be sending to twitter right, Will twitter be able to open this like an image embed in the tweet or just share a link ? Is the image storage service already present on the `loklak_server` ?

**Comment by Orbiter** [comment]
not yet, it will be delivered in an generic 'asset' servlet which may store even more data types. see: https://github.com/loklak/loklak_server/issues/42

**Comment by Orbiter** [comment]
the asset servlet is now present! We must now discuss how the cross-posting process shall happen.

**Comment by mariobehling** [comment]
Closing this issue. Relevant issue to follow up discussions seems to be this one: https://github.com/loklak/loklak_webclient/issues/97

**Comment by mariobehling** [comment]
Closing this issue. Relevant issue to follow up discussions seems to be this one: https://github.com/loklak/loklak_webclient/issues/97
