### ISSUE TITLE
Cross posts all posts to twitter to loklak server

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#97]
Large tweets that can be displayed on the `loklak_webclient` app which might include markdown and images have to be also sent to twitter but should redirect the users via a shortener share link that goes along with the tweet post so that the tweet can be viewed on loklak app.

eg. Lorem Ipsum  is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Posted to twitter converted to

Lorem Ipsum .... http://loklak.net/tweet/23716231

The question also is how do we generate the numeric ID information ?
@fuksi @aneeshd16 Could that view on the /tweet/<id> route also be integrated soon. @Orbiter what's your view here ?

**Comment by Orbiter** [comment]
Most important: there are no 'large tweets', only normal 140 character, twitter-compatible tweets with large-text attachments!

For the large-text attachment, I suggest to use http://lab.lepture.com/editor/ https://github.com/lepture/editor for the markdown. Thats easy and compatible to the markdown used here in github.

To publish such a tweet, you do two things:
- push the tweet with the markdown text to loklak_server where it is stored. You get back an image (a png) with a rendered version of the markdown text
- you push the normal tweet with the image attached to twitter

**Comment by mariobehling** [comment]
@sudheesh001 Thank you @Orbiter for clarifying. In order not to confuse this, I suggest to call any data that does not relate to the 140 characters "attachments". Please help to change this.

**Comment by mariobehling** [comment]
@Orbiter Thanks for clarifying again on gitter. I changed the title of the issue "Allow attachments to be cross posted to twitter"

**Comment by fuksi** [comment]
@sudheesh001 I just posted a new suggestion about the new route for individual tweet on #98

**Comment by Orbiter** [comment]
for cross-posting, there will be support by loklak_server to create content to be posted to twitter as image.
The issues in loklak_server are:
- for tweets with locations: https://github.com/loklak/loklak_server/issues/39
- for large texts with markdown: https://github.com/loklak/loklak_server/issues/40
- for image attachments: https://github.com/loklak/loklak_server/issues/42

**Comment by Orbiter** [comment]
for the retrieval of preview images for cross-posting, see the description of https://github.com/loklak/loklak_server/issues/39#issuecomment-109448270 for cross-posted maps

**Comment by mariobehling** [comment]
@sudheesh001 M2 has passed. Do you have an update here?

**Comment by sudheesh001** [comment]
@mariobehling https://github.com/loklak/loklak_webclient/issues/95 is a subset to this problem, the problem that we are facing currently is posting the image (read as any media) content using the hello.js API, As discussed on gitter, Because of a security reason, we can't reupload an image to a hidden element in a form, so I requested for a base64 to be generated, I am looking into the issue of how we could do this using the native Twitter API rather than hello.js, This needs some time, can it move to M2.5 ?

**Comment by mariobehling** [comment]
Thanks for the reference! Moving it to 2.5

**Comment by Orbiter** [comment]
Here is the process on how to show rich-text tweets, which is regulated with the message form convention for rich-text tweets in https://github.com/loklak/loklak_server/issues/66:

- when posting a rich text attachment to a tweet message, create the image for the rich text with https://github.com/loklak/loklak_server/issues/40
- You need a method to compose the rich text into the message to-be posted to loklak_server directly as well. This is regulated with https://github.com/loklak/loklak_server/issues/66
- concatenate the normal message text with `\n***\n` and the rich message text. This becomes the text to be posted to loklak_server
- then store this content to loklak_server using the /push.json api.

**Comment by sudheesh001** [comment]
Moving this to M3, Needs a little more work to keep it stable, buggy behaviour on requests being made

**Comment by fuksi** [comment]
Please refer back to #100 when this is done, along with a query example results in a status the rich content mentioned on top.

**Comment by mariobehling** [comment]
Test link, please.

**Comment by mariobehling** [comment]
Cannot see map tiles working.

![screenshot from 2015-07-25 16 18 09](https://cloud.githubusercontent.com/assets/1583873/8889786/c9cd2870-32e8-11e5-9610-5b780bab7f03.png)

**Comment by mariobehling** [comment]
Suggestion by @sudheesh001 
<img width="1440" alt="screen-shot-2015-08-01-at-11 33 55-am" src="https://cloud.githubusercontent.com/assets/1583873/9020865/04528156-3826-11e5-9379-569dd2b09aae.png">

Your solution also results in more clicks and I have no clue what are "large attachments". Please follow twitters design. 

Please create a mockup before you implement things.

**Comment by sudheesh001** [comment]
This issue contains a mix of many things and was mainly catered to the markdown editor integration.

As suggested
>For the large-text attachment, I suggest to use http://lab.lepture.com/editor/ https://github.com/lepture/editor for the markdown. Thats easy and compatible to the markdown used here in github.

Integrated that editor as the markdown editor.

The cross posting will all be tracked and discussed in one place https://github.com/loklak/loklak_webclient/issues/437
