### ISSUE TITLE
Implement view of a single tweet using the `id_str`

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#98]
Just like the wall and the search options, twitter also can show up individual tweets on the page, we need to implement something similar too. Please also check #97 as a part of this, a part of the problem that needs to be considered while doing this is present there.

**Comment by fuksi** [comment]
How it works currently on twitter is when you clicked for  ```Details```, the individual tweet is opened in a separate window/tab. If we create this view as a new state, e.g. ```/tweet/some_ID```, it's totally possible, except the fact that mark up on ```/search?q=...``` is gone, and the user have to do the search again (says he/she wants to back to the search results). 

I suggest the we can create a popup modal sort of [like this](http://vodkabears.github.io/remodal/), so we can stay in the current view (```search```) 

What do you think @aneeshd16?

**Comment by aneeshd16** [comment]
@fuksi We can have two views:
1. An isolated tweet view. `/tweet/some_ID` if someone has linked to that individual tweet.
2. A popup modal like you suggested if someone wants to view the tweet from a search result.

**Comment by fuksi** [comment]
Agree. I'll create an issue for this in my feature, and close this issue when i'm done :)

**Comment by sudheesh001** [comment]
As @aneeshd16 suggested, its best to go with both. an isolated view so that someone can directly land onto the tweet and also the popup modal in case someone clicks on a tweet on the tweet homepage

**Comment by Orbiter** [comment]
The single view does not show media, i.e. videos which is visible in the column view.
Example: http://aneesh-ojl02abl.cloudapp.net:3000/tweet?q=id:608394531856359424

**Comment by Orbiter** [comment]
please add all media views to the single tweet view

**Comment by fuksi** [comment]
Done yesterday with https://github.com/loklak/loklak_webclient/pull/152

**Comment by Orbiter** [comment]
This is completely broken now, maybe after a style change! Why don't you see these effects yourself?
Please also add the view of movie attachments:
- the field 'videos' now contains an array of video content
- if the field 'videos' is filled, the field 'images' contain poster-Images for the videos
- the videos-Field may contain: mp4 video files, youtube links (youtube.com and youtu.be) and vimeo links

**Comment by fuksi** [comment]
Fixed, along with adding video. #182
